---
title: "Gastrulation: MOFA applied to E7.5 stage"
output: 
  BiocStyle::html_document: 
    fig_width: 10
    fig_height: 8
---


```{r}
library(BioFAMtools)
library(data.table)
library(purrr)
library(ggplot2)
library(reticulate)
library(RColorBrewer)
```

```{r}
source("/Users/ricard/gastrulation/metacc/mofa/load_settings.R")
```


<!-- Load pretrained model -->
```{r}
file <- paste0(io$outdir,"/hdf5/test.hdf5")
model <- load_model(file=file)
```

```{r}
# sample_metadata <- fread(io$sample.metadata,stringsAsFactors=T) %>%
#   .[,c("sample","stage","lineage","lineage10x_2")] %>%
#   .[,stage_lineage:=as.factor(paste(stage,lineage,sep="_"))] %>%
#   .[,stage_lineage:=as.factor(paste(stage,lineage10x_2,sep="_"))] %>%
#   droplevels()
```

<!-- Filter sample metadata -->
```{r}
sample_metadata_filt <- sample_metadata %>% setkey(sample) %>% .[samples_names(model)]

sample_metadata_filt <- sample_metadata_filt %>%
  # .[stage_lineage%in%c("E7.5_Mature_mesoderm","E7.5_Nascent_mesoderm"),stage_lineage:="E7.5_Mesoderm"] %>%
  .[stage_lineage%in%c("E7.5_Embryonic_endoderm","E7.5_Visceral_endoderm","E7.5_Notochord"),stage_lineage:="E7.5_Endoderm"] %>%
  .[stage_lineage%in%c("E7.5_Primitive_Streak","E6.5_Primitive_Streak","E6.5_Anterior_Primitive_Streak","E7.5_Anterior_Primitive_Streak"),stage_lineage:="Primitive_Streak"] %>%
  .[stage_lineage%in%c("E7.5_Epiblast","E6.5_Epiblast","E5.5_Epiblast"),stage_lineage:="Epiblast"] %>%
  # .[stage_lineage%in%c("E7.5_Surface_ectoderm","E7.5_ExE_endoderm","E7.5_PGC","E7.5_Endoderm"),stage_lineage:="E7.5_NA"] %>%
  droplevels()
```

<!-- Rename views -->
```{r}
opts$anno_names <- c(

  "acc_H3K27ac_distal_E7.5_Mes_intersect12"="Acc Mes Distal H3K27ac",
  "acc_H3K27ac_distal_E7.5_Ect_intersect12"="Acc Ect Distal H3K27ac",
  "acc_H3K27ac_distal_E7.5_End_intersect12"="Acc End Distal H3K27ac",
  "acc_genebody"="Acc Gene bodies",
  "acc_prom_200_200"="Acc CGI Promoters",
  
  "met_H3K27ac_distal_E7.5_Mes_intersect12_500"="Met Mes Distal H3K27ac",
  "met_H3K27ac_distal_E7.5_Ect_intersect12_500"="Met Ect Distal H3K27ac",
  "met_H3K27ac_distal_E7.5_End_intersect12_500"="Met End Distal H3K27ac",
  "met_genebody"="Met Gene bodies",
  "met_prom_2000_2000"="Met Promoters"
)

views_names(model) <- stringr::str_replace_all(views_names(model), opts$anno_names)
```


```{r}
p <- plot_factors(
  model, 
  factors = c(1,2),
  # color_by = "group"
  color_by = as.character(sample_metadata_filt$stage_lineage)
  # shape_by = as.character(sample_metadata_filt$stage_lineage)
)

print(p)
```

