---
title: "Gastrulation scNMT-seq: dimensionality reduction on the DNA methylation data"
output:
  BiocStyle::html_document: 
    fig_width: 10
    fig_height: 8
---

```{r load_modules, echo=FALSE, include=FALSE}
library(MOFA)
library(umap)
library(Rtsne)
```

Load settings
```{r}
source("/Users/ricard/gastrulation/met/dimensionality_reduction/load_settings.R")
```

Load pretrained model
```{r}
model <- loadModel(io$outfile)
```

Sort sample metadata to match the order of the sample names in MOFA
```{r}
sample_metadata_filt <- sample_metadata %>% setkey(id_met) %>% .[MOFA::sampleNames(model)]
```

Classify cells as embryonic or extra-embryonic
```{r}
sample_metadata_filt %>% 
  .[,embryonic:=ifelse(lineage10x_2%in%c("Visceral_endoderm","Primitive_endoderm"),"ExE","Embryonic")]
```

Calculate variance explained per factor and view
```{r}
r2 <- calculateVarianceExplained(model)$R2PerFactor
```

<!-- (Optional) Rotate a factor -->
```{r}
# model@Expectations$Z[,1] <- -model@Expectations$Z[,1]
```

Scatter plots of Factor 1 vs Factor 2
```{r}
p <- plotFactorScatter(
  model, 
  factors=c("LF1","LF2"), 
  color_by=sample_metadata_filt$lineage10x_2
)

p <- p + 
  scale_colour_manual(values=opts$colors) +
  labs(x=sprintf("Factor 1 (%.2f%%)",r2["LF1",]*100), y=sprintf("Factor 2 (%.2f%%)",r2["LF2",]*100))
print(p)
```

<!-- (Optional) Non-linear dimensionality reduction from MOFA factors -->
```{r}
# # Define settings
# algorithms <- c("umap")
# 
# # Fetch factors
# Z <- getFactors(model)
# 
# for (algorithm in algorithms) {
# 
#   set.seed(1)
#   if (algorithm=="tsne") {
#     tsne <- Rtsne(Z, check_duplicates=FALSE, pca=FALSE, theta=0.5, dims=2)
#     Z.out <- tsne$Y
#   } else if (algorithm=="umap") {
#     umap.defaults$n_neighbors <- 20
#     umap.defaults$min_dist <- 0.7
#     umap.out <- umap(Z, config = umap.defaults)
#     Z.out <- umap.out$layout
#   }
# 
#   to.plot <- Z.out %>% as.data.table %>% .[,id_met:=rownames(Z)] %>%
#       merge(sample_metadata, by="id_met")
# 
#   p <- ggplot(to.plot, aes(x=V1, y=V2, color=lineage10x_2)) +
#     geom_point(alpha=0.7, size=1.5) +
#     scale_color_manual(values=opts$colors) +
#     guides(colour = guide_legend(override.aes = list(size=3))) +
#     labs(x="Dimension 1", y="Dimension 2") +
#     theme_classic() +
#     theme(
#       axis.text = element_blank(),
#       axis.ticks = element_blank(),
#       legend.position = "none"
#     )
# 
# # pdf(sprintf("%s/pdf/mofa+umap_met_%s_%s.pdf",io$outdir,paste(names(opts$annos), collapse="_"), paste(opts$stage_lineage, collapse="_")), useDingbats = F, onefile = F, width=6, height=6)
# print(p)
# # dev.off()
# }
```

