---
title: "Gastrulation: scatterplot of Met/RNA and Acc/RNA correlation coefficients in promoters"
output: 
  BiocStyle::html_document: 
    fig_width: 12
    fig_height: 8
---

```{r echo=FALSE, include=FALSE}
suppressPackageStartupMessages(library(purrr))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(data.table))
```

<!-- Define I/O and options -->
```{r echo=TRUE, include=FALSE}

#########
## I/O ##
#########

io   <- list()
io$base_dir   <- "/Users/ricard/data/gastrulation"
io$sample.metadata <- paste0(io$base_dir,"/sample_metadata.txt")
# io$annos.dir  <- paste0(io$base_dir, "/features/filt")
io$rna.file   <- paste0(io$base_dir, "/rna/parsed/SingleCellExperiment.rds")
io$met.dir   <- paste0(io$base_dir, "/met/parsed")
io$acc.dir   <- paste0(io$base_dir, "/acc/parsed")
io$outdir <- "/Users/ricard/data/gastrulation_norsync_stuff/metaccrna/cor"

#############
## Options ##
#############

opts <- list()

# Multiple testing correction options
opts$threshold_fdr  <- 0.10

opts$met.annos <- c(
  "prom_2000_2000"="Promoters"
)

opts$acc.annos <- c(
  "prom_2000_2000"="Promoters"
)

# Define which stage and lineages to look at 
opts$stages <- c("E5.5","E6.5","E7.5")
opts$lineages <- c(
  "Nascent mesoderm",
  "Primitive Streak",
  "Mixed mesoderm",
  "Epiblast",
  "Rostral neurectoderm",
  "Gut",
  "Embryonic endoderm",
  "Paraxial mesoderm",
  "Notochord",
  "Pharyngeal mesoderm",
  "Mature mesoderm",
  "Intermediate mesoderm",
  "Somitic mesoderm",
  "Caudal mesoderm",
  "Rostral neuroectoderm",
  "Caudal neurectoderm",
  "Caudal Mesoderm",
  "Def. endoderm"
)
opts$stage_lineage <- as.vector(outer(opts$stages,opts$lineages, paste, sep="_"))
opts$stage_lineage <- opts$stage_lineage[!opts$stage_lineage %in% c("E7.5_Epiblast","E7.5_Primitive Streak")]

# Define which cells to use
tmp <- fread(io$sample.metadata) %>% 
  .[,stage_lineage:=paste(stage,lineage10x,sep="_")] %>%
  # .[assay=="scNMT"] %>%
  .[stage_lineage%in%opts$stage_lineage]
opts$met_cells <- tmp %>% .[pass_metQC==T,id_met]
opts$rna_cells <- tmp %>% .[pass_rnaQC==T,id_rna]
opts$acc_cells <- tmp %>% .[pass_accQC==T,id_acc]


```

<!-- Load sample metadata -->
```{r load_metadata}
sample_metadata <- fread(io$sample.metadata) %>%
  .[,c("sample","id_met","id_acc","id_rna","stage","lineage10x_2")] %>%
  .[,stage_lineage:=as.factor(paste(stage,lineage10x_2,sep="_"))] %>%
  .[id_met%in%opts$met_cells | id_rna%in%opts$rna_cells | id_acc%in%opts$acc_cells]
```

<!-- Load methylation data -->
```{r load_data, echo=FALSE, include=FALSE}
met_dt <- lapply(opts$met.annos, function(n) {
  fread(csprintf("%s/%s.tsv.gz",io$met.dir,n)) %>% .[V1%in%opts$met_cells]
}) %>% rbindlist
colnames(met_dt) <- c("id_met","id","anno","Nmet","N","rate")
```

<!-- Load accessibility data -->
```{r load_data, echo=FALSE, include=FALSE}
acc_dt <- lapply(opts$acc.annos, function(n) {
  fread(sprintf("%s/%s.tsv.gz",io$acc.dir,n)) %>% .[V1%in%opts$acc_cells]
}) %>% rbindlist
colnames(acc_dt) <- c("id_acc","id","anno","Nacc","N","rate")
```

<!-- Load RNA data -->
```{r}
# Load scater object
sce <- readRDS(io$rna.file)

# Filter cells
sce <- sce[,colnames(sce) %in% opts$rna_cells]


# Subset genes
genes.factor1 <- c("Fn1", "Id2", "Fgf3", "Ifitm1", "Dll3", "Cyp26a1", "T", "Lefty2", "Tdgf1", "Mesp1")
genes.factor2 <- c("Krt18", "Phlda2", "Arl4a", "B9d1", "Tmem107", "Mlf1", "Krt8", "Tagln2", "Calca", "T")
genes <- unique(c(genes.factor1,genes.factor2))

# convert gene names from ensembl ID to gene symbols
rownames(sce) <- rowData(sce)$symbol

# Create data.table
rna_dt <- exprs(sce[genes,]) %>% t %>% as.data.table(keep.rownames = "id_rna") %>% 
  melt(id.vars = "id_rna", value.name = "expr", variable.name = "ens_id") %>%
  merge(rowData(sce) %>% as.data.frame(row.names = rownames(sce)) %>% tibble::rownames_to_column("ens_id") %>% .[,c("symbol","ens_id")] %>% setnames("symbol","gene"))
```

Merge DNA methylation and

