---
title: "Gastrulation: scatterplot of Met/RNA and Acc/RNA correlation coefficients in promoters"
output: 
  BiocStyle::html_document: 
    fig_width: 12
    fig_height: 8
---

```{r echo=FALSE, include=FALSE}
suppressPackageStartupMessages(library(purrr))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(data.table))
```

<!-- Define I/O and options -->
```{r echo=TRUE, include=FALSE}

## I/O ##
io   <- list()
io$base_dir   <- "/Users/ricard/data/gastrulation"
io$in.sample_metadata <- paste0(io$base_dir,"/sample_metadata.txt")
io$annos_dir  <- paste0(io$base_dir, "/features/filt")
io$rna_file   <- paste0(io$base_dir, "/rna/parsed/SingleCellExperiment.rds")
io$met_dir   <- paste0(io$base_dir, "/met/parsed")
io$metrna.cor <- "/Users/ricard/data/gastrulation_norsync_stuff/metrna/cor/metrna_cor_enhancers.txt"
io$accrna.cor <- "/Users/ricard/data/gastrulation_norsync_stuff/accrna/cor/accrna_cor_enhancers.txt"
io$diff.rna <- "/Users/ricard/data/gastrulation/rna/differential"
io$outdir <- "/Users/ricard/data/gastrulation_norsync_stuff/metaccrna/cor"

## Options ##
opts <- list()

# Multiple testing correction options
opts$min.fdr  <- 0.10

# Minimum log fold change in RNA expression for significance
opts$min.rna.diff <- 1

opts$met.annos <- c(
  "H3K27ac_distal_E7.5_Mes_intersect12" = "Mesoderm enhancers",
  "H3K27ac_distal_E7.5_End_intersect12" = "Endoderm enhancers",
  "H3K27ac_distal_E7.5_Ect_intersect12" = "Ectoderm enhancers"
)

opts$acc.annos <- c(
  "H3K27ac_distal_E7.5_Mes_intersect12" = "Mesoderm enhancers",
  "H3K27ac_distal_E7.5_End_intersect12" = "Endoderm enhancers",
  "H3K27ac_distal_E7.5_Ect_intersect12" = "Ectoderm enhancers"
)

# Top genes to label
opts$top_genes <- 5

# Define colors
opts$colors <- c(
  "Mesoderm enhancers" = "#CD3278",
  "Endoderm enhancers" = "#43CD80",
  "Ectoderm enhancers" = "steelblue"
)

```

<!-- Load results of Met/RNA coupling across cells -->
```{r}
metrna <- fread(io$metrna.cor)
metrna_filt <- metrna %>% .[anno%in%names(opts$met.annos)] %>%
  .[,anno:=stringr::str_replace_all(anno, opts$met.annos)]
```

<!-- Load results of Acc/RNA coupling across cells -->
```{r}
accrna <- fread(io$accrna.cor)
accrna_filt <- accrna %>% .[anno%in%names(opts$acc.annos)] %>%
  .[,anno:=stringr::str_replace_all(anno, opts$acc.annos)]
```

<!-- Load differential expression results -->
```{r}
# Mesoderm-specific
diff.rna.mes <- fread(cmd=sprintf("zcat < %s/E7.5Mesoderm_vs_E7.5EndodermEctoderm.txt.gz",io$diff.rna)) %>%
  .[,lineage:="Mesoderm"] %>% .[,sig:=padj_fdr<opts$min.fdr & abs(logFC)>opts$min.rna.diff]

# Ectoderm-specific
diff.rna.ect <- fread(cmd=sprintf("zcat < %s/E7.5Ectoderm_vs_E7.5MesodermEndoderm.txt.gz",io$diff.rna)) %>%
  .[,lineage:="Ectoderm"] %>% .[,sig:=padj_fdr<opts$min.fdr & abs(logFC)>opts$min.rna.diff]

# Endoderm-specific
diff.rna.end <- fread(cmd=sprintf("zcat < %s/E7.5Endoderm_vs_E7.5MesodermEctoderm.txt.gz",io$diff.rna)) %>%
  .[,lineage:="Endoderm"] %>% .[,sig:=padj_fdr<opts$min.fdr & abs(logFC)>opts$min.rna.diff]

diff.rna <- do.call("rbind", list(diff.rna.mes,diff.rna.end,diff.rna.ect))
rm(diff.rna.mes,diff.rna.ect,diff.rna.end)
```

<!-- Combine Met/RNA and Acc/RNA correlations -->
```{r}
cor <- rbind(
  metrna_filt[,type:="metrna"], 
  accrna_filt[,type:="accrna"]
) %>% dcast(id+gene+anno~type, value.var=c("padj_fdr","log_padj_fdr","r","sig")) %>% .[complete.cases(.)] %>%
  .[,sig:=sig_metrna | sig_accrna]

# sig_hits <- cor %>% .[sig==TRUE,gene] %>% unique()
```

```{r}
sig.hits <- diff.rna[sig==T,symbol]
```

<!-- Scatterplot -->
```{r}
to.plot <- cor %>%
  .[,padj_min:=min(padj_fdr_metrna,padj_fdr_accrna),by=c("gene","anno")] %>%
  setorder(padj_min) %>%
  .[,i:=1:nrow(.)]

to.plot.ect <- to.plot[sig==T & gene%in%sig.hits & anno=="Ectoderm enhancers"] %>% .[,i:=1:nrow(.)] %>% .[i<=opts$top_genes]
to.plot.end <- to.plot[sig==T & gene%in%sig.hits & anno=="Endoderm enhancers"] %>% .[,i:=1:nrow(.)] %>% .[i<=opts$top_genes]
to.plot.mes <- to.plot[sig==T & gene%in%sig.hits & anno=="Mesoderm enhancers"] %>% .[,i:=1:nrow(.)] %>% .[i<=opts$top_genes]

p <- ggplot(to.plot, aes(x=r_metrna, y=r_accrna)) +
  geom_segment(aes(x=-0.75, xend=0.25, y=0, yend=0), size=0.25, color="orange") +
  geom_segment(aes(x=0, xend=0, y=-0.25, yend=0.55), size=0.25, color="orange") +
  geom_point(alpha=0.1, size=0.7, data=to.plot[sig==F]) +
  geom_point(aes(color=anno), alpha=1.0, size=1, data=to.plot[sig==T]) +
  ggrepel::geom_text_repel(aes(x=r_metrna, y=r_accrna, label=gene, color=anno), size=5, force=1, data=to.plot.ect) +
  ggrepel::geom_text_repel(aes(x=r_metrna, y=r_accrna, label=gene, color=anno), size=5, force=1, data=to.plot.end) +
  ggrepel::geom_text_repel(aes(x=r_metrna, y=r_accrna, label=gene, color=anno), size=5, force=1, data=to.plot.mes) +
  scale_color_manual(values=opts$colors) +
  # coord_cartesian(xlim=c(-0.75,0.2), ylim=c(-0.2,0.60)) +
  labs(x="Met/RNA correlation", y="Acc/RNA correlation") +
  theme(
    axis.text.x = element_text(size=rel(1.1), color='black'),
    axis.text.y = element_text(size=rel(1.1), color='black'),
    axis.title.x = element_text(size=rel(1.2), color='black'),
    axis.title.y = element_text(size=rel(1.2), color='black'),
    legend.position = "none",
    panel.background = element_blank()
  )
print(p)

pdf(paste0(io$outdir,"/scatterplot_enhancers.pdf"), width=6.7, height=5.4, useDingbats = F)
print(p)
dev.off()
```
