---
title: "Gastrulation:"
output: 
  BiocStyle::html_document: 
    fig_width: 12
    fig_height: 8
---

```{r echo=FALSE, include=FALSE}
suppressPackageStartupMessages(library(purrr))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(data.table))
```

<!-- Define functions -->
```{r echo=FALSE, include=FALSE}
scatter_theme <- function(){
  p <- theme(
    axis.text=element_text(size=rel(1.1), color='black'),
    axis.title=element_text(size=rel(1.2), color='black'),
    # axis.title.y = element_text(margin=margin(0,10,0,0)),
    # axis.title.x = element_text(margin=margin(10,0,0,0)),
    legend.position="none",
    panel.border=element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank()
  )
}
```

<!-- Define I/O and options -->
```{r echo=TRUE, include=FALSE}

## I/O ##
io   <- list()
io$base_dir   <- "/Users/ricard/data/gastrulation"
io$in.sample_metadata <- paste0(io$base_dir,"/sample_metadata.txt")
io$annos_dir  <- paste0(io$base_dir, "/features/filt")
io$rna_file   <- paste0(io$base_dir, "/rna/parsed/SingleCellExperiment.rds")
io$met_dir   <- paste0(io$base_dir, "/met/parsed")
io$diff.rna <- "/Users/ricard/data/gastrulation/rna/differential"
io$outdir <- "/Users/ricard/data/gastrulation_norsync_stuff/metaccrna/cor"

## Options ##
opts <- list()

# Multiple testing correction options
opts$threshold_fdr  <- 0.10

opts$met.annos <- c(
  "prom_2000_2000"="Promoters"
)

opts$acc.annos <- c(
  "prom_2000_2000"="Promoters"
)
```

<!-- Load results of Met/RNA coupling across cells -->
```{r}
metrna <- fread("/Users/ricard/data/gastrulation_norsync_stuff/metrna/cor/metrna_cor_promoters.txt")
metrna_filt <- metrna %>% .[anno%in%names(opts$met.annos)] %>%
  .[,anno:=stringr::str_replace_all(anno, opts$met.annos)]
```

```{r}
metrna[,sum(sig==T),by="anno"]
```

<!-- Load results of Acc/RNA coupling across cells -->
```{r}
accrna <- fread("/Users/ricard/data/gastrulation_norsync_stuff/accrna/cor/accrna_cor_promoters.txt")
accrna_filt <- accrna %>% .[anno%in%names(opts$acc.annos)] %>%
  .[,anno:=stringr::str_replace_all(anno, opts$acc.annos)]
```

<!-- Load differential expression results -->
```{r}
# diff.rna.mes <- fread(sprintf("zcat < %s/E7.5Mes_vs_E7.5EctEnd.txt.gz", io$diff.rna)) %>% .[padj_fdr<=opts$threshold_fdr]
# diff.rna.ect <- fread(sprintf("zcat < %s/E7.5Ect_vs_E7.5MesEnd.txt.gz", io$diff.rna)) %>% .[padj_fdr<=opts$threshold_fdr]
# diff.rna.end <- fread(sprintf("zcat < %s/E7.5End_vs_E7.5EctMes.txt.gz", io$diff.rna)) %>% .[padj_fdr<=opts$threshold_fdr]
# diff.rna.pluripotency <- fread(sprintf("%s/E4.5Epiblast_vs_E7.5EctodermEndodermMesoderm.txt.gz", io$diff.rna)) %>%
#   .[padj_fdr<=opts$threshold_fdr]
# diff.rna.pluripotency <- fread(sprintf("%s/E4.5E5.5Epiblast_vs_E7.5EctodermEndodermMesoderm.txt.gz", io$diff.rna)) %>%
#   .[padj_fdr<=opts$threshold_fdr]
```

<!-- Combine Met/RNA and Acc/RNA coupling -->
```{r}
cor <- rbind(
  metrna_filt[,type:="metrna"], 
  accrna_filt[,type:="accrna"]
) %>% data.table::dcast(gene+anno~type, value.var=c("padj_fdr","log_padj_fdr","r","sig")) %>% .[complete.cases(.)] %>%
  .[,sig:=sig_metrna & sig_accrna]

sig_hits <- cor %>% .[sig==TRUE,gene] %>% unique()
```

```{r}
diff.rna.pluripotency <- fread(sprintf("%s/E4.5Epiblast_vs_E7.5EctodermEndodermMesoderm.txt.gz", io$diff.rna)) %>%
  .[,c("symbol","logFC","padj_fdr")] %>% setnames("symbol","gene")

to.plot <- cor[anno=="Promoters"] %>% 
  merge(diff.rna.pluripotency,by="gene")
```

<!-- Volcano plot with differential RNA expression in the X-axis and Met/RNA correlation in the Y-axis -->
```{r}
negative_hits <- to.plot[sig_metrna==TRUE & logFC<0,gene]
positive_hits <- to.plot[sig_metrna==TRUE & logFC>0,gene]
all <- nrow(to.plot)
    
p <- ggplot(to.plot, aes(x=logFC, y=log_padj_fdr_metrna)) +
  labs(title="", x="Differential RNA expression", y=expression(paste("Met/RNA -log"[10],"(p-value)"))) +
  #geom_hline(yintercept = -log10(opts$threshold_fdr), color="blue") +
  # geom_segment(aes(x=0, xend=0, y=0, yend=7.1), color="orange") +
  geom_point(aes(color=sig_metrna), size=2) +
  scale_color_manual(values=c("black","red")) +
  annotate("text", x=0, y=max(to.plot$log_padj_fdr_metrna), size=7, label=sprintf("(%d)", all)) +
  annotate("text", x=-7, y=max(to.plot$log_padj_fdr_metrna), size=7, label=sprintf("%d (-)",length(negative_hits))) +
  annotate("text", x=7, y=max(to.plot$log_padj_fdr_metrna), size=7, label=sprintf("%d (+)",length(positive_hits))) +
  scatter_theme()

nlabel <- 15
p <- p + ggrepel::geom_text_repel(
  data=to.plot[sig_metrna==TRUE] %>% setkey(padj_fdr_metrna) %>% head(n=nlabel),
  aes(x=logFC, y=log_padj_fdr_metrna, label=gene), size=5, color="red"
)

# pdf(paste0(io$outdir,"/metrna_volcano.pdf"), width=5.5, height=7, useDingbats = F)
p
# dev.off()
```

<!-- Volcano plot with differential RNA expression in the X-axis and Acc/RNA correlation in the Y-axis -->
```{r}
negative_hits <- to.plot[sig_accrna==TRUE & logFC<0,gene]
positive_hits <- to.plot[sig_accrna==TRUE & logFC>0,gene]
all <- nrow(to.plot)
    
p <- ggplot(to.plot, aes(x=logFC, y=log_padj_fdr_accrna)) +
  labs(title="", x="Differential RNA expression", y=expression(paste("Acc/RNA -log"[10],"(p-value)"))) +
  #geom_hline(yintercept = -log10(opts$threshold_fdr), color="blue") +
  # geom_segment(aes(x=0, xend=0, y=0, yend=7.1), color="orange") +
  geom_point(aes(color=sig_accrna), size=2) +
  scale_color_manual(values=c("black","red")) +
  annotate("text", x=0, y=max(to.plot$log_padj_fdr_accrna), size=7, label=sprintf("(%d)", all)) +
  annotate("text", x=-7, y=max(to.plot$log_padj_fdr_accrna), size=7, label=sprintf("%d (-)",length(negative_hits))) +
  annotate("text", x=7, y=max(to.plot$log_padj_fdr_accrna), size=7, label=sprintf("%d (+)",length(positive_hits))) +
  scatter_theme()

p <- p + ggrepel::geom_text_repel(
  data=to.plot[sig_accrna==TRUE] %>% setkey(padj_fdr_accrna) %>% head(n=nlabel),
  aes(x=logFC, y=log_padj_fdr_accrna, label=gene), size=5, color="red"
)

# pdf(paste0(io$outdir,"/accrna_volcano.pdf"), width=5.5, height=7, useDingbats = F)
p
# dev.off()
```

```{r}
a <- to.plot[sig_accrna==TRUE,gene]
b <- to.plot[sig_metrna==TRUE,gene]
length(unique(c(a,b)))
```

<!-- Plot fraction of significant Met/RNA correlations -->
```{r}
tmp <- diff.rna[padj_fdr<=opts$threshold_fdr] %>% 
  .[abs(logFC)>2.5] %>% .[,c("gene","logFC")] %>%
  merge(metrna_filt[,c("gene","sig")], by="gene") %>%
  .[,type:=ifelse(logFC>0,"(+)","(-)")] %>%
  # .[,sum(sig),by="type"]
  # .[,100*mean(sig),by="type"]
  .[,.N,by="type"]

p <- ggplot(tmp, aes(x=type, y=V1)) +
  labs(title="", x="", y="% of significant correlations") +
  geom_bar(stat="identity", fill="grey", color="black") +
  # coord_cartesian(ylim=c(0,30)) +
  scatter_theme()
p

# pdf(paste0(io$outdir,"/metrna_sigcor.pdf"), width=6, height=4.5, useDingbats = F)
# p
# dev.off()
```

<!-- Plot fraction of significant Acc/RNA correlations -->
```{r}
tmp <- diff.rna[padj_fdr<=opts$threshold_fdr] %>% 
  .[abs(logFC)>2.5] %>% .[,c("gene","logFC")] %>%
  merge(accrna_filt[,c("gene","sig")], by="gene") %>%
  .[,type:=ifelse(logFC>0,"Up-regulated","Down-regulated")] %>%
  # .[,100*mean(sig),by="type"]
  .[,.N,by="type"]
  # .[,sum(sig),by="type"]
  # .[,sum(sig),by="type"]

p <- ggplot(tmp, aes(x=type, y=V1)) +
  labs(title="", x="", y="% of significant correlations") +
  geom_bar(stat="identity", fill="grey", color="black") +
  # coord_cartesian(ylim=c(0,30)) +
  scatter_theme()
p
# pdf(paste0(io$outdir,"/accrna_sigcor.pdf"), width=6, height=6, useDingbats = F)
# p
# dev.off()
```
