---
title: "Gastrulation scNMT-seq: box plots of DNA methylation and chromatin accessibiliy levels in neuroectoderm vs pluripotency enhancers"
output:
  BiocStyle::html_document: 
    toc: false
    fig_width: 10
    fig_height: 8
---

```{r load_modules, echo=FALSE, include=FALSE}
library(data.table)
library(purrr)
library(ggplot2)
library(ggpubr)
```

<!-- Define I/O and options -->
```{r define_opts, echo=FALSE}
source("/Users/ricard/gastrulation/metacc/boxplots_enhancers/pluripotency_vs_neuroectoderm/load_settings.R")
source("/Users/ricard/gastrulation/metacc/boxplots_enhancers/utils.R")
io$esc_vs_brain <- "/Users/ricard/data/gastrulation/H3K27ac/E7.5_enhancers_Ect_ESC_brain_top250.txt"
```

<!-- Load sample metadata -->
```{r load_metadata}
sample_metadata <- fread(io$sample.metadata) %>%
  .[,c("sample","id_acc","id_met","id_rna","stage","lineage10x_2")] %>%
  .[,stage_lineage:=paste(stage,lineage10x_2,sep=" ")] %>%
  .[id_met%in%opts$met_cells | id_acc%in%opts$acc_cells]
```

<!-- Load methylation data -->
```{r load_data, echo=FALSE, include=FALSE}
met_dt <- lapply(names(opts$met.annos), function(n) {
  data <- fread(sprintf("%s/%s.tsv.gz",io$met.dir,n)) %>% .[V1%in%opts$met_cells]
}) %>% rbindlist %>% setnames(c("id_met","id","anno","Nmet","Ntotal","rate"))
```

<!-- Load accessibility data -->
```{r load_data, echo=FALSE, include=FALSE}
acc_dt <- lapply(names(opts$acc.annos), function(n) {
  data <- fread(sprintf("%s/%s.tsv.gz",io$acc.dir,n)) %>% .[V1%in%opts$acc_cells]
}) %>% rbindlist %>% setnames(c("id_acc","id","anno","Nmet","Ntotal","rate"))
```

<!-- Merge data with metadata -->
```{r merge}
acc_dt <- merge(acc_dt, sample_metadata, by="id_acc") %>% droplevels()
met_dt <- merge(met_dt, sample_metadata, by="id_met") %>% droplevels()
```

<!-- Rename genomic contexts -->
```{r}
met_dt <- met_dt %>% .[,anno:=stringr::str_replace_all(anno,opts$met.annos)]
acc_dt <- acc_dt %>% .[,anno:=stringr::str_replace_all(anno,opts$acc.annos)]
```

<!-- Filter by minimum number of measurements per cell -->
```{r}
opts$min.observations <- 15
acc_dt <- acc_dt[,N:=.N, by=c("sample","stage_lineage","anno")] %>% .[N>=opts$min.observations] %>% .[,N:=NULL]
met_dt <- met_dt[,N:=.N, by=c("sample","stage_lineage","anno")] %>% .[N>=opts$min.observations] %>% .[,N:=NULL]
```

<!-- Split ectoderm enhancers into Midbrain or Pluripotency -->
```{r}
tmp <- fread(io$esc_vs_brain) %>% 
  .[,c("chr","start","end","class","id")] %>%
  .[,class:=stringr::str_replace_all(class,"brain","Neuroectoderm enhancers")] %>%
  .[,class:=stringr::str_replace_all(class,"esc","Pluripotency enhancers")]

met_dt.1 <- met_dt[anno!="Ectoderm enhancers"]
acc_dt.1 <- acc_dt[anno!="Ectoderm enhancers"]
met_dt.2 <- met_dt[anno=="Ectoderm enhancers"] %>% merge(tmp[,c("id","class")], by="id") %>% 
  .[,anno:=class] %>% .[,class:=NULL]
acc_dt.2 <- acc_dt[anno=="Ectoderm enhancers"] %>% merge(tmp[,c("id","class")], by="id") %>% 
  .[,anno:=class] %>% .[,class:=NULL]

met_dt <- rbind(met_dt.1,met_dt.2)
acc_dt <- rbind(acc_dt.1,acc_dt.2)

rm(met_dt.1,met_dt.2,acc_dt.1,acc_dt.2)
```


<!-- Generate boxplots of (unnormalised) rates -->

DNA methylation
```{r}
foo.met <- met_dt %>%
  .[,.(rate=100*(sum(Nmet)/sum(Ntotal))),by=c("sample","stage_lineage","anno")] %>%
  .[,stage_lineage:=factor(stage_lineage, levels=names(colors))]

p <- ggboxplot(foo.met, x = "stage_lineage", y = "rate", fill="grey80", coef=1, outlier.shape=NA) +
  scale_fill_manual(values=colors) +
  labs(x="", y="Methylation (%)") +
  facet_wrap(~anno, nrow=1, scales="fixed") +
  # stat_compare_means(aes(label = paste0("p = ", ..p.format..)), label.y = 80, method="t.test", size=5) +
  coord_cartesian(ylim=c(0,85)) +
  theme(
    strip.background = element_rect(fill="#F37A71"),
    # axis.text.x = element_text(size=rel(0.9), color="black"),
    axis.text.x = element_blank(),
    axis.title.y = element_text(size=rel(1.4), color="black"),
    strip.text = element_text(size=rel(1.3), color="black"),
    legend.position = "none"
  )

pdf(paste0(io$outdir,"/boxplots_met_top250.pdf"), width=opts$width, height=opts$height/1.5)
print(p)
dev.off()
```

Chromatin accessibility
```{r}
foo.acc <- acc_dt %>%
  .[,.(rate=100*(sum(Nmet)/sum(Ntotal))),by=c("sample","stage_lineage","anno")] %>%
  .[,stage_lineage:=factor(stage_lineage, levels=names(colors))]

p <- ggboxplot(foo.acc, x = "stage_lineage", y = "rate", fill="grey80", outlier.shape=NA) +
  scale_fill_manual(values=colors) +
  labs(x="", y="Accessibility (%)") +
  facet_wrap(~anno, nrow=1, scales="fixed") +
  # stat_compare_means(aes(label = paste0("p = ", ..p.format..)), label.y = 63, method="t.test", size=5) +
  coord_cartesian(ylim=c(25,64)) +
  theme(
    strip.background = element_rect(fill="#00BFC4"),
    # axis.text.x = element_text(size=rel(0.9), color="black"),
    axis.text.x = element_blank(),
    axis.title.y = element_text(size=rel(1.4), color="black"),
    strip.text = element_text(size=rel(1.3), color="black"),
    legend.position = "none"
  )

pdf(paste0(io$outdir,"/boxplots_acc_top250.pdf"), width=opts$width, height=opts$height/1.5)
print(p)
dev.off()
```

```{r}
stop()
```


<!-- Generate boxplots of rates normalised to global levels -->

```{r}
my_comparisons <- list( 
  c("E4.5 Epiblast", "E5.5 Epiblast"),
  c("E5.5 Epiblast", "E6.5 Epiblast"),
  c("E6.5 Epiblast", "E7.5 Ectoderm")
)
```

Load genome-wide global methylation and accessibility rates
```{r}
met.stats <- fread(io$met.stats) %>% .[,c("id_met","mean")] %>% .[,context:="CG"] 
acc.stats <- fread(io$acc.stats) %>% .[,c("id_acc","mean")] %>% .[,context:="GC"]
```

DNA methylation
```{r}
foo.met <- met_dt %>%
  .[,.(rate=100*(sum(Nmet)/sum(Ntotal))),by=c("id_met","stage_lineage","anno")] %>%
  .[,stage_lineage:=factor(stage_lineage, levels=names(colors))] %>%
    merge(met.stats, by="id_met") %>%
  .[,norm_rate:=rate/mean] 

p <- ggboxplot(foo.met, x = "stage_lineage", y = "norm_rate", fill="grey80", outlier.shape=NA) +
  scale_fill_manual(values=colors) +
  geom_hline(yintercept=1, linetype="dashed", alpha=0.75, size=0.75) +
  labs(x="", y="Methylation (scaled)") +
  facet_wrap(~anno, nrow=1, scales="fixed") +
  stat_compare_means(comparisons = my_comparisons, aes(label = ..p.signif..), method="wilcox.test") +
  # coord_cartesian(ylim=c(0.1,1.15)) +
  theme(
    strip.background = element_rect(fill="#F37A71"),
    # axis.text.x = element_text(size=rel(0.9), color="black"),
    axis.text.x = element_blank(),
    axis.title.y = element_text(size=rel(1.4), color="black"),
    strip.text = element_text(size=rel(1.3), color="black"),
    legend.position = "none"
  )

pdf(paste0(io$outdir,"/boxplots_met_top250_scaled.pdf"), width=opts$width, height=opts$height)
print(p)
dev.off()
```

Chromatin accessibility
```{r}
foo.acc <- acc_dt %>%
  .[,.(rate=100*(sum(Nmet)/sum(Ntotal))),by=c("id_acc","stage_lineage","anno")] %>%
  .[,stage_lineage:=factor(stage_lineage, levels=names(colors))] %>%
    merge(acc.stats, by="id_acc") %>%
  .[,norm_rate:=rate/mean] 

p <- ggboxplot(foo.acc, x = "stage_lineage", y = "norm_rate", fill="grey80", coef=0.5, outlier.shape=NA) +
  scale_fill_manual(values=colors) +
  geom_hline(yintercept=1, linetype="dashed", alpha=0.75, size=0.75) +
  labs(x="", y="Accessibility (scaled)") +
  facet_wrap(~anno, nrow=1, scales="fixed") +
  stat_compare_means(comparisons = my_comparisons, aes(label = ..p.signif..), method="wilcox.test") +
  # coord_cartesian(ylim=c(0.85,1.75)) +
  theme(
    strip.background = element_rect(fill="#00BFC4"),
    # axis.text.x = element_text(size=rel(0.9), color="black"),
    axis.text.x = element_blank(),
    axis.title.y = element_text(size=rel(1.4), color="black"),
    strip.text = element_text(size=rel(1.3), color="black"),
    legend.position = "none"
  )

# pdf(paste0(io$outdir,"/boxplots_acc_top250_scaled.pdf"), width=opts$width, height=opts$height)
pdf(paste0(io$outdir,"/foo.pdf"), width=opts$width, height=opts$height)
print(p)
dev.off()
```

