
```{r}
io$pdfdir2 <- paste0(io$pdfdir,"/characterisation_factors/CellCycle_factor")
io$cellcycle.assignments <- "/Users/ricard/data/gastrulation_norsync_stuff/rna/cell_cycle/cell_cycle_scran.txt.gz"

opts$factors.width <- 4.5
opts$factors.height <- 4

factor <- 6
```

<!-- Load cell cycle assignments from cyclone -->
```{r}
cellcycle.assignments <- fread(io$cellcycle.assignments) %>%
  .[,c("id_rna","phase","phase2")] %>%
  merge(sample_metadata[,c("sample","id_rna")]) 
```

Subset cells that are present in the model
```{r}
cells <- as.character(unname(unlist(samples(model))))
cellcycle.assignments.filt <- cellcycle.assignments %>%
  .[sample%in%cells] %>% setkey(sample) %>% .[cells]
```

Subset cells with a cell cycle assignment
```{r}
cells <- cellcycle.assignments[phase2%in%c("G1S","G2M"),sample]

model.cellcycle <- subset_samples(model,cells)

cellcycle.assignments.filt <- cellcycle.assignments %>% 
  .[sample%in%unlist(samples(model.cellcycle))] %>% setkey(sample) %>% .[unlist(samples(model.cellcycle))]
```

```{r}
all(cellcycle.assignments.filt$sample == unlist(samples(model.cellcycle)))
```

<!-- Plot factor values colored by cell type assignment -->
```{r}
p <- plot_factor(
  model.cellcycle,
  factor = factor,
  color_by = cellcycle.assignments.filt$phase2, scale = T,
  add_violin = T, color_violin = T, 
  dodge=T, dot_size=1, legend = F, rasterize = F
)
p <- p + scale_color_brewer(palette = "Dark2") + scale_fill_brewer(palette = "Dark2")
p <- p + theme(
  strip.text = element_text(size=rel(1.1), color="black"),
  strip.background = element_blank(),
)

pdf(paste0(io$pdfdir2,"/Factor_values_violin.pdf"), width=5, height=4, useDingbats = F)
print(p)
dev.off()
```

<!-- Plot RNA expression values for top genes  -->

Top gene with negative loadings
```{r}
top.gene <- names(head(sort(get_weights(model, views="RNA", factor=factor)[[1]][,1]), n=1))

p <- plot_factor(model,
  factor = factor,
  color_by = top.gene,
  legend = FALSE,
  dot_size = 1
) + scale_colour_gradientn(colours = terrain.colors(10)) +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks.x = element_blank(),
    strip.text = element_blank()
  )

print(p)
  
# pdf(paste0(io$pdfdir2,"/Factor_rna_bottom.pdf"), width=opts$factors.width/1.5, height=opts$factors.height/2, useDingbats = F)
# print(p)
# dev.off()
```


<!-- Plot weights -->

RNA
```{r}
p <- plot_weights(
  model,
  view = "RNA",
  factor = factor,
  nfeatures = 25,
  scale = T
)

pdf(paste0(io$pdfdir2,"/loadings_RNA.pdf"), width=8, height=5, useDingbats = F)
print(p)
dev.off()
```


