
```{r}
io$pdfdir2 <- paste0(io$pdfdir,"/characterisation_factors/Mesoderm_factor")
opts$width <- 4.5
opts$height <- 4

factor <- 2
```

<!-- Plot variance explained -->
```{r}
p <- plot_variance_explained(model, x="group", y="view", factors=factor, legend = T, max_r2 = 0.13)

# p <- p + theme(axis.text.x = element_text(size=rel(1.0), angle=40, hjust=1))

pdf(paste0(io$pdfdir2,"/r2.pdf"), width=6.5, height=3.5)
print(p)
dev.off()
```

```{r}
p <- plot_factor(
  model,
  factor = 2,
  # color_by = "lineage10x_2", scale = T,
  color_by = "lineage10x_2", scale = T,
  add_violin = T, color_violin = T, 
  dodge=T, dot_size=1, legend = F, rasterize = F
)
p <- p + scale_color_manual(values=opts$colors) + scale_fill_manual(values=opts$colors)
p <- p + theme(
  strip.text = element_text(size=rel(1.1), color="black"),
  strip.background = element_blank(),
)

pdf(paste0(io$pdfdir2,"/Factor_values_violin.pdf"), width=2.8, height=3, useDingbats = F)
print(p)
dev.off()
```

```{r}
# plot_factor(model, #groups = c("E7.5"),
#   factor = 3,
#   color_by = "lineage10x_2", scale = T,
#   add_violin = T, color_violin = T, 
#   dodge=T, dot_size=1.5, legend = T
# ) + scale_color_manual(values=opts$colors) + scale_fill_manual(values=opts$colors)
```



<!-- Plot RNA expression values for top genes  -->

```{r}
# genes <- names(head(sort(get_weights(model, views="RNA expression", factor=factor)[[1]][,1]), n=1))
genes <- names(tail(sort(get_weights(model, views="RNA expression", factor=factor)[[1]][,1]), n=2))

for (i in genes) {
  p <- plot_factor(model,
    factor = factor,
    color_by = i,
    legend = FALSE,
    # dot_size = dot_size,
  ) + scale_colour_gradientn(colours = terrain.colors(10)) +
    theme(
      axis.text = element_blank(),
      axis.title = element_blank(),
      axis.ticks.x = element_blank(),
      strip.text = element_blank()
    )
  
  # pdf(sprintf("%s/Factor_rna_%s.pdf",io$pdfdir2,i), width=opts$width/1.5, height=opts$height/2, useDingbats = F)
  print(p)
  # dev.off()
}
```


<!-- Plot DNA methylation values for top enhancers (only scNMT-seq cells) -->

```{r}
# view <- "Enhancer methylation"
# nfeatures <- 100
# dot_size <- 0.75
```

Features with largest negative loadings
```{r}
# top.features <- names(tail(sort(get_weights(model.scnmt, views=view, factor=factor)[[1]][,1]), n=nfeatures))
# 
# # Calculate a DNA methylation rate per cell by averaging across the top N features
# met <- unlist(lapply(model.scnmt@data[[view]], function(x) colMeans(x[top.features,], na.rm=T)))
# met <- 100*2**met/(1+2**met) # Convert M-values to B-values
# 
# p <- plot_factor(
#   object = model.scnmt,
#   factor = factor, 
#   color_by = met, 
#   show_missing = FALSE,
#   legend = FALSE,
#   dot_size = dot_size
# )
# p <- p + scale_color_distiller(palette = "YlOrRd", direction=1) +
#   theme(
#     axis.text = element_blank(),
#     axis.title = element_blank(),
#     axis.ticks.x = element_blank(),
#     strip.text = element_blank()
#   )
# 
# pdf(paste0(io$pdfdir2,"/Factor_met_bottom.pdf"), width=opts$width/1.5, height=opts$height/2, useDingbats = F)
# print(p)
# dev.off()
```

Features with largest positive loadings
```{r}
# top.features <- names(head(sort(get_weights(model.scnmt, views=view, factor=factor)[[1]][,1]), n=nfeatures))
# 
# # Calculate a DNA methylation rate per cell by averaging across the top N features
# met <- unlist(lapply(model.scnmt@data[[view]], function(x) colMeans(x[top.features,], na.rm=T)))
# met <- 100*2**met/(1+2**met) # Convert M-values to B-values
# 
# p <- plot_factor(
#   object = model.scnmt,
#   factor = factor, 
#   color_by = met, 
#   show_missing = FALSE,
#   legend = FALSE,
#   dot_size = dot_size
# )
# p <- p + scale_color_distiller(palette = "YlOrRd", direction=1) +
#   theme(
#     axis.text = element_blank(),
#     axis.title = element_blank(),
#     axis.ticks.x = element_blank(),
#     strip.text = element_blank()
#   )
# 
# pdf(paste0(io$pdfdir2,"/Factor_met_top.pdf"), width=opts$width/1.5, height=opts$height/2, useDingbats = F)
# print(p)
# dev.off()
```



<!-- Plot chromatin accessibility values for top enhancers (only scNMT-seq cells) -->

```{r}
# view <- "Enhancer accessibility"
# 
# min_acc <- 20
# max_acc <- 80
# 
# nfeatures <- 100
# dot_size <- 0.75
```

Features with largest negative loadings
```{r}
# top.features <- names(tail(sort(get_weights(model.scnmt, views=view, factor=factor)[[1]][,1]), n=nfeatures))
# 
# # Calculate a DNA methylation rate per cell by averaging across the top N features
# acc <- unlist(lapply(model.scnmt@data[[view]], function(x) colMeans(x[top.features,], na.rm=T)))
# acc <- 100*2**acc/(1+2**acc) # Convert M-values to B-values
# acc[acc<(min_acc)] <- min_acc
# acc[acc>(max_acc)] <- max_acc
# 
# p <- plot_factor(
#   object = model.scnmt,
#   factor = factor, 
#   color_by = acc, 
#   show_missing = FALSE,
#   legend = FALSE,
#   dot_size = dot_size
# )
# p <- p + scale_color_distiller(palette = "Blues", direction=1) +
#   theme(
#     axis.text = element_blank(),
#     axis.title = element_blank(),
#     axis.ticks.x = element_blank(),
#     strip.text = element_blank()
#   )
# 
# pdf(paste0(io$pdfdir2,"/Factor_acc_bottom.pdf"), width=opts$width/1.5, height=opts$height/2, useDingbats = F)
# print(p)
# dev.off()
```

Features with largest positive loadings
```{r}
# top.features <- names(head(sort(get_weights(model.scnmt, views=view, factor=factor)[[1]][,1]), n=nfeatures))
# 
# # Calculate a DNA methylation rate per cell by averaging across the top N features
# acc <- unlist(lapply(model.scnmt@data[[view]], function(x) colMeans(x[top.features,], na.rm=T)))
# acc <- 100*2**acc/(1+2**acc) # Convert M-values to B-values
# acc[acc<(min_acc)] <- min_acc
# acc[acc>(max_acc)] <- max_acc
# 
# p <- plot_factor(
#   object = model.scnmt,
#   factor = factor, 
#   color_by = acc, 
#   show_missing = FALSE,
#   legend = FALSE,
#   dot_size = dot_size
# )
# p <- p + scale_color_distiller(palette = "Blues", direction=1) +
#   theme(
#     axis.text = element_blank(),
#     axis.title = element_blank(),
#     axis.ticks.x = element_blank(),
#     strip.text = element_blank()
#   )
# 
# pdf(paste0(io$pdfdir2,"/Factor_acc_top.pdf"), width=opts$width/1.5, height=opts$height/2, useDingbats = F)
# print(p)
# dev.off()
```



<!-- Plot weights -->

RNA
```{r}
p <- plot_weights(
  model,
  view="RNA expression",
  factor = factor,
  nfeatures = 8,
  scale = T
)

pdf(paste0(io$pdfdir2,"/Factor_loadings_RNA.pdf"), width=4, height=4.5, useDingbats = F)
print(p)
dev.off()
```



DNA methylation: joint plot of promoters and enhancers

```{r}
loadings.dt <- get_weights(
  model, 
  views = grep("methylation",views(model)),
  factors = factor, 
  as.data.frame = T
) %>% as.data.table

loadings.dt[,value:=value/max(abs(value))] %>%
  setorder(value) %>% .[,feature:=factor(feature,levels=feature)]
```

```{r}
p <- ggplot(loadings.dt, aes(x = value)) +
  geom_density(aes(y=..scaled..), alpha=0.85, fill="#e34a33") + 
  facet_wrap(~view, scales = "fixed", nrow=2) +
  # coord_cartesian(xlim=c(-0.21,0.21), ylim=c(0,20)) +
  scale_x_continuous(breaks = c(-1,0,1), limits = c(-1,1)) +
  scale_y_continuous(breaks = c(0,0.5,1)) +
  # scale_fill_manual(values=c("#d73027","#fdae61")) +
  # scale_fill_brewer(palette = "YlOrRd", direction=1) +
  labs(x="Loading", y="Density") +
  geom_vline(xintercept=0, linetype="dashed") +
  theme_classic() +
  theme(
      axis.text = element_text(size=rel(1.1), color="black"),
      axis.title = element_text(size=rel(1.3), color="black"),
      strip.background = element_blank(),
      strip.text = element_text(size=rel(1.3), color="black"),
  )
p

pdf(paste0(io$pdfdir2,"/Factor_loadings_met_joint.pdf"), width=4, height=5.1, useDingbats = F)
print(p)
dev.off()
```





Chromatin accessibility: joint plot of promoters and enhancers

```{r}
loadings.dt <- get_weights(
  model, 
  views = grep("accessibility",views(model)),
  factors = factor, 
  as.data.frame = T
) %>% as.data.table

loadings.dt[,value:=value/max(abs(value))] %>%
  setorder(value) %>% .[,feature:=factor(feature,levels=feature)]
```

```{r}
p <- ggplot(loadings.dt, aes(x = value)) +
  geom_density(aes(y=..scaled..), alpha=0.85, fill="#2b8cbe") + 
  facet_wrap(~view, scales = "fixed", nrow=2) +
  # coord_cartesian(xlim=c(-0.35,0.35), ylim=c(0,17)) +
  scale_x_continuous(breaks = c(-1,0,1), limits = c(-1,1)) +
  scale_y_continuous(breaks = c(0,0.5,1)) +
  # scale_fill_manual(values=c("#4575b4","#e0f3f8")) +
  # scale_fill_brewer(palette = "GnBu", direction=1) +
  labs(x="Loading", y="Density") +
  geom_vline(xintercept=0, linetype="dashed") +
  theme_classic() +
  theme(
      axis.text = element_text(size=rel(1.1), color="black"),
      axis.title = element_text(size=rel(1.3), color="black"),
      strip.background = element_blank(),
      strip.text = element_text(size=rel(1.3), color="black"),
  )
# p

pdf(paste0(io$pdfdir2,"/Factor_loadings_acc_joint.pdf"), width=4, height=5.1, useDingbats = F)
print(p)
dev.off()
```




