
```{r}
io$pdfdir2 <- paste0(io$pdfdir,"/CellCycle_factor")

opts$width <- 4.5
opts$height <- 4

factor <- 9
```

<!-- Plot factor values colored by cell type assignment -->
```{r}
p <- plot_factor(
  model,
  factor = factor,
  # color_by = "Sox11",
  color_by = "lineage10x_2",
  dodge=T, dot_size=1, legend = F, rasterize = F
)
p <- p + scale_color_manual(values=opts$colors) + scale_fill_manual(values=opts$colors)
p <- p + theme(
  strip.text = element_text(size=rel(1.1), color="black"),
  strip.background = element_blank(),
)

# pdf(paste0(io$pdfdir2,"/Factor_values.pdf"), width=opts$width, height=opts$height, useDingbats = F)
print(p)
# dev.off()
```

<!-- Plot RNA expression values for top genes  -->

Top gene with negative loadings
```{r}
top.gene <- names(head(sort(get_weights(model, views="RNA", factor=factor)[[1]][,1]), n=1))

p <- plot_factor(model,
  factor = factor,
  color_by = top.gene,
  legend = FALSE,
  dot_size = 1
) + scale_colour_gradientn(colours = terrain.colors(10)) +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks.x = element_blank(),
    strip.text = element_blank()
  )

print(p)
  
# pdf(paste0(io$pdfdir2,"/Factor_rna_bottom.pdf"), width=opts$width/1.5, height=opts$height/2, useDingbats = F)
# print(p)
# dev.off()
```


<!-- Plot weights -->

RNA
```{r}
p <- plot_weights(
  model,
  view = "RNA",
  factor = 1,
  nfeatures = 25,
  scale = T
)

# pdf(paste0(io$pdfdir2,"/loadings_RNA.pdf"), width=8, height=5, useDingbats = F)
print(p)
# dev.off()
```

<!-- Gene set enrichment analysis -->

Load MsigDb gene set
```{r go_enrichment, echo=FALSE}
io$msigFile <- "/Users/ricard/data/MSigDB/v6.0/mus_musculus/C5/bp_binary_matrix_ensembl.rds"
# io$msigFile <- "/Users/ricard/data/MSigDB/v6.0/mus_musculus/C2/binary_matrix_ensembl.rds"

feature.sets <- readRDS(io$msigFile)
```

Capitalise gene names
```{r}
features_names(model)[["RNA"]] <- toupper(features_names(model)[["RNA"]])
```

Do gene set enrichment analysis
```{r}
enrichment.out <- run_enrichment(model,
  view = "RNA",
  feature.sets = feature.sets,
  statistical.test = "parametric",
  alpha = 0.01
)
```

Plot
```{r}
# factor=6
# alpha = 0.1
# max.pathways = 25
# adjust = TRUE
# text_size = 1.0
# dot_size = 5.0
plotEnrichment(model, factor=9, enrichment.results = enrichment.out, max.pathways = 15)
```

