---
title: "Gastrulation scNMT-seq: plot distributions of DNA methylation"
output:
  BiocStyle::html_document: 
    toc: false
    fig_width: 10
    fig_height: 8
---

```{r load_modules, echo=FALSE, include=FALSE}
library(data.table)
library(purrr)
library(ggplot2)
library(ggpubr)
```

```{r define_opts, echo=FALSE}

## Define I/O ##
io <- list()
io$sample.metadata <- "/Users/ricard/data/gastrulation/sample_metadata.txt"
io$data <- "/Users/ricard/data/gastrulation/met/feature_level"
io$outdir <- "/Users/ricard/data/gastrulation/met/distributions"

## Define options ##
opts <- list()

# Define which stage and lineages to use (use NULL for all)
opts$stage_lineage <- c(
  
  # E4.5
  "E4.5_Epiblast",
  
  # E5.5
  "E5.5_Epiblast",
  
  # E6.5
  "E6.5_Epiblast",
  "E6.5_Primitive_Streak",
  
  # E7.5
  "E7.5_Epiblast",
  "E7.5_Primitive_Streak",
  "E7.5_Endoderm",
  "E7.5_Mesoderm",
  "E7.5_Ectoderm"
)
# opts$stage_lineage <- NULL

# Define which annotations to use
opts$annos <- c(
  "prom_2000_2000"="Promoters",
  "H3K27ac_distal_E7.5_Mes_intersect12"="Mesoderm enhancers",
  "H3K27ac_distal_E7.5_Ect_intersect12"="Ectoderm enhancers",
  "H3K27ac_distal_E7.5_End_intersect12"="Endoderm enhancers"
)

# Define which cells to use
tmp <- fread(io$sample.metadata) %>% .[!is.na(id_met)] 
if (is.null(opts$stage_lineage)) {
  opts$cells <- tmp[,id_met]
} else {
  opts$cells <- tmp %>%
    .[,stage_lineage:=paste(stage,lineage10x_2,sep="_")] %>%
    .[pass_metQC==T & stage_lineage%in%opts$stage_lineage,id_met]
}
```

<!-- Load sample metadata -->
```{r}
sample_metadata <- fread(io$sample.metadata) %>% 
  .[,c("id_met","stage","lineage10x_2","plate")] %>%
  .[id_met%in%opts$cells] %>%
  .[,stage_lineage:=as.factor(paste(stage,lineage10x_2,sep="_"))]
```

<!-- Load DNA methylation data  -->
```{r}
data <- lapply(names(opts$annos), function(n)
  fread(sprintf("%s/%s.tsv.gz",io$data,n), showProgress=F) %>%
  setnames(c("id_met","id","anno","Nmet","Ntotal","rate"))
) %>% rbindlist
```

<!-- Parse data -->
```{r}
# Merge methylation data and sample metadata
data <- data %>% merge(sample_metadata, by="id_met")

# Convert beta value to M value
# data[,m:=log2(((rate/100)+0.01)/(1-(rate/100)+0.01))]
```

```{r}
data %>% .[,anno:=stringr::str_replace_all(anno,opts$annos)]
```

<!-- Plot histogram in pseudobulk stages -->
```{r}
data.pseudobulk <- data %>% 
  # .[,.(rate=100*(sum(Nmet)/sum(Ntotal))),by=c("id_met","stage","id","anno")]
  .[,.(rate=100*(sum(Nmet)/sum(Ntotal))),by=c("stage","id","anno")]
  
p <- gghistogram(data.pseudobulk, x = "rate", y="..density..", fill = "#F37A71", color = "black", alpha=0.75) +
  facet_wrap(~stage+anno, nrow=4, scales="fixed") +
  theme(
    axis.text.y = element_text(size=rel(0.9))
    )

pdf(sprintf("%s/distributions_met.pdf",io$outdir), width=9, height=8)
print(p)
dev.off()
```

<!-- Plot histogram for every cell -->
```{r}
for (i in head(unique(data$id_met),n=10)) {
  p <- gghistogram(data[id_met==i], x = "rate", y="..density..", fill = "#F37A71", color = "black", alpha=0.75) +
    facet_wrap(~stage+anno, nrow=1, scales="fixed") +
    theme(
      axis.text.y = element_text(size=rel(0.9))
    )
  
  pdf(sprintf("%s/distributions_met_%s.pdf",io$outdir,i), width=9, height=8)
  print(p)
  dev.off()
}
```