---
title: "Gastrulation scNMT-seq: plot distributions of DNA methylation"
output:
  BiocStyle::html_document: 
    toc: false
    fig_width: 10
    fig_height: 8
---

```{r load_modules, echo=FALSE, include=FALSE}
library(data.table)
library(purrr)
library(ggplot2)
library(ggpubr)
```

```{r define_opts, echo=FALSE}

## Define I/O ##
io <- list()
io$sample.metadata <- "/Users/ricard/data/gastrulation/sample_metadata.txt"
io$data <- "/Users/ricard/data/gastrulation/met/feature_level"
# io$outdir <- "/Users/ricard/data/gastrulation/met/results/distributions"
io$outdir <- "/Users/ricard"

## Define options ##
opts <- list()

# Define which stage and lineages to use (use NULL for all)
# opts$stage_lineage <- c(
#   
#   # E4.5
#   "E4.5_Epiblast",
#   
#   # E5.5
#   "E5.5_Epiblast",
#   
#   # E6.5
#   "E6.5_Epiblast",
#   "E6.5_Primitive_Streak",
#   
#   # E7.5
#   "E7.5_Epiblast",
#   "E7.5_Primitive_Streak",
#   "E7.5_Endoderm",
#   "E7.5_Mesoderm",
#   "E7.5_Ectoderm"
# )
opts$stage_lineage <- NULL

# Define which annotations to use
opts$annos <- c(
  "prom_2000_2000"="Promoters"
  # "H3K27ac_distal_E7.5_Mes_intersect12"="Mesoderm enhancers",
  # "H3K27ac_distal_E7.5_Ect_intersect12"="Ectoderm enhancers",
  # "H3K27ac_distal_E7.5_End_intersect12"="Endoderm enhancers"
)

# Define which cells to use
tmp <- fread(io$sample.metadata) %>% .[!is.na(id_met)] 
if (is.null(opts$stage_lineage)) {
  opts$cells <- tmp[,id_met]
} else {
  opts$cells <- tmp %>%
    .[,stage_lineage:=paste(stage,lineage10x_2,sep="_")] %>%
    .[pass_metQC==T & stage_lineage%in%opts$stage_lineage,id_met]
}
```

<!-- Load sample metadata -->
```{r}
sample_metadata <- fread(io$sample.metadata) %>% 
  .[,c("id_met","stage","lineage10x_2")] %>%
  .[id_met%in%opts$cells] %>%
  .[,stage_lineage:=paste(stage,lineage10x_2,sep="_")]
```

<!-- Load DNA methylation data  -->
```{r}
data <- lapply(names(opts$annos), function(n)
  fread(sprintf("%s/%s.tsv.gz",io$data,n), showProgress=F) %>%
  setnames(c("id_met","id","anno","Nmet","Ntotal","rate"))
) %>% rbindlist
```

<!-- Parse data -->
```{r}
# Merge methylation data and sample metadata
data <- data %>% merge(sample_metadata, by="id_met")

# Convert beta value to M value
# data[,m:=log2(((rate/100)+0.01)/(1-(rate/100)+0.01))]
```

```{r}
data %>% .[,anno:=stringr::str_replace_all(anno,opts$annos)]
```


<!-- Plot histogram of the number of total reads per feature and cell -->

Note: this assumes just one annotation!
```{r }
stopifnot(length(unique(data$anno))==1)

subset.cells <- head(unique(data$id_met),n=6)

to.plot <- data[id_met%in%subset.cells,c("id_met","id","Ntotal")] %>% 
  .[,.(N=.N),by=c("Ntotal","id_met")] %>%
  .[Ntotal<=50] %>%
  .[,Ntotal:=as.factor(Ntotal)] 

p1 <- ggbarplot(to.plot, x = "Ntotal", y="N", size = 0.3,
                 fill = "gray70", color = "black", alpha=0.75) +
  facet_wrap(~id_met, nrow=2, scales="free_y") +
  scale_y_continuous(labels = function(x) format(x, scientific = TRUE)) +
  scale_x_discrete(breaks=seq(0,50,5)) +
  labs(x="Number of reads", y="Number of CpG sites") +
  theme(
    axis.text.x = element_text(size=rel(0.6)),
    # axis.text.x = element_text(size=rel(0.5), angle=90, hjust=1, vjust=0.5, color="black"),
    axis.text.y = element_text(size=rel(0.7)),
    axis.ticks.x = element_line(size=rel(0.5)),
    axis.ticks.length.x = unit(.05, "cm")
    )

# pdf(sprintf("%s/distributions_ntotal_per_cell_v2.pdf",io$outdir), width=9, height=8)
print(p1)
# dev.off()
```

<!-- Plot histogram of the number of total reads per feature after pseudobulking -->
```{r}
to.plot <- data %>% 
  .[,.(Ntotal=sum(Ntotal)),by=c("id","anno")] %>%
  .[,.(N=.N),by=c("Ntotal")] %>%
  .[Ntotal<=500] #%>%
  # .[,Ntotal:=as.factor(Ntotal)] 
  
p2 <- ggbarplot(to.plot, x = "Ntotal", y="N", size = 0.15,
                 fill = "gray70", color = "black", alpha=0.75) +
  scale_y_continuous(labels = function(x) format(x, scientific = TRUE)) +
  scale_x_continuous(breaks=seq(0,500,25)) +
  labs(x="Number of reads", y="Number of CpG sites") +
  theme(
    axis.text.x = element_text(size=rel(0.6)),
    # axis.text.x = element_text(size=rel(0.5), angle=90, hjust=1, vjust=0.5, color="black"),
    axis.text.y = element_text(size=rel(0.7)),
    axis.ticks.x = element_line(size=rel(0.5)),
    axis.ticks.length.x = unit(.05, "cm")
    )

# pdf(sprintf("%s/distributions_ntotal_pseudobulk_v2.pdf",io$outdir), width=9, height=8)
print(p2)
# dev.off()
```

```{r}
p <- cowplot::plot_grid(plotlist=list(p1,p2), nrow=1, rel_widths = c(1/2,1/2))

pdf(sprintf("%s/distributions_ntotal_v2.pdf",io$outdir), width=13, height=7)
print(p)
dev.off()
```



<!-- Plot histogram of DNA methylation rate in pseudobulk stages -->
```{r}
data.pseudobulk <- data %>% 
  # .[,.(rate=100*(sum(Nmet)/sum(Ntotal))),by=c("id_met","stage","id","anno")]
  .[,.(rate=100*(sum(Nmet)/sum(Ntotal))),by=c("stage","id","anno")]
  
p <- gghistogram(data.pseudobulk, x = "rate", y="..density..", fill = "#F37A71", color = "black", alpha=0.75) +
  facet_wrap(~stage+anno, nrow=4, scales="fixed") +
  theme(
    axis.text.y = element_text(size=rel(0.9))
    )

# pdf(sprintf("%s/distributions_met.pdf",io$outdir), width=9, height=8)
# print(p)
# dev.off()
```

<!-- Plot histogram of DNA methylation rate for every cell -->
```{r}
for (i in head(unique(data$id_met),n=10)) {
  p <- gghistogram(data[id_met==i], x = "rate", y="..density..", fill = "#F37A71", color = "black", alpha=0.75) +
    facet_wrap(~stage+anno, nrow=1, scales="fixed") +
    theme(
      axis.text.y = element_text(size=rel(0.9))
    )
  
  # pdf(sprintf("%s/distributions_met_%s.pdf",io$outdir,i), width=9, height=8)
  # print(p)
  # dev.off()
}
```