---
title: "Gastrulation scNMT-seq: plot distributions of DNA methylation at the CpG level"
output:
  BiocStyle::html_document: 
    toc: false
    fig_width: 10
    fig_height: 8
---

```{r load_modules, echo=FALSE, include=FALSE}
library(data.table)
library(purrr)
library(ggplot2)
library(ggpubr)
```

```{r define_opts, echo=FALSE}

## Define I/O ##
io <- list()
io$basedir <- "/Users/ricard/data/gastrulation"
io$metadata <- paste0(io$basedir,"/sample_metadata.txt")
io$data <- paste0(io$basedir,"/met/cpg_level")
# io$outdir <- paste0(io$basedir,"/met/distributions")
io$outdir <- "/Users/ricard"

## Define options ##
opts <- list()

# Define which stage and lineages to use (use NULL for all)
# opts$stage_lineage <- c(
#   
#   # E4.5
#   "E4.5_Epiblast",
#   
#   # E5.5
#   "E5.5_Epiblast",
#   
#   # E6.5
#   "E6.5_Epiblast",
#   "E6.5_Primitive_Streak",
#   
#   # E7.5
#   "E7.5_Epiblast",
#   "E7.5_Primitive_Streak",
#   "E7.5_Endoderm",
#   "E7.5_Mesoderm",
#   "E7.5_Ectoderm"
# )
opts$stage_lineage <- NULL

# Define which cells to use
tmp <- fread(io$metadata) %>% .[!is.na(id_met)] 
if (is.null(opts$stage_lineage)) {
  opts$cells <- tmp[,id_met]
} else {
  opts$cells <- tmp %>%
    .[,stage_lineage:=paste(stage,lineage10x_2,sep="_")] %>%
    .[pass_metQC==T & stage_lineage%in%opts$stage_lineage,id_met]
}
rm(tmp)
```

```{r }
opts$cells <- head(opts$cells,n=100)
```

<!-- Load sample metadata -->
```{r}
sample_metadata <- fread(io$metadata) %>% 
  .[,c("id_met","stage","lineage10x_2","plate")] %>%
  .[id_met%in%opts$cells] %>%
  .[,stage_lineage:=paste(stage,lineage10x_2,sep="_")]
```

<!-- Load DNA methylation data  -->
```{r}
data <- lapply(1:length(opts$cells), function(i)
  fread(sprintf("%s/%s.tsv.gz",io$data,opts$cells[[i]]), showProgress=F) %>% 
    .[,c("cell","chr"):=list(factor(paste0("cell_",i)),factor(chr))]
) %>% rbindlist
```

<!-- Parse data -->
```{r}
# Merge methylation data and sample metadata
# data <- data %>% merge(sample_metadata, by="id_met")

data[,total_reads:=met_reads+nonmet_reads]
```

<!-- Plot histogram of the number of total reads per CpG site per cell -->
```{r }
subset.cells <- head(unique(data$cell),n=6)

to.plot <- data[cell%in%subset.cells] %>% 
  .[total_reads>10,total_reads:=10] %>%
  .[,.(N=.N),by=c("total_reads","cell")] %>%
  .[,total_reads:=as.factor(total_reads)] 

p1 <- ggbarplot(to.plot, x = "total_reads", y="N",
                 fill = "#F37A71", color = "black", alpha=0.75) +
  facet_wrap(~cell, nrow=2, scales="free_y") +
  scale_y_continuous(labels = function(x) format(x, scientific = TRUE)) +
  labs(x="Number of reads", y="Number of CpG sites") +
  theme(
    axis.text.x = element_text(size=rel(0.8)),
    axis.text.y = element_text(size=rel(0.8))
    )

# pdf(sprintf("%s/distributions_ntotal_per_cell.pdf",io$outdir), width=9, height=8)
# print(p)
# dev.off()
```

<!-- Plot histogram of the number of total reads per CpG site after pseudobulking -->
```{r}
to.plot <- data %>% 
  .[,.(total_reads=sum(total_reads)),by=c("chr","pos")] %>%
  # .[total_reads>50,total_reads:=50] %>%
  .[,.(N=.N),by=c("total_reads")] %>%
  .[,total_reads:=as.factor(total_reads)] 
  
p2 <- ggbarplot(to.plot, x = "total_reads", y="N",
                 fill = "#F37A71", color = "black", alpha=0.75) +
  scale_y_continuous(labels = function(x) format(x, scientific = TRUE)) +
  coord_cartesian(xlim=c(0,30)) +
  labs(x="Number of reads", y="Number of CpG sites") +
  theme(
    axis.text.x = element_text(size=rel(0.7)),
    axis.text.y = element_text(size=rel(0.8))
    )
# print(p2)

# pdf(sprintf("%s/distributions_ntotal_pseudobulk.pdf",io$outdir), width=9, height=8)
# print(p)
# dev.off()
```

```{r}
p <- cowplot::plot_grid(plotlist=list(p1,p2), nrow=1, rel_widths = c(1/2,1/2))

pdf(sprintf("%s/distributions_ntotal.pdf",io$outdir), width=13, height=7)
print(p)
dev.off()
```

