samples:
    - E3.5_sample_1
    - E3.5_sample_2
    - E4.5_sample_1
    - E4.5_sample_2
    - E5.5_sample_1
    - E5.5_sample_2
    - E6.5_sample_1
    - E6.5_sample_2
    - E6.5_sample_3
    - E6.5_sample_4
    - E6.5_sample_5
    - E6.5_sample_6
    - E6.5_sample_7
    - E6.5_sample_8
    - E6.5_sample_9
    - E6.5_sample_10
    - E6.5_sample_11
    - E6.5_sample_12
    - E7.5_sample_1
    - E7.5_sample_2
    - E7.5_sample_3
    - E7.5_sample_4
    - E7.5_sample_5
    - E7.5_sample_7
    - E7.5_sample_6
    - E7.5_sample_8
    - E7.5_sample_9
    - E7.5_sample_10
    - E7.5_sample_11
    - E7.5_sample_12
    - E7.5_sample_13
    - E7.5_sample_14
    - E7.5_sample_15
    - TET_experiment_E8.5_WT_CD41+
    - TET_experiment_E8.5_WT_KDR+
    - TET_experiment_E8.5_WT_KDR+_CD41+
    - TET_experiment_E8.5_WT
    - TET_experiment_E7.5_WT

plates:
    - E3.5_Plate1
    - E3.5_Plate2
    - E4.5-5.5_new_Plate1
    - E4.5-5.5_new_Plate2
    - E4.5-5.5_new_Plate3
    - E4.5-5.5_new_Plate4
    - E6.5_Plate1
    - E6.5_Plate2
    - E6.5_Plate3
    - E6.5_late_Plate1
    - E6.5_late_Plate2
    - E7.5_Plate1
    - E7.5_Plate2
    - E7.5_Plate3
    - E7.5_Plate4
    - PS_VE_Plate1
    - PS_VE_Plate10
    - PS_VE_Plate11
    - PS_VE_Plate12
    - PS_VE_Plate2
    - PS_VE_Plate3
    - PS_VE_Plate4
    - PS_VE_Plate5
    - PS_VE_Plate6
    - PS_VE_Plate7
    - PS_VE_Plate8
    - PS_VE_Plate9
    - Plate11
    - Plate12
    - Plate13
    - Plate14
    - Plate15
    - Plate16
    - E8.5_oct20_plate1
    - E8.5_oct20_plate3
    - E8.5_oct20_plate5
    - E8.5_oct20_plate7
    - Tet-tko-chimera_embryo04
    - Tet-tko-chimera_embryo05
    - tet_chimera_march20_plate1
    - tet_chimera_march20_plate2
    - tet_chimera_march20_plate4_wt
    - tet_chimera_march20_plate5_wt
    - tet_chimera_march20_plate6_wt

    
stages: ["E3.5","E4.5","E5.5","E6.5","E7.5","E8.5"]

#################
## Directories ##
#################

directories:
    base: /bi/group/reik/ricard/data/scnmt_gastrulation_argelaguet2019
    original_data: /bi/group/reik/ricard/data/scnmt_gastrulation_argelaguet2019/original
    processed_data: /bi/group/reik/ricard/data/scnmt_gastrulation_argelaguet2019/processed/rna
    results: /bi/group/reik/ricard/data/scnmt_gastrulation_argelaguet2019/results
    atlas: /bi/group/reik/ricard/data/pijuansala2019_gastrulation10x

###############
## Resources ##
###############

resources:
    marker_genes: /bi/group/reik/ricard/data/pijuansala2019_gastrulation10x/results/marker_genes/all_stages/marker_genes.txt.gz
    umap: "/bi/group/reik/ricard/data/scnmt_gastrulation_argelaguet2019/results/rna/dimensionality_reduction/umap_features1000_pcs30_neigh25_dist0.3.txt.gz"
    # celltypes: ["Epiblast", "Primitive_Streak", "Caudal_epiblast", "PGC", "Anterior_Primitive_Streak", "Notochord", "Def._endoderm", "Gut", "Nascent_mesoderm", "Mixed_mesoderm", "Intermediate_mesoderm", "Caudal_Mesoderm", "Paraxial_mesoderm", "Somitic_mesoderm", "Pharyngeal_mesoderm", "Cardiomyocytes", "Allantois", "ExE_mesoderm", "Mesenchyme", "Haematoendothelial_progenitors", "Endothelium", "Blood_progenitors_1", "Blood_progenitors_2", "Erythroid1", "Erythroid2", "Erythroid3", "NMP", "Rostral_neurectoderm", "Caudal_neurectoderm", "Neural_crest", "Forebrain_Midbrain_Hindbrain", "Spinal_cord", "Surface_ectoderm", "Visceral_endoderm", "ExE_endoderm", "ExE_ectoderm", "Parietal_endoderm"]
    gene_metadata: /bi/group/reik/ricard/data/ensembl/mouse/v87/BioMart/all_genes/Mmusculus_genes_BioMart.87.txt
    bedGraphToBigWig: "/bi/apps/ucsc_tools/5/bedGraphToBigWig"

#############
## Scripts ##
#############

scripts:
    create_seurat: ../processing/1_create_seurat_rna.R
    qc: ../processing/2_QC.R
    seurat_to_sce: ../processing/3_seurat_to_SCE.R
    mapping_mnn: ../mapping/run/mapping_mnn.R
    mapping_seurat: ../mapping/run/seurat/mapping_seurat.R
    parse_mapping: ../mapping/run/parse_sample_metadata_after_mapping.R
    dimensionality_reduction_sce: ../dimensionality_reduction/dimensionality_reduction_sce.R
    dimensionality_reduction_seurat: ../dimensionality_reduction/dimensionality_reduction_seurat.R
    pseudobulk_rna: ../pseudobulk/pseudobulk_rna.R
    plot_mapping_results: ../mapping/analysis/plot_mapping_umap.R
    plot_celltype_proportions: ../celltype_proportions/plot_celltype_proportions.R
    sex_assignment: ../sex/sex_assignment.R
    celltype_assignment_E35: ../celltype_assignment/celltype_assignment_E35.R
    celltype_assignment_E45: ../celltype_assignment/celltype_assignment_E45.R
    celltype_assignment_E55: ../celltype_assignment/celltype_assignment_E55.R
    parse_celltype_assignments: ../celltype_assignment/parse_celltype_assignments.R
    rename_celltypes: ../celltype_assignment/rename_celltypes.R


################
## Parameters ##
################

params:
    pseudobulk_rna:
        group_by: ["celltype"]
        normalisation_method: "cpm"
        
    mapping_mnn:
        atlas_stages: ["E6.5","E6.75","E7.0","E7.25","E7.5","E7.75","E8.0","E8.25","E8.5"]
        query_stages: ["E6.5","E7.5","E8.5"]
        npcs: 50
        n_neighbours: 25

    qc:
        min_nFeature_RNA: 4000
        max_nFeature_RNA: 10000
        percent_mt: 10
        percent_rib: 20
        
    dimensionality_reduction_sce:
        npcs: 15
        features: 1500
        n_neighbors: 15
        min_dist: 0.3
        vars_to_regress: ["nFeature_RNA"]
        # colour_by: ["plate", "celltype", "celltype_seurat"]
        colour_by: ["plate", "celltype", "celltype2", "celltype3", "nFeature_RNA"]

    dimensionality_reduction_sce_all_cells:
        npcs: 25
        features: 2500
        n_neighbors: 25
        min_dist: 0.3
        vars_to_regress: ["nFeature_RNA"]
        # colour_by: ["plate", "celltype", "celltype_seurat"]
        colour_by: ["plate", "celltype", "celltype2", "celltype3", "stage", "nFeature_RNA"]

    # dimensionality_reduction_seurat:
    #     npcs: 30
    #     features: 2500
    #     n_neighbors: 25
    #     min_dist: 0.3
    #     seed: 42
    #     vars_to_regress: ["nFeature_RNA","mit_percent_RNA"]
    #     # colour_by: ["plate", "celltype", "celltype_seurat"]
    #     colour_by: ["plate", "celltype", "celltype2", "celltype3"]

    # celltype_validation_single_cells:
    #     umap: "..."
    #     celltype_label: "celltype_seurat"

    # celltype_validation_pseudobulk:
    #     umap: "..."
    #     celltype_label: "celltype_seurat"

    plot_celltype_proportions:
        celltype_label: "celltype"
        # celltype_label: ["celltype_seurat","celltype"]

    # plot_mapping_results

    sex_assignment:
        chrY_ratio_threshold: 0.001

###########
## Slurm ##
###########

slurm:  # memory in MB
    create_seurat: 
        memory: 5000
        threads: 1
    qc: 
        memory: 2000
        threads: 1
    seurat_to_sce:
        memory: 5000
        threads: 1
    pseudobulk_rna:
        memory: 5000
        threads: 1
    mapping_mnn:
        memory: 50000
        threads: 1
    mapping_mnn_all_samples:
        memory: 60000
        threads: 1
    mapping_seurat:
        memory: 100000
        threads: 1
    mapping_seurat_all_samples:
        memory: 90000
        threads: 1
    parse_mapping_results:
        memory: 2000
        threads: 1
    dimensionality_reduction_sce:
        memory: 20000
        threads: 1
    dimensionality_reduction_seurat:
        memory: 10000
        threads: 1
    # celltype_validation_single_cells:
    #     memory: 15000
    #     threads: 1
    # celltype_validation_pseudobulk:
    #     memory: 3000
    #     threads: 1
    plot_mapping_results:
        memory: 3000
        threads: 1
    plot_celltype_proportions:
        memory: 3000
        threads: 1
    sex_assignment:
        memory: 5000
        threads: 1
    celltype_assignment_E35:
        memory: 5000
        threads: 1
    celltype_assignment_E45:
        memory: 5000
        threads: 1
    celltype_assignment_E55:
        memory: 5000
        threads: 1
    parse_celltype_assignments:
        memory: 5000
        threads: 1
    rename_celltypes:
        memory: 5000
        threads: 1