samples:
    - E7.5_TET_TKO
    - E7.5_TET_TKO_crispr
    - E8.5_WT_CD41+
    - E8.5_TET_TKO_CD41+
    - E8.5_WT_KDR+
    - E8.5_TET_TKO_KDR+
    - E8.5_WT_KDR+_CD41+
    - E8.5_TET_TKO_KDR+_CD41+
    - E8.5_WT
    - E8.5_TET_TKO

plates:
    - E7.5_tet_chimera_plate3
    - E7.5_tet_crispr_plate5
    - E7.5_tet_crispr_plate6
    - E8.5_oct20_plate1
    - E8.5_oct20_plate7
    - E8.5_oct20_plate5
    - E8.5_oct20_plate3
    - E8.5_oct20_plate4
    - E8.5_oct20_plate6
    - E8.5_oct20_plate2
    - E8.5_oct20_plate8

#################
## Directories ##
#################

directories:
    base: /Users/argelagr/data/tet_chimera_nmtseq
    original_data: /Users/argelagr/data/tet_chimera_nmtseq/original
    processed_data: /Users/argelagr/data/tet_chimera_nmtseq/processed/rna
    results: /Users/argelagr/data/tet_chimera_nmtseq/results
    atlas: /Users/argelagr/data/gastrulation10x

###############
## Resources ##
###############

resources:
    marker_genes: /Users/argelagr/data/gastrulation10x/results/marker_genes/all_stages/marker_genes.txt.gz
    umap: /Users/argelagr/data/tet_chimera_nmtseq/results/rna/dimensionality_reduction/seurat/umap_features1000_pcs30_neigh25_dist0.3.txt.gz
    celltypes: ["Epiblast", "Primitive_Streak", "Caudal_epiblast", "PGC", "Anterior_Primitive_Streak", "Notochord", "Def._endoderm", "Gut", "Nascent_mesoderm", "Mixed_mesoderm", "Intermediate_mesoderm", "Caudal_Mesoderm", "Paraxial_mesoderm", "Somitic_mesoderm", "Pharyngeal_mesoderm", "Cardiomyocytes", "Allantois", "ExE_mesoderm", "Mesenchyme", "Haematoendothelial_progenitors", "Endothelium", "Blood_progenitors_1", "Blood_progenitors_2", "Erythroid1", "Erythroid2", "Erythroid3", "NMP", "Rostral_neurectoderm", "Caudal_neurectoderm", "Neural_crest", "Forebrain_Midbrain_Hindbrain", "Spinal_cord", "Surface_ectoderm", "Visceral_endoderm", "ExE_endoderm", "ExE_ectoderm", "Parietal_endoderm"]
    stages: ["E7.5","E8.5"]
    gene_metadata: /Users/argelagr/data/tet_chimera_nmtseq/features/gene_metadata/Mmusculus_genes_BioMart.87.txt

#############
## Scripts ##
#############

scripts:
    create_seurat: ../processing/1_create_seurat_rna.R
    qc: ../processing/2_QC.R
    seurat_to_sce: ../processing/3_seurat_to_SCE.R
    mapping_mnn: ../mapping/run/mnn/mapping_mnn.R
    mapping_seurat: ../mapping/run/seurat/mapping_seurat.R
    parse_mapping: ../mapping/run/parse_sample_metadata_after_mapping.R
    dimensionality_reduction_sce: ../dimensionality_reduction/dimensionality_reduction_sce.R
    dimensionality_reduction_seurat: ../dimensionality_reduction/dimensionality_reduction_seurat.R
    pseudobulk_rna: ../pseudobulk/pseudobulk_rna.R
    # celltype_validation_single_cells: ../celltype_validation/celltype_validation_single_cells.R
    # celltype_validation_pseudobulk: ../celltype_validation/celltype_validation_pseudobulk.R
    plot_mapping_results: ../mapping/analysis/plot_mapping_umap.R
    plot_celltype_proportions: ../celltype_proportions/plot_celltype_proportions.R


################
## Parameters ##
################

params:
    pseudobulk_rna:
        group_by: ["celltype.mapped_mnn", "celltype.mapped_seurat"]
        normalisation_method: "cpm"
        
    mapping_mnn:
        atlas_stages: ["E6.5","E6.75","E7.0","E7.25","E7.5","E7.75","E8.0","E8.25","E8.5"]
        npcs: 50
        n_neighbours: 25

    mapping_seurat:
        atlas_stages: ["E6.5","E6.75","E7.0","E7.25","E7.5","E7.75","E8.0","E8.25","E8.5"]
        npcs: 50
        n_neighbours: 25

    qc:
        min_nFeature_RNA: 4000
        max_nFeature_RNA: 10000
        percent_mt: 10
        percent_rib: 20
        
    dimensionality_reduction_sce:
        npcs: 30
        features: 1000
        n_neighbors: 25
        min_dist: 0.3
        vars_to_regress: ["nFeature_RNA","mit_percent_RNA"]
        colour_by: ["plate", "celltype.mapped_mnn", "celltype.mapped_seurat"]

    dimensionality_reduction_seurat:
        npcs: 30
        features: 1000
        n_neighbors: 25
        min_dist: 0.3
        seed: 42
        vars_to_regress: ["nFeature_RNA","mit_percent_RNA"]
        colour_by: ["plate", "celltype.mapped_mnn", "celltype.mapped_seurat"]

    # celltype_validation_single_cells:
    #     umap: "..."
    #     celltype_label: "celltype.mapped_seurat"

    # celltype_validation_pseudobulk:
    #     umap: "..."
    #     celltype_label: "celltype.mapped_seurat"

    plot_celltype_proportions:
        celltype_label: "celltype.mapped_mnn"
        # celltype_label: ["celltype.mapped_seurat","celltype.mapped_mnn"]

    # plot_mapping_results

###########
## Slurm ##
###########

slurm:  # memory in MB
    create_seurat: 
        memory: 5000
        threads: 1
    qc: 
        memory: 2000
        threads: 1
    seurat_to_sce:
        memory: 5000
        threads: 1
    pseudobulk_rna:
        memory: 5000
        threads: 1
    mapping_mnn:
        memory: 30000
        threads: 1
    mapping_mnn_all_samples:
        memory: 30000
        threads: 1
    mapping_seurat:
        memory: 90000
        threads: 1
    mapping_seurat_all_samples:
        memory: 90000
        threads: 1
    parse_mapping_results:
        memory: 2000
        threads: 1
    dimensionality_reduction_sce:
        memory: 20000
        threads: 1
    dimensionality_reduction_seurat:
        memory: 10000
        threads: 1
    # celltype_validation_single_cells:
    #     memory: 15000
    #     threads: 1
    # celltype_validation_pseudobulk:
    #     memory: 3000
    #     threads: 1
    plot_mapping_results:
        memory: 3000
        threads: 1
    plot_celltype_proportions:
        memory: 3000
        threads: 1


        