name: tet_chimera_nmtseq_rna_snakemake
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconductor-scater =1.20
  - bioconductor-scran =1.20
  - bioconductor-singlecellexperiment =1.14
  - bioconductor-batchelor =1.8
  - bioconductor-scds =1.8
  # - bioconductor-destiny = 3.4 # THIS IS DEPRECIATED, DEPENDS ON bioconductor-singlecellexperiment 1.12
  # - r-xml2 =1.3.2
  - r-r.utils=2.11.0
  - r-ggpubr =0.4.0
  - r-argparse =2.1.1
  - r-seurat =4.0.4
  - r-pheatmap=1.0.12
  - r-ggrastr=0.2.3
  - scanpy=1.8.1
  - h5py=2.10.0
  - loompy=3.0.6
  - pip
  - pip:
    - dfply
    - scvelo