---
title: "Gastrulation: plot expression levels"
---
  
```{r echo=FALSE, include=FALSE}
library(scater)
```

Define I/O
```{r define_io}
source("/Users/ricard/scnmt_gastrulation/settings.R")
io$outdir <- paste0(io$basedir,"/rna/results/dimensionality_reduction")
```

```{r define_opts, echo=FALSE, include=FALSE}
opts$stage_lineage <- c(
  "E4.5_Epiblast",
  #"E4.5_Primitive_endoderm",
  "E5.5_Epiblast",
  #"E5.5_Primitive_endoderm",
  "E6.5_Epiblast",
  #"E6.5_Primitive_Streak",
  "E6.5_Visceral_endoderm",
  "E6.5_Nascent_mesoderm",
  "E7.5_Epiblast",
  "E7.5_Ectoderm",
  "E7.5_Mesoderm",
  "E7.5_Endoderm"
)
```

Update sample metadata
```{r}
sample_metadata <- sample_metadata %>% 
  .[pass_rnaQC==T & stage_lineage%in%opts$stage_lineage] %>%
  .[,c("id_rna","stage","lineage10x_2","stage_lineage")]
table(sample_metadata$stage_lineage)
```

# Load data

Load SingleCellExperiment object
```{r load_expr, echo=FALSE, include=FALSE}
sce <- load_SingleCellExperiment(io$rna.sce, normalise = TRUE, cells = sample_metadata$id_rna)
dim(sce)
```

# Parse data

Create data.table
```{r}
rna.dt <- logcounts(sce) %>% t %>% as.data.table(keep.rownames="id_rna") %>% 
  melt(id.vars="id_rna", value.name="expr", variable.name="id") %>%
  merge(rowData(sce) %>% as.data.frame(row.names=rownames(sce)) %>% tibble::rownames_to_column("ens_id") %>% .[,c("symbol","ens_id")] %>% as.data.table %>% setnames("ens_id","id"))
```

Merge data and metadata
```{r}
rna.dt <- merge(rna.dt, sample_metadata[,c("id_rna","stage_lineage","stage")], by="id_rna")
```

# Plot

Boxplots of mean differences from manual hits
```{r}
gene_id <- "Tal1"

to.plot <- rna.dt[symbol==gene_id] %>% 
  .[,stage_lineage:=factor(stage_lineage, levels=opts$stage_lineage)]

p <- ggplot(to.plot, aes(x=stage_lineage, y=expr)) +
  geom_jitter(size=0.8, color="#3CB54E") +
  geom_violin(fill="#3CB54E", alpha=0.6) +
  geom_boxplot(fill="#3CB54E", alpha=0.4, width=0.3) +
  # coord_cartesian(ylim=c(0,9)) +
  labs(title=gene_id, x="",y="RNA expression") +
  guides(x = guide_axis(angle = 90)) +
  theme_classic()
print(p)

# pdf(paste0(io$outdir,"/rna_",gene_id,".pdf"), width=8, height=5, useDingbats = F)
# print(p)
# dev.off()
```
```{r}
to.plot[,mean(expr>1),by="stage_lineage"]
```
  
  
  