---
title: "Gastrulation scNMT-seq: plot cell cycle results"
---
  
# Define settings

```{r}
if (grepl("ricard",Sys.info()['nodename'])) {
  source("/Users/ricard/scnmt_gastrulation/settings.R")
  source("/Users/ricard/scnmt_gastrulation/utils.R")
} else if (grepl("ebi",Sys.info()['nodename'])) {
  source("/homes/ricard/scnmt_gastrulation/settings.R")
  source("/homes/ricard/scnmt_gastrulation/utils.R")
}
```

I/O
```{r}
io$outdir <- paste0(io$basedir,"/rna/results/cell_cycle/pdf")
```

Options

```{r define_opts, echo=FALSE}
opts$stage_lineage <- c(
  "E3.5_ICM",
  "E4.5_Epiblast",
  "E4.5_Primitive_endoderm",
  "E5.5_Epiblast",
  "E5.5_Visceral_endoderm",
  "E6.5_Epiblast",
  "E6.5_Primitive_Streak",
  "E6.5_Visceral_endoderm",
  "E6.5_Mesoderm",
  "E7.5_Epiblast",
  "E7.5_Primitive_Streak",
  "E7.5_Ectoderm",
  "E7.5_Endoderm",
  "E7.5_Mesoderm"
)
```

# Load sample metadata

```{r load_metadata, echo=FALSE}
sample_metadata <- fread(io$metadata) %>% 
  .[,stage_lineage:=paste(stage,lineage10x_2,sep="_")] %>%
  .[pass_rnaQC==T & stage_lineage%in%opts$stage_lineage] %>%
  .[,stage_lineage:=factor(stage_lineage, levels=opts$stage_lineage)] 
```

# Load pre-computed cell cycle assignments

```{r}
cell_cycle.dt <- fread(io$cell.cycle)
colnames(cell_cycle.dt)
```

# Plot

## Pie plots

Plot proportion of cell cycle states per stage
```{r}
to.plot <- cell_cycle.dt %>% 
  merge(sample_metadata, by="id_rna") %>%
  .[phase2!="unknown"] %>%
  .[,sum:=.N,by=c("stage")] %>%
  .[,.(prop=.N/unique(sum), N=.N), by=c("stage","phase2")] %>%
  .[complete.cases(.)]

for (i in unique(to.plot$stage)) {
  p <- ggpie(to.plot[stage==i], "prop", label = "N", fill="phase2",
        palette = c("#00AFBB", "#E7B800", "#FC4E07"), color="black", title=i) +
    theme(
      legend.position = "right",
      legend.title = element_blank()
    )
  # pdf(sprintf("%s/pieplot_%s.pdf",io$outdir,i), width=5, height=5)
  print(p)
  # dev.off()
}
```

Plot proportion of cell cycle states per lineage
```{r}
to.plot <- cell_cycle.dt %>% 
  merge(sample_metadata, by="id_rna") %>%
  .[phase2!="unknown"] %>%
  .[,sum:=.N,by=c("stage_lineage")] %>%
  .[,.(prop=.N/unique(sum), N=.N), by=c("stage_lineage","phase2")] %>%
  .[complete.cases(.)]

for (i in unique(to.plot$stage_lineage)) {
  p <- ggpie(to.plot[stage_lineage==i], "prop", label = "N", fill="phase2",
        palette = c("#00AFBB", "#E7B800", "#FC4E07"), color="black", title=i) +
    theme(
      legend.position = "right",
      legend.title = element_blank()
    )
  # pdf(sprintf("%s/pieplot_%s.pdf",io$outdir,i), width=5, height=5)
  print(p)
  # dev.off()
}
```


## Overlay with UMAP

```{r}
umap.dt <- fread(io$umap)
to.plot <- umap.dt %>% 
  merge(sample_metadata,by="sample") %>%
  merge(cell_cycle.dt,by="id_rna") %>%
  .[phase2!="unknown"]
```

```{r}
p <- ggplot(to.plot, aes(x=V1, y=V2, fill=phase)) +
  # geom_point(alpha=0.9, size=3.0, shape=21) +
  ggrastr::geom_point_rast(alpha=0.9, size=3.0, shape=21, stroke=0.25) +
  scale_fill_brewer(palette="Dark2") +
  theme_classic() +
  ggplot_theme_NoAxes() +
  theme(
    legend.title = element_blank()
  )

pdf(sprintf("%s/umap_cellcycle.pdf",io$outdir), width=5, height=4)
print(p)
dev.off()
```



