---
title: "Gastrulation: dimensionality reduction on RNA data"
output: 
  BiocStyle::html_document: 
  fig_width: 10
  fig_height: 8
---
  
```{r load_modules, echo=FALSE, include=FALSE}
library(data.table)
library(purrr)
library(scater)
library(ggplot2)
library(ggpubr)
library(RColorBrewer)
library(scran)
```

```{r funcs, echo=FALSE}
# source("/Users/ricard/gastrulation/rna/differential/utils.R")
```

```{r define_opts, echo=FALSE}

## Define I/O ##
io <- list()
io$rna <- "/Users/ricard/data/gastrulation/rna/parsed/SingleCellExperiment.rds"
io$metadata.file <- "/Users/ricard/data/gastrulation/sample_metadata.txt"
io$outdir <- "/Users/ricard/data/gastrulation/rna/cell_cycle"

## Define options ##
opts <- list()

# Define stage and lineage
# opts$stage_lineage <- c(
# 
#   # E4.5
#   "E4.5_Epiblast",
#   # "E4.5_Primitive_endoderm",
#   
#   # E5.5
#   "E5.5_Epiblast",
#   # "E5.5_Visceral_endoderm",
#   
#   # E6.5
#   "E6.5_Epiblast",
#   "E6.5_Primitive_Streak",
#   # "E6.5_Visceral_endoderm",
# 
#   # E7.5 
#   "E7.5_Epiblast",
#   "E7.5_Ectoderm",
#   "E7.5_Primitive_Streak",
#   "E7.5_Endoderm",
#   "E7.5_Mesoderm"
# )
opts$stage_lineage <- "all"

# Define which cells to use
if (opts$stage_lineage[1] == "all") {
  opts$cells <- fread(io$metadata.file) %>% .[pass_rnaQC==T,id_rna]
} else {
  opts$cells <- fread(io$metadata.file) %>% 
    .[,stage_lineage:=paste(stage,lineage10x_2,sep="_")] %>%
    .[pass_rnaQC==T & stage_lineage%in%opts$stage_lineage,id_rna]
}
```

<!-- Load sample metadata -->
```{r load_metadata, echo=FALSE}
sample_metadata <- fread(io$metadata.file) %>% 
  .[id_rna %in% opts$cells] %>%
  .[,stage_lineage:=paste(stage,lineage10x_2,sep="_")]
```

<!-- Load RNA expression data --> 
```{r load_data, echo=FALSE}
sce <- readRDS(io$rna)[,opts$cells]
```

<!-- Infer cell cycle phase using cyclone from scram -->
- to be in G1 phase, if the G1 score is above 0.5 and the G2/M score is below 0.5
- to be in G2/M phase, if the G2/M score is above 0.5 and the G1 score is below 0.5; 
- to be in S phase, if both scores are below 0.5; and to be unknown, if both scores are above 0.5. 
Despite the availability of a S score, it tends to be more accurate to assign cells based on the G1 and G2/M scores only.
```{r}
mm.pairs <- readRDS(system.file("exdata", "mouse_cycle_markers.rds", package="scran"))
tmp <- cyclone(sce, mm.pairs)

df <- tmp$normalized.scores
df$id_rna <- colnames(sce)
df$phase <- tmp$phases

df$G1S <- pmax(df$G1,df$S)

df <- df %>% 
  dplyr::mutate(phase2=ifelse(G2M>G1S,"G2M","G1S")) %>%
  dplyr::mutate(phase2=ifelse(abs(G2M-G1S)<0.25,"unknown",phase2)) %>%
  dplyr::mutate(phase2=ifelse(G2M<0.50 & G1S<0.50,"unknown",phase2))
```

<!-- Save results -->
```{r}
saveRDS(tmp, paste0(io$outdir,"/cyclone.rds"))
fwrite(df, paste0(io$outdir,"/cell_cycle_scran.txt"), sep="\t", quote=F)
```

