---
title: "Gastrulation scNMT-seq: pseudobulked profiles of DNA methylation and chromatin accessibility"
---

```{r load_modules, echo=FALSE, include=FALSE}
library(data.table)
library(purrr)
library(ggplot2)
library(ggpubr)
```

<!-- Define I/O and options -->
```{r define_options, echo=FALSE}
if (grepl("ricard",Sys.info()['nodename'])) {
  base <- "/Users/ricard/scnmt_gastrulation/met/variability/differential/metacc_profiles"
} else if (grepl("ebi",Sys.info()['nodename'])) {
  base <- "/homes/ricard/scnmt_gastrulation/met/variability/differential/metacc_profiles"
} else {
  stop("Computer not recognised")
}

source(paste0(base,"/load_settings.R"))
```


<!-- (ONLY FOR TESTING) Subset cells to reduce memory burden -->
```{r subset}
opts$ncells <- 3
opts$met.cells <- sample_metadata %>% .[pass_metQC==T] %>% .[,head(unique(id_met),n=opts$ncells),by="stage_lineage"] %>% .$V1
opts$acc.cells <- sample_metadata %>% .[pass_accQC==T] %>% .[,head(unique(id_acc),n=opts$ncells),by="stage_lineage"] %>% .$V1
```

# Load data

Load genomic annotations
```{r load_annotations, echo=FALSE}
source(paste0(base,"/load_annotations.R"))
```

Load DNA methylation and chromatin accessibility data
```{r load_data, echo=FALSE}
source(paste0(base,"/load_data.R"))
```

Load results from differential analysis
```{r}
source("/Users/ricard/scnmt_gastrulation/met/variability/differential/load_differential_results.R")
```

Calculate quartiles
```{r}

```


# Parse data

Subset features by quartile
```{r}

```

Merge DNA methylation and chromatin acessibility data
```{r merge}
data <- rbind(
  met[,c("sample","stage","id","anno","dist","rate","context")],
  acc[,c("sample","stage","id","anno","dist","rate","context")]
)
data[,rate:=rate*100]
```

<!-- Rename genomic contexts -->
```{r}
# data[,anno:=stringr::str_replace_all(anno,opts$annos)]
```

Load pre-computed object
```{r}
# saveRDS(data, paste0(io$outdir,"/precomputed.rds"))
# data <- readRDS(paste0(io$outdir,"/precomputed.rds"))
```

<!-- Load genome-wide global methylation and accessibility rates -->
```{r load_stats}
met.stats <- fread(io$met.stats) %>%
  merge(sample_metadata[,.(sample,id_met)], by="id_met") %>% .[,context:="CG"]

acc.stats <- fread(io$acc.stats) %>%
  merge(sample_metadata[,.(sample,id_acc)], by="id_acc") %>% .[,context:="GC"]

stats <- rbind(
  met.stats[,c("sample","mean","coverage","context")],
  acc.stats[,c("sample","mean","coverage","context")]
) %>% merge(sample_metadata[,c("sample","stage")],by="sample")
```


<!-- Plot joint methylation and accessibility profiles -->

Per stage, genomic contexts side by side
```{r plot1}
p_list <- list()

for (i in opts$stages) {
  print(i)
  
  tmp <- data[stage==i]
  
  p_list[[i]] <- ggplot(tmp, aes(x=dist, y=rate, group=context, fill=context, color=context)) +
    facet_wrap(~anno, nrow=1, scales="fixed") +
    stat_summary(geom="ribbon", fun.data="mean_se", alpha=1) +
    stat_summary(geom="line", fun.data="mean_se") +
    geom_hline(yintercept=stats[context=="CG" & stage==i,median(mean,na.rm=T)], color="#F37A71", linetype="dashed", alpha=0.75, size=0.75) +
    geom_hline(yintercept=stats[context=="GC" & stage==i,median(mean,na.rm=T)], color="#00BFC4", linetype="dashed", alpha=0.75, size=0.75) +
    labs(x="Distance from center (bp)", y="Met/Acc levels (%)") +
    coord_cartesian(ylim=c(0,50)) +
    # scale_x_continuous(breaks=c(-1,0,1)) +
    xlim(-opts$window_size, opts$window_size) +
    guides(fill=FALSE, color=FALSE, linetype=FALSE) +
    theme_classic() +
    theme(
      axis.text.x = element_text(size=rel(0.8), colour="black"),
      axis.text.y = element_text(size=rel(1.2), colour="black")
    )

  pdf(file=sprintf("%s/%s.pdf",io$outdir,i), width=8.5, height=5)
  print(p_list[[i]])
  dev.off()
}
```


Per cell
```{r plot2}
p_list <- list()

for (i in as.character(unique(data$sample))) {
  print(i)
  
  tmp <- data[sample==i]
  
  p_list[[i]] <- ggplot(tmp, aes(x=dist, y=rate, group=context, fill=context, color=context)) +
    facet_wrap(~anno, nrow=1, scales="fixed") +
    stat_summary(geom="ribbon", fun.data="mean_se", alpha=1) +
    stat_summary(geom="line", fun.data="mean_se") +
    geom_hline(yintercept=stats[context=="CG" & sample==i,mean], color="#F37A71", linetype="dashed", alpha=0.75, size=0.75) +
    geom_hline(yintercept=stats[context=="GC" & sample==i,mean], color="#00BFC4", linetype="dashed", alpha=0.75, size=0.75) +
    labs(x="Distance from center (bp)", y="Met/Acc levels (%)") +
    coord_cartesian(ylim=c(0,50)) +
    # scale_x_continuous(breaks=c(-1,0,1)) +
    xlim(-opts$window_size, opts$window_size) +
    guides(fill=FALSE, color=FALSE, linetype=FALSE) +
    theme_classic() +
    theme(
      axis.text.x = element_text(size=rel(0.8), colour="black"),
      axis.text.y = element_text(size=rel(1.2), colour="black")
    )
  # print(p_list[[i]])

  pdf(file=sprintf("%s/per_cell/%s.pdf",io$outdir,i), width=8.5, height=5)
  print(p_list[[i]])
  dev.off()
}
```
