
<!-- Gene set enrichment analysis -->

Prepare data
```{r}
# If a gene has multiple hits, just keep the most significant
cor2 <- cor %>% split(.$anno) %>% map(~ .[,.SD[which.min(p)], by=c("gene")]) %>% rbindlist
```

```{r}
tmp <- cor2[,c("gene","sig")] %>%
  .[,.(sig=mean(sig)), by="gene"] %>%
  .[,sig:=sig>0]
```

Load MsigDb gene set
```{r go_enrichment, echo=FALSE}
# I/O MSigDB
io$msigFile <- "/Users/ricard/data/MSigDB/v6.0/mus_musculus/C5/bp_binary_matrix_ensembl.rds"
# io$msigFile <- "/Users/ricard/data/MSigDB/v6.0/mus_musculus/C2/binary_matrix_ensembl.rds"

# Load MSigDB files
feature.sets <- readRDS(io$msigFile)
```

Filter gene sets
```{r}
# Filter feature sets with small number of features
opts$min.size <- 25
feature.sets <- feature.sets[rowSums(feature.sets)>=opts$min.size,]
  
# Remove features that do not intersect between the feature sets and the data
features <- intersect(toupper(tmp$gene),colnames(feature.sets))
tmp_filt <- tmp[,gene:=toupper(gene)] %>% .[gene %in% features]
feature.sets_filt <- feature.sets[,features]
```

Perform Fisher exact test per gene set
```{r}
asd <- melt.data.table(as.data.table(feature.sets_filt, keep.rownames="pathway"), id.vars = "pathway", variable.name="gene", value.name="value") %>% 
  merge(tmp_filt[,c("gene","sig")], allow.cartesian=T, by="gene")

go_results <- asd[,.(p=fisher.test(x=matrix(data=c(.SD[sig==T & value==1,.N],
                                                   .SD[sig!=T & value==1,.N],
                                                   .SD[sig==T & value==0,.N],
                                                   .SD[sig!=T & value==0,.N]), 
                                              nrow=2, ncol=2), alternative="greater")[["p.value"]]), by="pathway"] %>% .[,padj:=p.adjust(p, method = "fdr")]
```

Plot GO results
```{r}
tmp <- go_results %>% setorder(padj)

# Convert pvalues to log scale (add a small regulariser to avoid numerical errors)
tmp$log <- -log10(tmp$padj)

# Order according to significance
tmp$pathway <- factor(tmp$pathway, levels = tmp$pathway[order(tmp$padj, decreasing = T)])

# Select top N pathways to display
tmp_filt <- tmp[1:15]

p <- ggplot(tmp_filt, aes(x=pathway, y=log)) +
  geom_point(size=5) +
  geom_hline(yintercept=-log10(opts$threshold), linetype="longdash", color = "red") +
  scale_color_manual(values=c("black","red")) +
  geom_segment(aes(xend=pathway, yend=0)) +
  ylab(expression(paste("-log"[10],"(",plain(q),"-value)"))) + coord_flip() +
  theme(
    axis.text.y = element_text(size=rel(0.9), hjust=1, color='black'),
    axis.text.x = element_text(size=rel(1.2), vjust=0.5, color='black'),
    axis.title.y = element_blank(), 
    panel.background = element_blank()
  )
print(p)

pdf(paste0(io$outdir,"/GOenrich.pdf"), width=8, height=4, useDingbats = F)
print(p)
dev.off()
```

