---
title: "Differential variability analysis"
---

Load libraries
```{r}
# suppressPackageStartupMessages(library(ggpubr))
# suppressPackageStartupMessages(library(viridis))
# suppressPackageStartupMessages(library(scattermore))
# suppressPackageStartupMessages(library(logitnorm))
```

Define settings
```{r}
if (grepl("ricard",Sys.info()['nodename'])) {
  source("/Users/ricard/scnmt_gastrulation/settings.R")
  io$dir.lib <- "/Users/ricard/bbreg/lib/"
  io$bayes.dir <- paste0(io$scmet,"/differential/bayes")
  io$point_estimates.dir <- paste0(io$scmet,"/differential/bayes/txt")
  io$out.dir <- paste0(io$scmet,"/differential/differential_variability/pdf")
  source("/Users/ricard/scnmt_gastrulation/met/variability/differential/differential_variability/volcano_plots/utils.R")
} else {
  stop("Computer not recognised")
}

# Source project lib directory
R.utils::sourceDirectory(io$dir.lib, modifiedOnly = FALSE)
```

Options
```{r}
# Define genomic contexts
opts$anno <- c(
  # "H3K27ac_distal_E7.5_union_intersect12_500",
  # "H3K27ac_distal_E7.5_union_intersect12",
  # "H3K4me3_E7.5_union",
  # "prom_2000_2000"
  "H3K27ac_distal_E7.5_Mes_intersect12_500",
  "H3K27ac_distal_E7.5_Mes_intersect12",
  "H3K27ac_distal_E7.5_End_intersect12_500",
  "H3K27ac_distal_E7.5_End_intersect12",
  "H3K27ac_distal_E7.5_Ect_intersect12_500",
  "H3K27ac_distal_E7.5_Ect_intersect12"
)

# Define groups
opts$groups <- c("E6.5", "E7.5")

# Differential testing hyperparameters
opts$min.LOR <- log(2.5)
opts$tail_prob <- 0.9
```


Load pre-computed differential analysis results
```{r}
diff.dt <- opts$anno %>% 
  map(~ fread(sprintf("%s/%s_epsilon.txt.gz", io$point_estimates.dir, .))) %>%
  rbindlist
```


Call differentially variable features
```{r}
diff.dt %>%
  .[,sig:=abs(res_disp_change)>=opts$min.LOR & res_disp_diff_tail_prob>=opts$tail_prob] %>%
  .[sig==F,res_disp_diff_test:="Nodiff"] %>%
  .[sig==T & res_disp_change>0,res_disp_diff_test:=paste0(opts$groups[1],"+")] %>%
  .[sig==T & res_disp_change<0,res_disp_diff_test:=paste0(opts$groups[2],"+")]

diff.dt[,mean(sig),by="anno"]
```

Volcano plots
```{r, echo=FALSE}
for (i in opts$anno) {
  
  p <- volcano_plot(
    diff_obj = diff.dt[anno==i],
    mode = "epsilon",
    evidence_thresh = opts$tail_prob,
    change_thresh = opts$min.LOR,
    xlab = "Log odds ratio"
  )
  p <- p +
    coord_cartesian(xlim=c(-3,3)) +
    scale_fill_manual(values = c("lightpink3", "darkolivegreen3","#595959")) +
    scale_size_manual(values = c(1.75,1.75,0.6)) +
    scale_alpha_manual(values = c(0.8,0.8,0.4))
  
  pdf(sprintf("%s/volcano_plots/volcano_%s_epsilon.pdf",io$out.dir,i), width = 7, height = 5, useDingbats = F)
  print(p)
  dev.off()
}
```
