samples:
    - E7.5_TET_TKO
    - E7.5_TET_TKO_crispr
    - E7.5_TET_TKO_crispr
    - E8.5_WT_CD41+
    - E8.5_TET_TKO_CD41+
    - E8.5_WT_KDR+
    - E8.5_TET_TKO_KDR+
    - E8.5_WT_KDR+_CD41+
    - E8.5_TET_TKO_KDR+_CD41+
    - E8.5_WT
    - E8.5_TET_TKO

plates:
    - E7.5_tet_chimera_plate3
    - E7.5_tet_crispr_plate5
    - E7.5_tet_crispr_plate6
    - E8.5_oct20_plate1
    - E8.5_oct20_plate7
    - E8.5_oct20_plate5
    - E8.5_oct20_plate3
    - E8.5_oct20_plate4
    - E8.5_oct20_plate6
    - E8.5_oct20_plate2
    - E8.5_oct20_plate8

genomic_contexts:
    - multiome_peaks
    - CGI
    - H3K27ac_distal_E7.5_Ect_intersect12
    - H3K27ac_distal_E7.5_End_intersect12
    - H3K27ac_distal_E7.5_Mes_intersect12
    - LINE
    - LTR
    - genebody
    - prom_2000_2000
    - prom_2000_2000_cgi
    - prom_2000_2000_noncgi
    - prom_200_200
    - prom_200_200_cgi
    - prom_200_200_noncgi

#################
## Directories ##
#################

directories:
    base: /bi/scratch/Stephen_Clark/snakemake/tet_chimera_nmtseq/
    processed_data: /bi/scratch/Stephen_Clark/snakemake/tet_chimera_nmtseq/processed
    results: /bi/scratch/Stephen_Clark/snakemake/tet_chimera_nmtseq/results
    features: /bi/scratch/Stephen_Clark/snakemake/tet_chimera_nmtseq/features/genomic_contexts
    genome_seq: /bi/scratch/Stephen_Clark/annotations/mm10_sequence/mm10.genome
    bedGraphToBigWig: "/bi/apps/ucsc_tools/5/bedGraphToBigWig"
    rna_SingleCellExperiment: /bi/scratch/Stephen_Clark/snakemake/tet_chimera_nmtseq/processed/rna_new/SingleCellExperiment.rds
    tss_file: /bi/scratch/Stephen_Clark/annotations/mm10_regulation/genes/TSS_protein_coding.bed

###############
## Resources ##
###############

resources:
    celltypes: ["Epiblast", "Primitive_Streak", "Caudal_epiblast", "PGC", "Anterior_Primitive_Streak", "Notochord", "Def._endoderm", "Gut", "Nascent_mesoderm", "Mixed_mesoderm", "Intermediate_mesoderm", "Caudal_Mesoderm", "Paraxial_mesoderm", "Somitic_mesoderm", "Pharyngeal_mesoderm", "Cardiomyocytes", "Allantois", "ExE_mesoderm", "Mesenchyme", "Haematoendothelial_progenitors", "Endothelium", "Blood_progenitors_1", "Blood_progenitors_2", "Erythroid1", "Erythroid2", "Erythroid3", "NMP", "Rostral_neurectoderm", "Caudal_neurectoderm", "Neural_crest", "Forebrain_Midbrain_Hindbrain", "Spinal_cord", "Surface_ectoderm", "Visceral_endoderm", "ExE_endoderm", "ExE_ectoderm", "Parietal_endoderm"]
    stages: ["E7.5","E8.5"]

#############
## Scripts ##
#############

scripts:
    calculate_global_stats_per_cell: ../stats/calculate_stats.R
    calculate_chr_stats_per_cell: ../stats/calculate_stats_per_chr.R
    plot_global_stats_per_cell: ../stats/plot_stats.R
    plot_chr_stats_per_cell: ../stats/plot_stats_per_chr.R
    qc: ../qc/qc.R
    parse_metadata_after_qc: ../qc/parse_sample_metadata_after_qc.R
    quantify_feature_level: ../quantify_feature_level/quantify_feature_level.R
    pseudobulk: ../pseudobulk/pseudobulk_cpg_level.R
    boxplots_metacc_feature_level: ../boxplots_feature_level/boxplots_feature_level.R
    calculate_tss_profiles: ../profiles/calculate_metacc_profiles.R
    plot_tss_profiles: ../profiles/plot_metacc_profiles.R
    bigwig: ../bigwig/create_bigwig_pseudobulk.R
    metrna_coupling: ../../metrna/coupling/local_coupling/calculate_metrna_coupling.R
    metacc_coupling: ../../metacc/coupling/local_coupling/calculate_metacc_coupling.R
    accrna_coupling: ../../accrna/coupling/local_coupling/calculate_accrna_coupling.R



################
## Parameters ##
################

params:
    qc_met:
        minimum_number_sites: 5000
        min_rate: 50
        max_rate: 100
    qc_acc:
        minimum_number_sites: 10000
        min_rate: 10
        max_rate: 40
    pseudobulk:
        # group_by: ["sample","celltype_class"]
        group_by: ["celltype_class"]
        min_cells: 15
    calculate_tss_profiles:
        window_size: 3000
        met_tile: 100
        acc_tile: 50
    bigwig_met:
        step_size: 500
        min_rate_bigwig: 10
    bigwig_acc:
        step_size: 100
        min_rate_bigwig: 5
    metrna_coupling:
        up: 3000
        down: 3000
        window: 150
        tile: 50
    metacc_coupling:
        up: 3000
        down: 3000
        window: 150
        tile: 50
    accrna_coupling:
        up: 3000
        down: 3000
        window: 100
        tile: 50

###########
## Slurm ##
###########

slurm:  # memory in MB
    calculate_global_stats_per_cell: 
        memory: 5000
        threads: 1
    calculate_chr_stats_per_cell: 
        memory: 5000
        threads: 1
    plot_global_stats_per_cell: 
        memory: 3000
        threads: 1
    qc: 
        memory: 5000
        threads: 1
    quantify_feature_level: 
        memory: 15000
        threads: 1
    pseudobulk: 
        memory: 25000
        threads: 1
    boxplots_metacc_feature_level: 
        memory: 5000
        threads: 1
    calculate_tss_profiles: 
        memory: 50000
        threads: 1
    plot_tss_profiles: 
        memory: 10000
        threads: 1    
    bigwig_met:
        memory: 20000
        threads: 1    
    bigwig_acc:
        memory: 50000
        threads: 1    
    metrna_coupling:
        memory: 3000
        threads: 1   
    accrna_coupling:
        memory: 6000
        threads: 1   
    metacc_coupling:
        memory: 8000
        threads: 1   
