---
title: "Gastrulation: pseudobulked profiles of DNA methylation and chromatin accessibility"
output: 
  BiocStyle::html_document: 
    fig_width: 10
    fig_height: 8
---

```{r load_modules, echo=FALSE, include=FALSE}
library(data.table)
library(purrr)
library(ggplot2)
```

```{r fncs, echo=FALSE}
theme_boxplot <- function() {
    theme(
      plot.margin = unit(c(t=1,r=1,b=1,l=1), "cm"),
      plot.title = element_text(size=25,hjust=0.5),
      axis.text=element_text(size=15, colour="black"),
      axis.title.x=element_text(size=17, margin=margin(10,0,0,0)),
      axis.title.y=element_text(size=17, margin=margin(0,10,0,0)),
      axis.line = element_line(size=rel(1.0)),
      axis.ticks = element_line(size=rel(1.3), color="black"),
      legend.key = element_blank(),
      legend.position = "top",
      legend.direction = "horizontal",
      # legend.key.size= unit(0.5, "cm"),
      legend.key.width=unit(1.2,"line"),
      legend.key.height=unit(1.0,"line"),
      legend.margin = margin(t=10, r=0, b=0, l=0, unit="pt"),
      legend.title = element_blank(),
      legend.text = element_text(size=15),
      panel.border=element_blank(),
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank(),
      panel.background=element_blank()
    )
}

f <- function(x) { return(data.frame(y=mean(x), ymin=mean(x)-sd(x), ymax=mean(x)+sd(x))) }
```


```{r define_options, echo=FALSE}

# Define I/O
io <- list()
io$basedir <- "/Users/ricard/data/gastrulation"
io$outdir <- "/Users/ricard/gastrulation/metaccrna/traceback/profiles/out"
io$in.sample_metadata <- paste0(io$basedir,"/sample_metadata_scNMT.txt")
io$features.indir <- paste(io$basedir,"features/filt",sep="/")
io$met.indir <- paste(io$basedir,"met/raw/",sep="/")
io$acc.indir <- paste(io$basedir,"acc/raw/",sep="/")
# io$diffrna.dir <- "/Users/ricard/data/gastrulation_norsync_stuff/rna/test"
io$diffmet.dir <- "/Users/ricard/data/gastrulation_norsync_stuff/met/test/diff_featurelevel"
io$diffacc.dir <- "/Users/ricard/data/gastrulation_norsync_stuff/acc/test/diff_featurelevel"

# Define options
opts <- list()
opts$window_size <- 2000
opts$met.tile <- 150
opts$acc.tile <- 100

# opts$window_size <- 1500
# opts$met.tile <- 100
# opts$acc.tile <- 50


# Define which annotations to use and where to center the windows
opts$annos <- c(
  "H3K27ac_distal_E7.5_Ect_intersect12"="center",
  "H3K27ac_distal_E7.5_Mes_intersect12"="center",
  "H3K27ac_distal_E7.5_End_intersect12"="center",
  "TSC_distal_H3K27ac"="center"
)

# Define annotation names
opts$anno.names <-c(
  "H3K27ac_distal_E7.5_Ect_intersect12"="Ectoderm putative enhancers",
  "H3K27ac_distal_E7.5_Mes_intersect12"="Mesoderm putative enhancers",
  "H3K27ac_distal_E7.5_End_intersect12"="Endoderm putative enhancers",
  "TSC_distal_H3K27ac"="Trophoblast enhancers"
)

# Define stage and lineage
opts$stage_lineage <- c(
  "E6.5_TB"
)

# Define which cells to use
sample_metadata <- fread(io$in.sample_metadata,stringsAsFactors=T) %>% 
  .[,stage_lineage:=as.factor(paste(stage,lineage,sep="_"))] %>%
  .[(pass_metQC==T | pass_accQC==T) & outlier==F & stage_lineage%in%opts$stage_lineage] 
  
opts$met.cells <- as.character(sample_metadata[pass_metQC==T,id_met])
opts$acc.cells <- as.character(sample_metadata[pass_accQC==T,id_acc])
```

<!-- Load genomic annotations -->
```{r load_annotations, echo=FALSE, warning=FALSE}
anno_list <- list()
for (anno in names(opts$annos)) {
  tmp <- fread(sprintf("%s/%s.bed",io$features.indir,anno))[,c(1,2,3,4,5,6)]
  colnames(tmp) <- c("chr","start","end","strand","id","anno")
  
  # Define central position for the window approach
  if (opts$annos[anno] == "start") {
    tmp <- rbind(tmp[strand=="+",.(chr,start,strand,id,anno)] %>% .[,center:=start] %>% .[,c("start"):=NULL], 
                 tmp[strand=="-",.(chr,end,strand,id,anno)] %>% .[,center:=end] %>% .[,c("end"):=NULL]) 
  }
  if (opts$annos[anno] == "center") {
    stopifnot(all(tmp[,end] > tmp[,start]))
    tmp <- tmp[,.(chr,start,end,strand,id,anno)][,center:=round(end+start)/2][,c("start","end"):=NULL]
  }
  if (opts$annos[anno] == "end") {
    tmp <- rbind(tmp[strand=="+",.(chr,end,strand,id,anno)][,center:=end][,c("end"):=NULL], 
                 tmp[strand=="-",.(chr,start,strand,id,anno)][,center:=start][,c("start"):=NULL])
  }
  anno_list[[anno]] <- tmp %>% .[, c("start","end") := list(center-opts$window_size,center+opts$window_size)]
}

anno_df <- rbindlist(anno_list) %>% 
  .[,c("anno","chr"):=list(as.factor(anno),as.factor(sub("chr","",chr)))] %>%
  setkey(chr,start,end)
rm(anno_list)
```

<!-- Load methylation data -->
```{r load_data, echo=FALSE}
met_list <- list()
for (cell in opts$met.cells) {
  tmp <- fread(sprintf("zcat < %s/%s.tsv.gz",io$met.indir,cell), showProgress=F, stringsAsFactors=F) %>%
    .[,c("chr","pos","rate")] %>% .[,id_met:=cell] %>% 
    .[,c("start","end"):=list(pos,pos)] %>% setnames("pos","bp") %>% setkey("chr","start","end") %>%
    
    foverlaps(.,anno_df, nomatch=0) %>% .[, c("chr","i.start","i.end") := NULL] %>%
    .[,id:=as.character(id)] %>%
    .[,dist:=ifelse(strand %in% c("+","*"),bp-center,center-bp)] %>% 
    .[, dist:=opts$met.tile*round(dist/opts$met.tile)] %>%
    .[,list(rate=mean(rate), n=.N),by=.(id_met,id,dist,anno)]
  met_list[[cell]] <- tmp
}
met <- rbindlist(met_list) %>%
  .[,c("id_met","id","context"):=list(as.factor(id_met),as.factor(id),"CG")]
  
rm(met_list)
```

<!-- Load accessibility data -->
```{r}
acc_list <- list()
for (cell in opts$acc.cells) {
  tmp <- fread(sprintf("zcat < %s/%s.tsv.gz",io$acc.indir,cell), showProgress=F, stringsAsFactors=F) %>%
    .[,c("chr","pos","rate")] %>% .[,id_acc:=cell] %>% 
    .[,c("start","end"):=list(pos,pos)] %>% setnames("pos","bp") %>% setkey("chr","start","end") %>%
    
    foverlaps(.,anno_df, nomatch=0) %>% .[, c("chr","i.start","i.end") := NULL] %>%
    .[,id:=as.character(id)] %>%
    .[,dist:=ifelse(strand %in% c("+","*"),bp-center,center-bp)] %>% 
    .[, dist:=opts$acc.tile*round(dist/opts$acc.tile)] %>%
    .[,list(rate=mean(rate), n=.N),by=.(id_acc,id,dist,anno)]
  acc_list[[cell]] <- tmp
}
acc <- rbindlist(acc_list) %>%
  .[,c("id_acc","id","context"):=list(as.factor(id_acc),as.factor(id),"GC")]
  
rm(acc_list)
```

<!-- Merge data with sample metadata -->
```{r}
met <- met %>% merge(sample_metadata[,c("sample","id_met","stage","stage_lineage")], by="id_met") %>%
  droplevels()
acc <- acc %>% merge(sample_metadata[,c("sample","id_acc","stage","stage_lineage")], by="id_acc") %>%
droplevels()
```

<!-- Combine methylation and accessibility data -->
```{r}
data <- rbind(
  met[,c("sample","stage","stage_lineage","id","anno","dist","rate","context")],
  acc[,c("sample","stage","stage_lineage","id","anno","dist","rate","context")]
)
```

```{r}
data[,rate:=rate*100]
```

<!-- Summarise across all genome-wide features -->
```{r}
data_filt <- data %>%
  .[,.(rate=mean(rate), N=.N, var=var(rate)), by=c("stage","stage_lineage","dist","anno","context")]
# fwrite(data_filt, "/Users/ricard/data/gastrulation_norsync_stuff/foo.txt", quote=F)
```

```{r}
met.stats <- fread("/Users/ricard/gastrulation/met/stats/samples/out/sample_stats.txt") %>% .[anno=="all",.(id_met,mean)] %>%
  merge(sample_metadata[,.(sample,id_met)], by="id_met") %>% .[,context:="CG"]

acc.stats <- fread("/Users/ricard/gastrulation/acc/stats/samples/out/sample_stats.txt") %>% .[anno=="all",.(id_acc,mean)] %>%
  merge(sample_metadata[,.(sample,id_acc)], by="id_acc") %>% .[,context:="GC"]

stats <- rbind(met.stats[,c("sample","mean","context")],acc.stats[,c("sample","mean","context")]) %>%
  merge(sample_metadata[,c("sample","stage","stage_lineage")],by="sample") %>%
  .[,.(mean=mean(mean)),by=c("stage_lineage","context")]
```

<!-- Plot joint methylation and accessibility profiles -->

Per stage_lineage and genomic context separately
```{r plot_profiles, echo=FALSE, include=TRUE, warning=FALSE}
# f <- function(x) { return(data.frame(y=mean(x), ymin=mean(x)-sd(x), ymax=mean(x)+sd(x))) }
# # mean_sd <- function(x) { return(data.frame(y=mean(x), ymin=mean(x)-sd(x)/2, ymax=mean(x)+sd(x)/2)) }
# mean_sd <- function(x, mult = 1) {  
#   x <- na.omit(x)
#   sd <- mult * sqrt(var(x))
#   mean <- mean(x)
#   data.frame(y = mean, ymin = mean - sd, ymax = mean + sd)
# }
# 
# for (i in as.character(unique(data$stage_lineage))) {
#   for (n in as.character(unique(data$anno))) {
#     tmp <- data[anno==n & stage_lineage==i]
#     p <- ggplot(tmp, aes(x=dist, y=rate, group=context, fill=context, color=context)) +
#       stat_summary(fun.data="mean_se", geom="ribbon", alpha=0.25) +
#       # stat_summary(aes(fill=context, color=context), fun.data=mean_se, geom="smooth", alpha=0.5, size=1.0) +
#       stat_summary(geom="line") +
#       # geom_line() +
#       # stat_summary(aes(group=context, colour=context, fill=context), fun.y=mean, geom="line") +
#       labs(x="Distance from center (bp)", y="Rate", title=sprintf("%s:%s",i,n)) +
#       xlim(-opts$window_size, opts$window_size) +
#       # scale_colour_manual(values=opts$colors) +
#       guides(fill=FALSE, color=FALSE, linetype=FALSE) +
#       theme_boxplot() +
#       theme(
#         plot.title = element_text(size=15,hjust=0.5),
#         axis.text=element_text(size=12, colour="black"),
#         axis.title.x=element_text(size=rel(1.0), margin=margin(10,0,0,0)),
#         axis.title.y=element_text(size=rel(1.0), margin=margin(0,10,0,0)),
#         axis.line = element_line(size=rel(1.0)),
#         axis.ticks = element_line(size=rel(1.3), color="black"),
#         legend.text = element_text(size=11)
#       )
#     print(p)
#     
#     pdf(file=sprintf("%s/%s_%s.pdf",io$outdir,i,n), width=5, height=5)
#     print(p)
#     dev.off()
#   }
# }
```

Per stage_lineage, genomic contexts side by side
```{r}
for (i in as.character(unique(data$stage_lineage))) {
  print(i)
  
  tmp <- data[stage_lineage==i] %>%  
    .[,anno:=stringr::str_replace_all(anno,opts$anno.names)]
  
  p <- ggplot(tmp, aes(x=dist, y=rate, group=context, fill=context, color=context)) +
    facet_wrap(~anno, nrow=1, scales="fixed") +
    stat_summary(geom="ribbon", alpha=0.10) +
    stat_summary(geom="line") +
    geom_hline(yintercept=stats[context=="CG" & stage_lineage==i,mean(mean,na.rm=T)], color="#F37A71", linetype="dashed", alpha=0.75, size=0.75) +
    geom_hline(yintercept=stats[context=="GC" & stage_lineage==i,mean(mean,na.rm=T)], color="#00BFC4", linetype="dashed", alpha=0.75, size=0.75) +
    # labs(x="Distance from center (bp)", y="Rate", title=i) +
    labs(x="", y="") +
    coord_cartesian(ylim=c(15,90)) +
    xlim(-opts$window_size, opts$window_size) +
    # scale_colour_manual(values=opts$colors) +
    guides(fill=FALSE, color=FALSE, linetype=FALSE) +
    theme_boxplot() +
    theme(
      axis.text.x = element_text(size=rel(0.9), colour="black"),
      axis.text.y = element_text(size=rel(1.1), colour="black"),
      axis.title.x = element_text(size=rel(1.0), margin=margin(10,0,0,0)),
      axis.title.y = element_text(size=rel(1.0), margin=margin(0,10,0,0)),
      axis.line = element_line(size=rel(1.0)),
      axis.ticks = element_line(size=rel(1.3), color="black"),
      legend.text = element_text(size=11),
      strip.text = element_blank()
    )
  print(p)

  # pdf(file=sprintf("%s/%s.pdf",io$outdir,i), width=8.5, height=5)
  # print(p)
  # dev.off()
}
```












STOP HERE
```{r}
stop()
```



Relative rates
```{r}
# mean_f <- function(x,context) 100 * (mean(x) - asd[context,min]) / ( asd[context,max] - asd[context,min] )
# all_f <- function(x,context) { return(
#   data.frame(
#     y = 100 * (mean(x) - asd[context,min]) / ( asd[context,max] - asd[context,min]),
#     ymin = 100 * (mean(x) - asd[context,min]) / ( asd[context,max] - asd[context,min]) - sd(x),
#     ymax = 100 * (mean(x) - asd[context,min]) / ( asd[context,max] - asd[context,min]) + sd(x)
#     )
# ) }
all_f <- function(x,foo) { return(
  data.frame(
    y = 100 * (mean(x) - asd[foo,min]) / ( asd[foo,max] - asd[foo,min]),
    ymin = 100 * (mean(x) - asd[foo,min]) / ( asd[foo,max] - asd[foo,min]) - sd(x),
    ymax = 100 * (mean(x) - asd[foo,min]) / ( asd[foo,max] - asd[foo,min]) + sd(x)
    )
) }

asd <- data[,.(rate=mean(rate)), by=c("context","anno","dist","stage_lineage")] %>%
  .[,.(min=min(rate), max=max(rate)), by=c("context","stage_lineage")] %>% 
  .[,foo:=paste(context,stage_lineage,sep="_")] %>%
  setkey(foo)
    
for (i in as.character(unique(data$stage_lineage))) {
    tmp <- data[stage_lineage==i] %>% 
      .[,anno:=stringr::str_replace_all(anno,opts$anno.names)] %>%
      .[,foo:=paste(context,stage_lineage,sep="_")]
    
    # to.plot <- tmp[,.(rate=mean(rate)), by=c("sample","context","dist","anno")]
    
    p <- ggplot(tmp, aes(x=dist, y=rate)) +
      facet_wrap(~anno, nrow=1, scales="fixed") +
      stat_summary(fun.data=all_f, fun.args=paste0("GC_",i), geom="smooth", size=1.0, data=tmp[context=="GC" & stage_lineage==i], color="#00BFC4", fill="#00BFC4", alpha=0.5) +
      stat_summary(fun.data=all_f, fun.args=paste0("CG_",i), geom="smooth", size=1.0, data=tmp[context=="CG" & stage_lineage==i], color="#F37A71", fill="#F37A71", alpha=0.5) +
      # stat_summary(fun.y=mean_f, geom="line") +
      # stat_summary(geom="ribbon", alpha=0.10) +
      # stat_summary(geom="line") +
      # labs(x="Distance from center (bp)", y="Rate", title=i) +
      labs(x="", y="") +
      coord_cartesian(ylim=c(0,100)) +
      xlim(-opts$window_size, opts$window_size) +
      # scale_colour_manual(values=opts$colors) +
      guides(fill=FALSE, color=FALSE, linetype=FALSE) +
      theme_boxplot() +
      theme(
        axis.text.x = element_text(size=rel(0.9), colour="black"),
        axis.text.y = element_text(size=rel(1.1), colour="black"),
        axis.title.x = element_text(size=rel(1.0), margin=margin(10,0,0,0)),
        axis.title.y = element_text(size=rel(1.0), margin=margin(0,10,0,0)),
        axis.line = element_line(size=rel(1.0)),
        axis.ticks = element_line(size=rel(1.3), color="black"),
        legend.text = element_text(size=11),
        strip.text = element_blank()
      )
    # print(p)

    pdf(file=sprintf("%s/%s.pdf",io$outdir,i), width=8.5, height=5)
    print(p)
    dev.off()
}
```

Per cell, genomic contexts side by side
```{r}
for (i in as.character(unique(data$stage_lineage))) {
  for (j in as.character(unique(data[stage_lineage==i,sample]))) {
    tmp <- data[stage_lineage==i & sample==j] %>% .[,anno:=stringr::str_replace_all(anno,opts$anno.names)]
    p <- ggplot(tmp, aes(x=dist, y=rate, group=context, fill=context, color=context)) +
      facet_wrap(~anno, nrow=1, scales="fixed") +
      
      # stat_summary(geom="ribbon", alpha=0.10) +
      # stat_summary(geom="line") +
      
      stat_summary(fun.data=all_f, fun.args=paste0("GC_",i), geom="smooth", size=1.0, data=tmp[context=="GC" & stage_lineage==i], color="#00BFC4", fill="#00BFC4", alpha=0.5) +
      stat_summary(fun.data=all_f, fun.args=paste0("CG_",i), geom="smooth", size=1.0, data=tmp[context=="CG" & stage_lineage==i], color="#F37A71", fill="#F37A71", alpha=0.5) +
      
      # labs(x="Distance from center (bp)", y="Rate", title=i) +
      labs(x="", y="") +
      coord_cartesian(ylim=c(0,100)) +
      xlim(-opts$window_size, opts$window_size) +
      # scale_colour_manual(values=opts$colors) +
      guides(fill=FALSE, color=FALSE, linetype=FALSE) +
      theme_boxplot() +
      theme(
        axis.text.x = element_text(size=rel(0.9), colour="black"),
        axis.text.y = element_text(size=rel(1.1), colour="black"),
        axis.title.x = element_text(size=rel(1.0), margin=margin(10,0,0,0)),
        axis.title.y = element_text(size=rel(1.0), margin=margin(0,10,0,0)),
        axis.line = element_line(size=rel(1.0)),
        axis.ticks = element_line(size=rel(1.3), color="black"),
        legend.text = element_text(size=11),
        strip.text = element_blank()
      )

    pdf(file=sprintf("%s/%s_%s.pdf",io$outdir,i,j), width=8.5, height=5)
    print(p)
    dev.off()
  }
}
```

