---
title: "Variance versus background"
author: "Stephen Clark"
date: "05/14/2018"
output: html_document
---

```{r load_modules, echo=FALSE, include=FALSE}
library(data.table)
library(purrr)
library(ggplot2)
library(cowplot)
library(ggrepel)
source("/bi/group/reik/Stephen/gastrulation/fread_gz.R")
```

```{r}
io <- list()
io$data_dir <- "/bi/scratch/Stephen_Clark/gastrulation_data"
io$base_dir <- "/bi/group/reik/Stephen/github/gastrulation"
io$sample_meta <- paste0(io$data_dir, "/sample_metadata.txt")
io$bb_files <- paste0(io$base_dir, "/acc/motifs/betabinomial_model/out")
io$bb_background_files <- paste0(io$base_dir, "/acc/motifs/betabinomial_model/out/background")
io$out_file <- paste0(io$base_dir, "/acc/motifs/betabinomial_model/out/all_stages_motifs.csv")


opts <- list()



```

```{r}
bb <- dir(io$bb_files, pattern="bb_all_stages", full=TRUE) %>%
  map(fread) %>%
  rbindlist()

# find the TF names 
tfs <- bb[, .(anno=unique(anno))] %>%
  .[, tf := gsub("cispb_1.02-|_1.02|jaspar2016-|jolma2013-|HOCOMOCOv10-|UniPROBE-|JASPAR_2014-|JASPAR_CORE-|_MOUSE|\\..*|\\-.*", "", anno)]


bb <- merge(bb, tfs, by="anno")

# order by mean rho
bb <- bb[, mean_rho := mean(rho), anno] %>%
  .[order(-rank(mean_rho))] %>%
  .[, anno := factor(anno, levels=unique(anno))]

annos <- bb[, unique(anno)] %>%
  .[1:20]

```

```{r}
ggplot(bb[anno%in%annos], aes(anno, rho, fill=anno)) +
  geom_boxplot(outlier.shape=NA) +
  geom_point(position=position_jitterdodge(jitter.width=0.2)) +
  coord_flip() +
  guides(fill=FALSE)
  
```

```{r}
ggplot(bb, aes(rho, mu)) +
  geom_point(alpha=0.2) +
  geom_smooth(method="lm", se=FALSE)
```


```{r}

bb <- bb[order(-rank(rho))] %>%
  .[, c("id", "rank") := .(factor(id, levels=unique(id)), .I)]

ggplot(bb, aes(rank, rho, label=tf)) +
  geom_point() +
  geom_text_repel(data=subset(bb, rank<20))
```

```{r}
dir.create(dirname(io$out_file), recursive=TRUE)
fwrite(bb, io$out_file)
```




