

```{r}
io$pdfdir2 <- paste0(io$pdfdir,"/dimensionality_reduction")
opts$width <- 4.5
opts$height <- 4
```

```{r}
theme_pub <- function() {
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank()
  )
}
```

<!-- Remove technical sources of variation -->

```{r}
p <- plot_factor(
  model.orig,
  factor = 8,
  color_by = "lineage10x_2", scale = F,
  add_violin = T, color_violin = T,
  dodge=T, dot_size=1, legend = F, rasterize = F
) + scale_color_manual(values=opts$colors) + scale_fill_manual(values=opts$colors)

print(p)
```

```{r}
plot_top_weights(model.orig, factors=10, view="RNA expression")
```

```{r}
# factors.to.keep <- factors(model)[!factors(model)%in% paste0("Factor ",c(3,7,8))]
# model.orig <- subset_factors(model, factors=factors.to.keep)
```

```{r}
# model.orig <- subset_factors(model, factors.to.keep)
model.orig <- model
```


<!-- Run UMAP/TSNE -->
```{r}
set.seed(42)

# model.orig <- run_umap(model.orig, n_neighbors=10)
model.orig <- run_tsne(model.orig, perplexity = 25)
```

<!-- Plot t-SNE and colour by lineage identity -->
```{r}
p <- plot_dimred(model.orig, groups = "all", method = "TSNE", color_by = "lineage10x_2", legend = F, dot_size = 1.75) + 
  scale_color_manual(values=opts$colors) +
  theme_pub()

# pdf(paste0(io$pdfdir2,"/tsne_by_lineage.pdf"), width=opts$width/1.5, height=opts$height*1.1, useDingbats = F)
print(p)
# dev.off()
```

```{r}
p <- plot_dimred(model.orig, groups = "all", method = "TSNE", color_by = "stage", legend = T, dot_size = 1.75) + 
  scale_color_brewer(palette = "Dark2") +
  theme_pub()

pdf(paste0(io$pdfdir2,"/tsne_by_stage.pdf"), width=opts$width/1.5, height=opts$height*1.1, useDingbats = F)
print(p)
dev.off()
```

<!-- Plot t-SNE and colour by factor values -->
```{r}
factor <- "Factor8"

p <- plot_dimred(model.orig, method = "TSNE", color_by = factor, legend = F, dot_size = 1.25) + 
  scale_color_distiller(palette = "PRGn") +
  theme_pub()

pdf(sprintf("%s/tsne_by_%s.pdf",io$pdfdir2,factor), width=opts$width/2, height=opts$height/2, useDingbats = F)
print(p)
dev.off()
```

<!-- Plot t-SNE and colour by specific features -->

<!-- Methylation -->
```{r}
# factor = "Factor1"
# view = "Enhancer accessibility"

factor = "Factor3"
view = "Enhancer accessibility"
```

Select features by loading
```{r}
# feature <- names(head(sort(get_weights(model.orig, views=view, factor=factor)[[1]][,1]), n=1))
```

Average across multiple features for plotting
```{r}
nfeatures = 50
top.features <- names(head(sort(get_weights(model.orig, views=view, factor=factor)[[1]][,1]), n=nfeatures))
# top.features <- names(tail(sort(get_weights(model.orig, views=view, factor=factor)[[1]][,1]), n=nfeatures))

acc <- unlist(lapply(model.orig@data[[view]], function(x) colMeans(x[top.features,], na.rm=T)))
acc <- 100*2**acc/(1+2**acc) # Convert M-values to B-values

# Cap values for better visualisation
acc[acc>80] <- 80
acc[acc<20] <- 20
```


```{r}
p <- plot_dimred(model.orig, 
  method = "TSNE",
  # color_by = feature, 
  color_by = acc,
  legend = T, 
  dot_size = 1.2, 
  show_missing = T, 
  alpha_missing = 0.05
) + theme_pub() + scale_color_distiller(palette = "Blues", direction=1, limits=c(20,80))

pdf(sprintf("%s/tsne_by_acc_%s.pdf",io$pdfdir2,factor), width=opts$width/2, height=opts$height/2, useDingbats = F)
print(p)
dev.off()
```




<!-- Methylation -->
```{r}
# factor = "Factor1"
# view = "Promoter methylation"

factor = "Factor3"
view = "Enhancer methylation"
```

Select features by loading
```{r}
# feature <- names(head(sort(get_weights(model.orig, views=view, factor=factor)[[1]][,1]), n=1))
```

Average across multiple features for plotting
```{r}
nfeatures = 50
# top.features <- names(head(sort(get_weights(model.orig, views=view, factor=factor)[[1]][,1]), n=nfeatures))
top.features <- names(tail(sort(get_weights(model.orig, views=view, factor=factor)[[1]][,1]), n=nfeatures))

met <- unlist(lapply(model.orig@data[[view]], function(x) colMeans(x[top.features,], na.rm=T)))
met <- 100*2**met/(1+2**met) # Convert M-values to B-values

# Cap values for better visualisation
met[met>80] <- 80
met[met<20] <- 20
```


```{r}
p <- plot_dimred(model.orig, 
  method = "TSNE",
  # color_by = feature, 
  color_by = met,
  legend = T, 
  dot_size = 1.2, 
  show_missing = T, 
  alpha_missing = 0.05
) + theme_pub() + scale_color_distiller(palette = "YlOrRd", direction=1, limits=c(10,90))

pdf(sprintf("%s/tsne_by_met_%s.pdf",io$pdfdir2,factor), width=opts$width/2, height=opts$height/2, useDingbats = F)
print(p)
dev.off()
```


