---
title: "Gastrulation: dimensionality reduction on accessibility data using putative accessibility peaks"

---

```{r load_modules, echo=FALSE, include=FALSE}
library(data.table)
library(purrr)
library(furrr)
library(ggplot2)
library(cowplot)
library(Rtsne)

options(future.globals.maxSize = 1000*1024^2)
```



```{r define_opts, echo=FALSE, include=FALSE}

## Define I/O ##
io <- list()
io$data_dir <- "/bi/scratch/Stephen_Clark/gastrulation_data"
io$base_dir <- "/bi/group/reik/Stephen/github/gastrulation"
io$sample.metadata <- paste0(io$data_dir, "/sample_metadata_scNMT.txt")
#io$in.data <- paste0(io$data_dir, "/acc/parsed/Christel")
io$in.data <- paste0(io$data_dir, "/acc/parsed/peaks")
io$tf_acc <- paste0(io$data_dir, "/acc/parsed/motifdb_100bp/filt_by_peaks")
io$out_dir <- "/bi/home/clarks/gastrulation/plots/tsne"


## Define options ##
opts <- list()

# Define which stage and lineages to look at 

opts$stage <- c("E4.5", "E5.5","E6.5", "E6.75", "E7.5")
opts$stage <- c("E7.5") 
opts$lineage <- c("EPI",  "PS", "Ectoderm", "Endoderm", "Mesoderm") # c("Mesoderm", "Ectoderm")#c("Ectoderm", "Endoderm", "Mesoderm")#
opts$KO_3b <- "not"
opts$file_regex <- "E4.5_all_100_by_50_top_0.05" # "12C|15C" ""E4.5_all_100_by_50_top_0.05""
opts$colour_by_cell_type <- "stage_lineage" # either "stage", "lineage" or "stage_lineage"
opts$colour_by_tf <- "Klf12"


# Define filtering options
opts$min.weight <- 1
opts$min.coverage <- 0


# filter on raw variance
opts$var_cutoff <- 0.5 # keep only the top xx fraction

opts$calc_loadings <- FALSE


# fun
fread_gz = function(filename, ...){
  paste("zcat", filename) %>%
    fread(...)
}

```

<!-- load metadata -->
```{r, include=FALSE}
meta <- fread(io$sample.metadata) %>%
  .[stage == "E6.75", stage := "E6.5"] %>%
  .[stage %in% opts$stage & lineage %in% opts$lineage & KO_3b %in% opts$KO_3b & pass_accQC]

cells <- meta[, sample]
```


```{r, include=FALSE}
files <- dir(io$in.data, pattern = opts$file_regex, full=TRUE)
# remove empty files
files <- files[file.size(files)>100]


```


<!-- Load, parse and filter data -->
```{r, include=FALSE}
# plan(multiprocess)


 data <- future_map(files, ~{
#data <- map(files, ~{
  dt <- fread_gz(.) %>%
    setkey(sample) %>%
    .[sample %in% cells]
  # filter by weight
  dt <- dt[N>=opts$min.weight]
  # filter variance
  var <- dt[, .(var=var(rate)), id] %>%
      .[!is.na(var)] %>%
      .[order(-rank(var))] %>%
      .[1:(.N*opts$var_cutoff), id]
  dt <- dt[id %in% var]
  if (dt[, .N]==0) return(NULL)
  
  total_cells <- dt[, length(unique(sample))]
  
  # filter by number of cells
  dt <- dt[, coverage := (.N)/total_cells, id] %>%
    .[coverage >= opts$min.coverage]
  
   if (dt[, .N]==0) return(NULL)
  
  #Convert beta value to M value 
  dt <- dt[,m:=log2(((rate)+0.01)/(100-(rate)+0.01))]
  
  # mean impute 
  dt <- dcast(dt, sample~id, value.var="m") %>%
    melt(id.vars="sample", variable.name="id", value.name="m") %>%
    .[, mean_m := mean(m, na.rm=TRUE), id] %>%
    .[is.na(m), m:=mean_m]
  
  # dcast to matrix
  
  dcast(dt, sample ~ id, value.var = "m") %>%
    as.data.frame() %>%
    tibble::column_to_rownames("sample") %>%
    as.matrix()
})

names(data) <- basename(files) %>% gsub(".tsv.gz", "", .)
  
  
  
 
  
 
  
 
```

<!-- t-SNE -->
```{r tsne}
tf_colours <- dir(io$tf_acc, pattern = ".tsv.gz", full = TRUE) %>%
  .[grep(opts$colour_by_tf, .)] %>%
  map(fread_gz) %>%
  rbindlist() %>%
  .[, .(tf = mean(rate)), sample] %>%
  setkey(sample)

meta <- fread(io$sample.metadata) %>%
  .[stage == "E6.75", stage := "E6.5"]

set.seed(999)

if (grepl("acc", io$in.data)) title <- "Accessibility"
if (grepl("met", io$in.data)) title <- "Methylation"

.x=data[[1]]
.y=names(data)[1]

 tsne <- future_map2(data, names(data), ~{
#tsne <- map2(data, names(data), ~{
  t <- Rtsne::Rtsne(.x, check_duplicates=FALSE, dims=3, perplexity = 30) 
  
  dir(io$tf_acc)

opts$colour_by_tf="nfix"

tf_colours <- dir(io$tf_acc, pattern = ".tsv.gz", full = TRUE) %>%
  .[grep(toupper(opts$colour_by_tf), toupper(.))] %>%
  map(fread_gz) %>%
  rbindlist() %>%
  .[, .(tf = mean(rate)), sample] %>%
  setkey(sample)
  
  dt <- as.data.table(t$Y) %>%
    .[, sample := rownames(.x)] %>%
    merge(meta[, .(sample, stage, lineage, stage_lineage = paste0(stage, "_", lineage))]) %>%
    merge(tf_colours, by = "sample")
  
  p1 <- ggplot(dt, aes(V1, V2, colour = get(opts$colour_by_cell_type))) +
    geom_point(size = 2) +
    xlab("t-SNE component 1") + 
    ylab("t-SNE component 2") +
    #guides(colour = FALSE)
    scale_colour_discrete(name = "RNA cluster") +
#     ggtitle(title)
    ggtitle("")#ggtitle(.y)
  
   p2 <- ggplot(dt, aes(V1, V3, colour = get(opts$colour_by_cell_type))) +
    geom_point(size = 2) +
    xlab("t-SNE component 1") + 
    ylab("t-SNE component 3") +
    scale_colour_discrete(name = "RNA cluster") +
    #     ggtitle(title)
 ggtitle("")# ggtitle(.y)



p3 <- ggplot(dt, aes(V1, V2, colour = tf)) +
    geom_point(size = 2) +
    xlab("t-SNE component 1") + 
    ylab("t-SNE component 2") +
    viridis::scale_colour_viridis(name = opts$colour_by_tf) +
    #scale_colour_continuous(name = opts$colour_by_tf) +
#     ggtitle(title)
  ggtitle("")#ggtitle(.y)
  
   p4 <- ggplot(dt, aes(V1, V3, colour = tf)) +
    geom_point(size = 2) +
    xlab("t-SNE component 1") + 
    ylab("t-SNE component 3") +
    viridis::scale_colour_viridis(name = opts$colour_by_tf) +
    #scale_colour_continuous(name = opts$colour_by_tf) +
    #     ggtitle(title)
  ggtitle("")#ggtitle(.y)
  
plot_grid(p1, p3, ncol=1)


  if (opts$calc_loadings){
    dim1_loadings <- as.data.frame(.x) %>%
      setDT(keep.rownames = "sample") %>%
      setkey(sample) %>%
      merge(dt[, .(sample, V1)], by = "sample") %>%
      melt(id.vars = c("sample", "V1"), variable.name = "id", value.name = "rate") %>%
      .[, cor(V1, rate), id] %>%
      .[order(-rank(abs(V1)))]
    
    return(list(p1, p3, p2, p4, dim1_loadings))
  }
  



  list(p1, p3, p2, p4)
    
  
})

tsne

files_1 <- paste0(io$out_dir, "/", names(tsne), "_", title, "_colour_by_", opts$colour_by,".pdf")

dir.create(io$out_dir, recursive = TRUE)
walk2(files_1, map(tsne, 1), save_plot, base_height = 8)
#save_plot(io$out_file, tsne)

 if (opts$calc_loadings){
   files_loadings <- paste0(io$out_dir, "/", names(tsne), "_", title, "_colour_by_", opts$colour_by,"_loadings.csv")
   walk2(map(tsne, 3), files_loadings, fwrite)
 }
```




