---
title: "Gastrulation: plot distributions of DNA methylation profiles for Zhang2018 data"
output:
  BiocStyle::html_document: 
    fig_width: 10
    fig_height: 8
---

```{r load_modules, echo=FALSE, include=FALSE}
library(data.table)
library(purrr)
library(ggplot2)
```

```{r define_opts, echo=FALSE, include=FALSE}
## I/O ##
io <- list()
io$data <- "/Users/ricard/data/Zhang_2017/methylation/GSE76505_STEM-seq_methylC_mCG/liftover/feature_level"
io$sample.metadata <- "/Users/ricard/data/Zhang_2017/sample_metadata.txt"
io$outdir <- "/Users/ricard/data/gastrulation/met/distributions"
  
## Options ##
opts <- list()

# Define which annotations to use
opts$annos <- c(
  "prom_2000_2000"="Promoters",
  "H3K27ac_distal_E7.5_Mes_500"="Mesoderm enhancers",
  "H3K27ac_distal_E7.5_Ect_500"="Ectoderm enhancers",
  "H3K27ac_distal_E7.5_End_500"="Endoderm enhancers"
)

# Define which samples to use
opts$stage_lineage <- c(
  "E4.0_Inner_cell_mass", 
  "E5.5_Epiblast", 
  "E6.5_Epiblast", 
  "E6.5_Primitive_Streak",
  "E7.5_Ectoderm", 
  "E7.5_Mesoderm", 
  "E7.5_Endoderm"
)
```

<!-- Load sample metadata -->
```{r}
sample_metadata <- fread(io$sample.metadata) %>% 
  .[,c("sample","stage","lineage")] %>%
  .[,stage_lineage:=paste(stage,lineage,sep="_")] %>%
  .[stage_lineage%in%opts$stage_lineage]
```

<!-- Load DNA methylation data  -->
```{r}
data <- lapply(names(opts$annos), function(n)
  fread(sprintf("%s/%s.tsv.gz",io$data,n))
) %>% rbindlist %>% setnames(c("sample","id","anno","rate"))
```

<!-- Parse data -->
```{r}
# Merge methylation data and sample metadata
data <- data %>% merge(sample_metadata, by="sample")
```

<!-- Plot histogram in pseudobulk stages -->
```{r}
data.pseudobulk <- data %>% 
  .[,.(rate=mean(rate)),by=c("stage","id","anno")] %>%
  .[,anno:=stringr::str_replace_all(anno,opts$annos)]
  
p <- gghistogram(data.pseudobulk, x = "rate", y="..density..", fill = "#F37A71", color = "black", alpha=0.75) +
  facet_wrap(~stage+anno, nrow=4, scales="fixed") +
  theme(
    axis.text.y = element_text(size=rel(0.9))
    )

pdf(sprintf("%s/Zhang2018_distributions_met.pdf",io$outdir), width=9, height=8)
print(p)
dev.off()
```
