---
title: "Gastrulation: Robustness analysis of MOFA factors"
output:
  BiocStyle::html_document: 
    toc: false
    fig_width: 10
    fig_height: 8
---

```{r load_modules, echo=FALSE, include=FALSE}
library(MOFA)
library(data.table)
library(purrr)
library(ggplot2)
library(pheatmap)
```

```{r}
compareFactors <- function(models, comparison = "all", ...) {
  
  # Sanity checks
  if(!is.list(models))
    stop("'models' has to be a list")
  if (!all(sapply(models, function (l) class(l)=="MOFAmodel")))
    stop("Each element of the the list 'models' has to be an instance of MOFAmodel")
  if (!comparison %in% c("all", "pairwise"))
    stop("'comparison' has to be either 'all' or 'pairwise'")
  
  # give generic names if no names present
  if(is.null(names(models))) names(models) <- paste("model", 1: length(models), sep="")
  
  # get latent factors
  LFs <- lapply(seq_along(models), function(modelidx){
    model <- models[[modelidx]]
    Z <- getFactors(model)
    Z
    })
  
  for (i in seq_along(LFs)) 
    colnames(LFs[[i]]) <- paste(names(models)[i], colnames(LFs[[i]]), sep="_")
  
  if (comparison=="all") {
    #get common samples between models
    commonSamples <- Reduce(intersect,lapply(LFs, rownames))
    if(is.null(commonSamples)) 
      stop("No common samples in all models for comparison")
    
    #subset LFs to common samples
    LFscommon <- Reduce(cbind, lapply(LFs, function(Z) {
      Z <- Z[commonSamples,, drop=FALSE]
      nonconst <- apply(Z,2,var, na.rm=TRUE) > 0
      if(sum(nonconst) < ncol(Z)) message("Removing ", sum(!nonconst), " constant factors from the comparison.")
      Z[, nonconst]
    })
      )
    # calculate correlation
    corLFs <- cor(LFscommon, use="complete.obs")
    
    # annotation by model
    modelAnnot <- data.frame(model = rep(names(models), times=sapply(LFs, ncol)))
    rownames(modelAnnot) <- colnames(LFscommon)
    
    #plot heatmap
    # if(is.null(main)) main <- "Absolute correlation between latent factors"
    if(length(unique(as.numeric(abs(corLFs))))>1){
    pheatmap(abs(corLFs),
             color = colorRampPalette(c("white",RColorBrewer::brewer.pal(9,name="YlOrRd")))(100),
             # annotation_row = modelAnnot,
             annotation_col = modelAnnot, ...
             )
    } else warning("No plot produced as correlations consist of only one value")
  }
}
```

<!-- Define settings -->
```{r}
io <- list()
io$outdir <- "/Users/ricard/data/gastrulation_norsync_stuff/metaccrna/mofa/E7.5/hdf5"

opts <- list()
opts$ntrials <- 10
```

<!-- Load precomputed models -->
```{r}
MOFAlist <- list()
for (i in 1:opts$ntrials) {
  outfile <- sprintf("%s/model_%d.hdf5",io$outdir,i)
  MOFAlist[[i]] <- loadModel(outfile)
}
```

<!-- Subset active factors -->
```{r}
for (i in 1:opts$ntrials) {
  r2 <- calculateVarianceExplained(MOFAlist[[i]])$R2PerFactor
  factors <- r2[,"rna"]>0.005
  MOFAlist[[i]] <- subsetFactors(MOFAlist[[i]], which(factors))
}
```

<!-- Assess robustness of factors -->
```{r}
# pdf(paste0(io$outdir,"/robustness.pdf"), height=7, width=8.5)
compareFactors(MOFAlist, show_rownames=F, show_colnames=F)
# dev.off()
```

<!-- Select model with the highest ELBO -->
```{r}
compareModels(MOFAlist)
```