---
title: "Gastrulation: pseudotime estimation using destiny"
output: 
  BiocStyle::html_document: 
  fig_width: 10
fig_height: 8
---

```{r load_modules, echo=FALSE, include=FALSE}
library(data.table)
library(purrr)
library(scater)
library(ggplot2)
library(destiny)
library(scran)
```

```{r}

## I/O ##
io <- list()
io$basedir <- "/Users/ricard/data/gastrulation"
io$in.sample_metadata <- paste0(io$basedir,"/sample_metadata.txt")
io$rna.infile <- paste(io$basedir,"rna/parsed/SingleCellExperiment.rds",sep="/")
io$outdir <- "/Users/ricard/gastrulation/metaccrna/mofa/primitive_streak/endoderm"

## Options ##
opts <- list()

opts$stage_lineage10x <- c(

  # E5.5
  "E5.5_Epiblast",

  # E6.5
  "E6.5_Epiblast",
  "E6.5_Primitive_Streak",
  # "E6.5_Mesoderm",

  # E7.5 
  # "E7.5_Epiblast",
  "E7.5_Primitive_Streak",
  "E7.5_Endoderm"
  # "E7.5_Mesoderm"
)

opts$colors <- c(
  Epiblast="#63B8FF",
  Mesoderm="#CD3278",
  Primitive_Streak="#F4A460",
  Endoderm="#43CD80"
)


opts$cells <- fread(io$in.sample_metadata) %>% 
  .[,stage_lineage:=paste(stage,lineage10x_2,sep="_")] %>% 
  .[pass_rnaQC==T & stage_lineage%in%opts$stage_lineage, id_rna]
```

```{r}
sample_metadata <- fread(io$in.sample_metadata) %>% .[id_rna%in%opts$cells] %>%
  .[,stage_lineage:=paste(stage,lineage10x_2,sep="_")]
```

```{r load_data, echo=FALSE}
sce <- readRDS(io$rna.infile) %>% .[,opts$cells]
sce$lineage <- sample_metadata$lineage10x_2
sce$stage_lineage <- sample_metadata$stage_lineage
```

<!-- Identify highly variable genes -->
```{r}
# Normalize
sce_filt <- scater::normalize(sce)

# Temporarily remove the lowly expressed genes
sce_filt <- sce_filt[!(rowMeans(counts(sce_filt)) <= 1 | rowData(sce_filt)$pct_dropout_by_counts > 90),]
  
# Fit a mean-dependent trend
var.fit <- trendVar(sce_filt, method="loess", use.spikes=FALSE)

# Decompose the gene-specific variance into biological and technical components
var.out <- decomposeVar(sce_filt, var.fit)
var.out <- var.out[var.out$bio>0,]
var.out[is.nan(var.out$p.value),] <- NA

# Store overdispersion information in rowData
# rowData(sce)$techVar <- var.out$tech
# rowData(sce)$bioVar <- var.out$bio
# rowData(sce)$totalVar <- var.out$total

```

<!-- Filter expression data -->
```{r}
N <- 1500

# Keep N more variable genes
# genes <- names(tail(sort(apply(exprs(sce),1,var)), n=N))

# Keep N more overdispersed genes
# genes <- rownames(head(rowData(sce)[order(rowData(sce)$bioVar, decreasing = T),],n=N))
genes <- rownames(head(var.out[order(var.out$bio, decreasing = T),],n=N))
sce_filt <- sce_filt[rownames(sce_filt) %in% genes]
```

<!-- Regress out covariates -->
```{r}
data <- as.matrix(t(logcounts(sce_filt)))

stage <- as.factor(sce_filt$stage)
ngenes <- rowMeans(data)

# data_regressed <- future_apply(data, 2, function(x) {
data_regressed <- apply(data, 2, function(x) {
  lm.out <- lm(formula=expr~ngenes, data=data.frame(expr=x, ngenes=ngenes));
  residuals <- lm.out[["residuals"]]
}) %>% t

logcounts(sce_filt) <- data_regressed
```

<!-- Fit DiffusionMap -->
```{r}
set.seed(42)
dm <- DiffusionMap(t(logcounts(sce_filt)))
```

<!-- Fit PCA -->
```{r}
# Z.out <- irlba::prcomp_irlba(x = t(data_regressed), n = 3)$x
# 
# to.plot <- Z.out %>% as.data.table %>% .[,id_rna:=colnames(sce_filt)] %>%
#     merge(sample_metadata, by="id_rna")
# 
# p <- ggplot(to.plot, aes(PC1, PC2)) +
#   geom_point(aes(color=lineage10x_2, shape=stage), alpha=1.0, size=1.0) +
#   # geom_point(aes(color=cdr, shape=stage_lineage), alpha=0.7, size=2.0) +
#   labs(x="Diffusion component 1", y="Diffusion component 2") +
#   theme(
#     plot.title = element_text(size=20, hjust=0.5),
#     axis.title.y = element_text(colour="black", size=16, margin=margin(0,15,0,0)),
#     axis.title.x = element_text(colour="black", size=16, margin=margin(15,0,0,0)),
#     axis.text.x = element_text(colour="black",size=rel(1.4)),
#     axis.text.y = element_text(colour="black",size=rel(1.4)),
#     axis.line = element_line(colour="black", size=rel(0.9)),
#     axis.ticks = element_line(colour="black", size=rel(1.0)),
#     panel.background = element_blank(),
#     panel.grid = element_blank(),
#     legend.position="right",
#     legend.text=element_text(size=15),
#     legend.key = element_blank(),
#     legend.title=element_blank(),
#     legend.background=element_blank(),
#     panel.border = element_blank()
#   )
# print(p)
```

```{r}
tmp <- data.table(
  sample = colnames(sce_filt),
  stage = sce_filt$stage,
  lineage = sce_filt$lineage,
  stage_lineage = sce_filt$stage_lineage,
  x = eigenvectors(dm)[,1],
  y = eigenvectors(dm)[,2],
  z = eigenvectors(dm)[,3]
)
```

<!-- Load pre-computed pseudotime -->
```{r}
tmp <- fread(paste0(io$outdir,"/destiny_endoderm.tsv"))
```

<!-- Calculate ranks -->
```{r}
tmp <- tmp %>% 
  setorder(x) %>% .[,rank_x:=1:.N] %>%
  setorder(y) %>% .[,rank_y:=1:.N] %>%
  setorder(z) %>% .[,rank_z:=1:.N] %>%
  .[!stage_lineage=="E7.5_Epiblast"]
```

```{r}
# rownames(sce) <- rowData(sce)$symbol
# foo <- data.table(
#   sample = colnames(sce),
#   gene = exprs(sce["Sox17",])[1,]
#   )
# 
# tmp <- tmp %>% merge(foo)
```

<!-- Scatter plot of pairs of diffusion components -->
```{r}
p <- ggplot(tmp, aes(rank_x,rank_z)) +
  geom_point(aes(color=lineage), alpha=1.0, size=1.0) +
  geom_rug(aes(color=lineage), sides="b") + 
  scale_color_manual(values=opts$colors) +
  labs(x="Diffusion component 1", y="Diffusion component 2") +
  theme_classic() + theme(
    axis.title = element_text(colour="black", size=rel(1.2)),
    # axis.text = element_text(colour="black",size=rel(1.0)),
    axis.ticks = element_blank(),
    axis.text = element_blank(),
    legend.position="none"
  )
print(p)

pdf(paste0(io$outdir,"/destiny_endoderm_v2.pdf"), useDingbats = F, width=4.75, height=4.25)
print(p)
dev.off()
```

<!-- Remove outliers -->
```{r}
# tmp <- tmp[!(x>(0.008) & lineage=="Epiblast")]
```

<!-- Save results -->
```{r}
tmp <- data.frame(
  id_rna=colnames(sce), 
  DC1=round(dm$DC1,4)
)
write.table(tmp, paste0(io$outdir,"/destiny_endoderm.tsv"), quote=F, sep="\t", row.names = F, col.names = T)
```