  ---
title: "Gastrulation scNMT-seq: correlation per gene (across cells) between RNA expression and chromatin accessibility"
output: 
  BiocStyle::html_document: 
    fig_width: 12
    fig_height: 8
---

```{r echo=FALSE, include=FALSE}
suppressPackageStartupMessages(library(SingleCellExperiment))
suppressPackageStartupMessages(library(purrr))
suppressPackageStartupMessages(library(weights))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(grid))
suppressPackageStartupMessages(library(gridExtra))
suppressPackageStartupMessages(library(cowplot))
suppressPackageStartupMessages(library(data.table))
```

<!-- Define functions -->
```{r echo=FALSE, include=FALSE}
source("/Users/ricard/gastrulation/accrna/cor/utils.R")
```

<!-- Define I/O and options -->
```{r echo=TRUE, include=FALSE}

## I/O ##
io   <- list()
io$basedir   <- "/Users/ricard/data/gastrulation"
io$sample.metadata <- paste0(io$basedir,"/sample_metadata.txt")
io$annos_dir  <- paste0(io$basedir, "/features/genomic_contexts")
io$rna_file   <- paste0(io$basedir, "/rna/SingleCellExperiment.rds")
io$acc_dir   <- paste0(io$basedir, "/acc/feature_level")
io$gene_metadata <- "/Users/ricard/data/ensembl/mouse/v87/BioMart/mRNA/Mmusculus_genes_BioMart.87.txt"
io$outdir <- paste0(io$basedir,"/accrna/cor")

## Options ##
opts <- list()

# Filtering parameters
opts$min.GpCs <- 5     # Minimum number of GpCs per feature
opts$min.cells <- 50   # Minimum number of cells per feature
opts$max.genes <- 5000  # Top N most variable genes and features

# Multiple testing correction options
opts$threshold_fdr  <- 0.1

# Correlation type options
opts$method <- "pearson"      # correlation type (see ?cor)
opts$weight <- FALSE          # weighted correlation (see ?wtd.cor) 

# Permutation test options
opts$permutation <- TRUE   # do permutation test?
opts$n_perms <- 10          # Number of random permutations

# Define genomic contexts
opts$annos <- c(
  "prom_2000_2000"="Promoters"
)

# Define stage and lineages
opts$stage_lineage <- c(

  # E4.5
  "E4.5_Epiblast",

  # E5.5
  "E5.5_Epiblast",
  
  # E6.5
  "E6.5_Epiblast",
  "E6.5_Primitive_Streak",
  
  # E7.5
  "E7.5_Epiblast",
  "E7.5_Ectoderm",
  "E7.5_Primitive_Streak",
  "E7.5_Endoderm",
  "E7.5_Mesoderm"
)

# Define which cells to use
tmp <- fread(io$sample.metadata) %>% 
  .[,stage_lineage:=paste(stage,lineage10x_2,sep="_")] %>%
  .[pass_accQC==T & pass_rnaQC==T & stage_lineage%in%opts$stage_lineage] 
opts$rna.cells <- tmp$id_rna
opts$acc.cells <- tmp$id_acc
```

<!-- Load sample metadata -->
```{r}
sample_metadata <- fread(io$sample.metadata) %>% 
  .[,c("sample","id_rna","id_acc","stage","lineage10x_2")] %>%
  .[,stage_lineage:=paste(stage,lineage10x_2,sep="_")] %>%
  .[sample%in%tmp$sample]
```

<!-- Load RNA data -->
```{r load_rna, echo=FALSE, include=FALSE}
# Load expression as SCE object
sce <- readRDS(file=io$rna_file)[,opts$rna.cells]

# Create data.table
rna_dt <- exprs(sce) %>% t %>% as.data.table(keep.rownames="id_rna") %>% 
  melt(id.vars="id_rna", value.name="expr", variable.name="id") %>%
  merge(sample_metadata[,c("sample","id_rna")]) %>%
  merge(rowData(sce) %>% as.data.frame(row.names=rownames(sce)) %>% 
          tibble::rownames_to_column("ens_id") %>%
          .[,c("symbol","ens_id")] %>% as.data.table %>% setnames(c("ens_id","symbol"),c("id","gene")),
        by=c("id")
        )
```

<!-- Filter RNA data -->
```{r}
# Remove genes with little variability
rna_dt <- rna_dt[,var:=var(expr), by="gene"] %>% .[var>0.1] %>% .[,var:=NULL]
```

<!-- Load accessibility data -->
```{r load_acc, echo=FALSE, include=FALSE}
acc_dt <- lapply(names(opts$annos), function(n) {
  fread(sprintf("%s/%s.tsv.gz",io$acc_dir,n)) %>% .[V1%in%opts$acc.cells]
}) %>% rbindlist %>% setnames(c("sample","id","anno","Nacc","N","rate"))
```

<!-- Filter accessibility data -->
```{r load_met, echo=FALSE, include=FALSE}
# Filter by mininum number of GpCs per feature
acc_dt <- acc_dt[N>=opts$min.GpCs]

# Filter by coverage
acc_dt <- acc_dt %>% .[,N:=.N, by=c("id","anno")] %>% .[N>=opts$min.cells] %>% .[,N:=NULL]

# Filter by variance
acc_dt <- acc_dt[,var:=var(rate), by=c("id","anno")] %>% .[var>0] %>% .[,var:=NULL]
```

<!-- Load gene metadata -->
```{r load_genomiccontexts}
gene_metadata <- fread(io$gene_metadata) %>% 
  setnames(c("ens_id","symbol"),c("id","gene")) %>% 
  .[,chr:=stringr::str_replace_all(chr,"chr","")]
```

<!-- Merge chromatin accessibility and RNA expression data -->
```{r}
acc_dt <- acc_dt %>% merge(gene_metadata[,c("id","gene")], by="id")

accrna_dt <- merge(
  acc_dt, 
  rna_dt[,c("sample","gene","expr")], 
  by = c("sample","gene")
)
```

<!-- Filter data -->
```{r filter_across_samples, echo=FALSE}
# Filter by variance
accrna_dt <- accrna_dt[,var:=var(rate), by=c("id","anno","gene")] %>% .[var>0] %>% .[,var:=NULL]
accrna_dt <- accrna_dt[,var:=var(expr), by=c("id","anno","gene")] %>% .[var>0] %>% .[,var:=NULL]

# Extract top N most variable genes
keep_hv_genes <- accrna_dt %>% split(.$anno) %>% 
  map(~ .[,.(var=var(expr)), by=c("gene","id")] %>% setorder(-var) %>% head(n=opts$max.genes) %>% .[,gene_id:=paste(gene,id,sep="_")] %>% .$gene_id %>% as.character())
accrna_dt <- accrna_dt %>% .[,gene_id:=paste(gene,id,sep="_")] %>% split(.$anno) %>%
  map2(.,names(.), function(x,y) x[gene_id %in% keep_hv_genes[[y]]]) %>% rbindlist %>% .[,gene_id:=NULL]

accrna_dt <- accrna_dt
```

<!-- Compute correlations and do multiple testing correction -->

```{r}
if (opts$weight) {
  cor <- accrna_dt[, wtd.cor(rate, expr, N)[,c("correlation","t.value","p.value")], by = c("id","gene","anno")]
} else {
  cor <- accrna_dt[, .(V1 = unlist(cor.test(rate, expr, method = opts$method)[c("estimate", "statistic", "p.value")])), by = c("id","gene","anno")]
}

# Compute adjusted p-values (both FDR and Bonferroni)
cor <- cor %>% .[, para := rep(c("r","t","p"), .N/3)] %>% data.table::dcast(id+gene+anno ~ para, value.var = "V1") %>%
      .[, c("padj_fdr", "padj_bonf") := list(p.adjust(p, method="fdr"), p.adjust(p, method="bonferroni")), by = "anno"] %>%
      .[, c("log_padj_fdr","log_padj_bonf") := list(-log10(padj_fdr), -log10(padj_bonf))] %>%
      .[, sig := padj_fdr <= opts$threshold_fdr] %>%  setorder(padj_fdr)
```

```{r}
cor[,sum(sig),by="anno"]
```

<!-- Save results -->
```{r}
# fwrite(cor, paste0(io$outdir,"/accrna_cor_promoters.txt"), quote=F, sep="\t")
# cor <- fread(paste0(io$outdir,"/accrna_cor_promoters.txt"))
```

<!-- Run permutation test for the correlation across samples -->
```{r perm_cor_rate, echo=FALSE, include=FALSE}
if (opts$permutation) {
  pp_vals <- vector(mode = "numeric", length = length(cor$p))
  for (k in 1:opts$n_perms){
    print(k)
    accrna_dt_perm <- copy(accrna_dt)
    
    # Permute gene expression levels
    accrna_dt_perm <- accrna_dt_perm[, expr:=sample(expr), by = c("id","gene","anno")]
    
    # Permute accessibility levels
    accrna_dt_perm <- accrna_dt_perm[, rate:=sample(rate), by = c("id","gene","anno")]
    
    # Compute correlation across samples
    if (opts$weight) {
      cor_perm <- accrna_dt_perm[, .(p = wtd.cor(rate, expr, weight)[, c("p.value")]), by = c("id", "gene", "anno")]
    } else {
      cor_perm <- accrna_dt_perm[, .(p = cor.test(rate, expr, method=opts$method)[["p.value"]]), by = c("id","gene","anno")]
    }
    
    # For each annotation sort by p-value and store the permuted p-values
    cor_perm <- cor_perm %>% split(.$anno) %>% map(~ .[,.(anno = anno, p = sort(p))]) %>% rbindlist
    pp_vals <- pp_vals + cor_perm$p
  }
  # Compute the average p-values
  pp_vals <- pp_vals / opts$n_perms
  # Store them in a data.table for later analysis
  cor_perm <- cor_perm[, p := pp_vals]
}
```

<!-- Volcano plot of p-values against Pearson's r and QQ-plot of p-values -->
```{r, echo=FALSE}
if (opts$permutation) {
  pp <- qq <- list()
  for (n in unique(cor$anno)) {
    
    # Compute positive and negative hits in terms of correlation
    negative_hits <- cor[anno==n & sig==TRUE & r<0,id]
    positive_hits <- cor[anno==n & sig==TRUE & r>0,id]
    all <- nrow(cor[anno == n,])
    
    # Generate volcano plot  
    tmp <- cor
    tmp[log_padj_fdr>8,log_padj_fdr:=8]
    pp[[n]] <- gg_volcano_plot(tmp[anno == n,], title = "", label=15)
    
    # Generate permutation plot
    qq[[n]] <- gg_qqplot(cor[anno == n, ], cor_perm[anno == n]$p, title = "")
    
    # Combine and save
    # pdf(file=paste0(io$outdir,"/pdf/volcano_", n, ".pdf"), width = 13, height = 5.5, useDingbats = FALSE)
    grid.arrange(pp[[n]], qq[[n]], ncol=2, top = textGrob(n, gp=gpar(fontsize=29, fontface = "bold")), newpage = TRUE)
    # dev.off()
  }
}
```

