---
title: "Boxplots of lineage specific sites"
author: "Stephen Clark"
date: "30 May 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(data.table)
library(purrr)
library(furrr)
library(dplyr)
library(tibble)
library(ggplot2)
library(cowplot)


# in/out
io <- list()
io$data_dir <- "/bi/scratch/Stephen_Clark/gastrulation_data"
io$code_dir <- "/bi/group/reik/Stephen/github/gastrulation"
io$sample_meta <- paste0(io$data_dir, "/sample_metadata_scNMT.txt")
# io$acc_data <- paste0(io$data_dir, "/acc/parsed/peaks/all_Peaks_E4.5_all_100_by_50_top_0.05_filt_100_merged_overlap.tsv.gz")
# io$sig_loci <- paste0(io$data_dir, "/acc/output/peaks/diff_acc")

#  io$acc_data <- paste0(io$data_dir, "/acc/parsed/unbiased_sig_acc/all_100win_step50.tsv.gz")
#  io$sig_loci <- paste0(io$data_dir, "/features/sjc/unbiased_sig_acc/")
io$acc_data <- paste0(io$data_dir, "/acc/parsed/acc_windows/sig_sites")

# options
opts <- list()
opts$stages <- c("E4.5", "E5.5", "E6.5", "E7.5")
opts$lineages <- c("EPI", "PS", "Ectoderm", "Mesoderm", "Endoderm")
opts$KO_3b <- "not"
opts$min_weight <- 1
opts$high_or_low_sites <- "high" # select sites which were significantly high/low in a given lineage (defualt = high)


# functions
source("/bi/home/clarks/fread_gz.R")

```


```{r}

loci <- dir(io$sig_loci, full = TRUE, pattern = ".csv") %>%
  map(fread) %>%
  setNames(dir(io$sig_loci, pattern = ".csv") %>% gsub(".csv", "", .))

if (opts$high_or_low_sites == "low") {
  loci <- map(loci, ~.[mean_y > mean_x, id])
} else {
  loci <- map(loci, ~.[mean_x > mean_y, id])
}

  
  
meta <- fread(io$sample_meta) %>% 
     .[stage %in% opts$stage & 
         lineage %in% opts$lineage & 
         KO_3b %in% opts$KO_3b & 
         pass_accQC == TRUE ] %>%
  .[, lineage := factor(lineage, levels = opts$lineages)]


cells <- meta[, sample]

acc <- fread_gz(io$acc_data) %>% 
  setkey(sample) %>% 
  .[sample %in% cells] %>%
  merge(meta[, .(sample, stage, lineage)], by = "sample") %>%
  .[N >= opts$min_weight] %>%
  setkey(id)

acc <- map(loci, ~acc[id %in% .])
```



Boxplot of the rates at each loci.  





```{r}
mean_id <- map(acc, ~.[, .(rate = mean(rate)), .(id, stage, lineage)])

map2(mean_id, names(mean_id), ~{
  title <- paste0("Accessibility at ", .y, " high sites")
  ggplot(.x, aes(stage, rate, fill = lineage)) +
    geom_boxplot(outlier.shape=NA) +
    geom_point(alpha = 0.25 ,position = position_jitterdodge(jitter.width = 0.03)) +
    xlab("") +
    ylab("Accessibility rate (mean accross cells)") +
    ggtitle(title) +
    ylim(0, 100)
})

# mean_id_lin <- c("E4.5_EPI", "E5.5_EPI")
# mean_id_lin <-  list(mesoderm = c(mean_id_lin, "E6.5_PS", "E7.5_Mesoderm"),
#                      endoderm = c(mean_id_lin, "E6.5_PS", "E7.5_Endoderm"),
#                      ectoderm = c(mean_id_lin, "E6.5_EPI", "E7.5_Ecotderm")) %>%
#   map(~rbindlist(mean_id)[paste(stage, lineage, sep = "_") %in% .])
# 
# map2(mean_id_lin, names(mean_id_lin), ~{
#   title <- paste0("Accessibility at of ", .y, " cells at significant sites")
#   ggplot(.x, aes(stage, rate, colour = id, group = id)) +
#     geom_line() +
#     #geom_point(alpha = 0.25 ,position = position_jitterdodge(jitter.width = 0.03)) +
#     xlab("") +
#     ylab("Accessibility rate (mean accross cells)") +
#     ggtitle(title) +
#     guides(colour = FALSE)
# })

```

Plot the mean rate for each cell. Can we see lineages in earlier stages?  


```{r}
mean_cell <- map(acc, ~.[, .(rate = mean(rate)), .(sample, stage, lineage)])


map2(mean_cell, names(acc), ~{
  title <- paste0("Accessibility at ", .y, " high sites")
  ggplot(.x, aes(stage, rate, fill = lineage)) +
    geom_boxplot(outlier.shape=NA) +
    geom_point(alpha = 0.25 ,position = position_jitterdodge(jitter.width = 0.03)) +
    xlab("") +
    ylab("Accessibility rate (mean accross sites)") +
    ggtitle(title) +
    ylim(0, 100)
})

map2(mean_cell, names(acc), ~{
  title <- paste0("Accessibility at ", .y, " high sites")
  ggplot(.x, aes(stage, rate, colour = lineage)) +
    geom_point(alpha = 0.9 ,position = position_jitterdodge(jitter.width = 0.25)) +
    xlab("") +
    ylab("Accessibility rate (mean accross sites)") +
    ggtitle(title) +
    ylim(0, 100)
})


```





```{r}
# library(pheatmap)
# 
# heat <- map(acc, ~.[, max := length(unique(sample))] %>% .[, ncell := .N/max, id] %>% .[ncell >= 0.55]) %>%
#   map(dcast, id~sample, value.var = "rate") %>%
#   map(~setDF(.) %>% tibble::column_to_rownames("id") %>% as.matrix)
# 
# anno_col <- meta[, .(sample, stage, lineage)] %>%
#   setDF() %>%
#   column_to_rownames("sample")
# .=heat[[2]]
# pheatmap(., annotation_col = anno_col, show_rownames = FALSE, show_colnames = FALSE)

```


