---
title: "Motif enrichment"
author: "Stephen Clark"
date: "06/18/2018"
output: html_document
---


```{r load_modules, echo=FALSE, include=FALSE}
library(data.table)
library(purrr)
library(furrr)
library(MotifDb)
library(Biostrings)
library(BSgenome.Mmusculus.UCSC.mm10)

```



```{r define_opts, echo=FALSE, include=FALSE}

## Define I/O ##
io <- list()
io$data_dir <- "/bi/scratch/Stephen_Clark/gastrulation_data"
io$sample.metadata <- paste0(io$data_dir, "/sample_metadata_scNMT.txt")
io$anno_dir <- paste0(io$data_dir, "/features/sjc/peaks")



## Define options ##
opts <- list()


```


```{r load_sequences_from_peaks}
plan(multiprocess)

annos <- dir(io$anno_dir, pattern = ".bed", full = TRUE) %>% 
  future_map(fread) %>% 
  map(~.[, chr := paste0("chr", chr)])

# testing....

annos <- map(annos[1:2], ~.[1:1e3])

mm10 <- BSgenome.Mmusculus.UCSC.mm10



sequence_list <- future_map(annos, ~{
  list(top = getSeq(mm10, .[, chr], .[, start], .[, end], strand = "+"),
       bottom = getSeq(mm10, .[, chr], .[, start], .[, end], strand = "-"))
}) 
top_seq <- map(sequence_list, ~.$top) %>% purrr::reduce(c)
bot_seq <- map(sequence_list, ~.$bottom) %>% purrr::reduce(c)

annos <- bind_rows(annos)



# load all PWMs in mouse genome
pwm <- query(MotifDb, "mmusculus")
# testing...
#pwm <- pwm[1:2]
pwm_names <- gsub("Mmusculus-", "", names(pwm))


motifs_anno <- map(seq_along(pwm), function(i) {
  future_map(1:nrow(annos), ~matchPWM(pwm[[i]], top_seq[[.]], with.score = FALSE)) %>%
    future_map(~as.data.frame(.) %>% nrow %>% data.table(hits = .)) %>%
    bind_rows() %>%
    cbind(annos[, .(id, anno)]) %>%
    .[, .(hits = sum(hits)), anno] %>%
    setnames("hits", pwm_names[[i]]) %>%
    setkey(anno) 
}) %>%
  purrr::reduce(merge)



annos <- annos[, len := end - start] %>%
  .[order(chr)]

background <- annos[, .(.N, min = min(start), max = max(end)), chr] %>%
  .[, .(start = runif(N, min, max)), chr] %>%
  cbind(annos[, .(id, anno, len)]) %>%
  .[, end := start + len] %>%
  .[, len := NULL]

sequence_list <- future_map(split(background, by = "anno"), ~{
  list(top = getSeq(mm10, .[, chr], .[, start], .[, end], strand = "+"),
       bottom = getSeq(mm10, .[, chr], .[, start], .[, end], strand = "-"))
}) 
top_seq <- map(sequence_list, ~.$top) %>% purrr::reduce(c)
bot_seq <- map(sequence_list, ~.$bottom) %>% purrr::reduce(c)


motifs_back <- map(seq_along(pwm), function(i) {
  future_map(1:nrow(annos), ~matchPWM(pwm[[i]], top_seq[[.]], with.score = FALSE)) %>%
    future_map(~as.data.frame(.) %>% nrow %>% data.table(hits = .)) %>%
    bind_rows() %>%
    cbind(annos[, .(id, anno)]) %>%
    .[, .(hits = sum(hits)), anno] %>%
    setnames("hits", pwm_names[[i]]) %>%
    setkey(anno) 
}) %>%
  purrr::reduce(merge)


```




