---
title: "Gastrulation: dimensionality reduction on accessibility data using putative accessibility peaks"

---

```{r load_modules, echo=FALSE, include=FALSE}
library(data.table)
library(purrr)
library(furrr)
library(ggplot2)
library(cowplot)
library(Rtsne)

```



```{r define_opts, echo=FALSE, include=FALSE}

## Define I/O ##
io <- list()
io$data_dir <- "/bi/scratch/Stephen_Clark/gastrulation_data"
io$base_dir <- "/bi/group/reik/Stephen/github/gastrulation"
io$sample.metadata <- paste0(io$data_dir, "/sample_metadata_scNMT.txt")
io$in.data <- paste0(io$data_dir, "/acc/parsed/peaks")


## Define options ##
opts <- list()

# Define which stage and lineages to look at 

opts$stage <- c("E4.5", "E5.5","E6.5","E7.5")
opts$stage <- c("E6.5", "E6.75")
opts$lineage <- "PS"#c("EPI", "PE", "VE", "PS", "Ectoderm", "Endoderm", "Mesoderm")
opts$KO_3b <- "not"
opts$file_regex <- "100_by_50_top_0.05"


# Define filtering options
opts$min.weight <- 1
opts$min.coverage <- 0


# filter on raw variance
opts$var_cutoff <- 0.5 # keep only the top xx fraction



# fun

fread_gz = function(filename, ...){
  if (!file.exists(filename)) stop(paste0(filename, " not found"))
  
  f = file(filename)
  filetype = summary(f)$class
  close.connection(f)
  if (filetype != "file" && filetype != "gzfile") stop("File must be gzip or not compressed")
  if (filetype == "file") {
    file = fread(filename, ...)
  } else {
    BFR.SIZE <- 1e7
    dest_file <- tempfile()
    # Setup input and output connections
    inn <- gzfile(filename, open = "rb")
    out <- file(description = dest_file, open = "wb")
    # Process
    nbytes <- 0
    repeat {
      bfr <- readBin(inn, what=raw(0L), size=1L, n=BFR.SIZE)
      n <- length(bfr)
      if (n == 0L) break;
      nbytes <- nbytes + n
      writeBin(bfr, con=out, size=1L)
      bfr <- NULL  # Not needed anymore
    }
    close(inn)
    close(out)
    file = fread(dest_file, ...)
    file.remove(dest_file)
    
  }
  file    
}
```

<!-- load metadata -->
```{r, include=FALSE}
meta <- fread(io$sample.metadata) %>%
  .[stage %in% opts$stage & lineage %in% opts$lineage & KO_3b %in% opts$KO_3b & pass_accQC]

cells <- meta[, sample]
```


```{r, include=FALSE}
files <- dir(io$in.data, pattern = opts$file_regex, full=TRUE)
# remove empty files
files <- files[file.size(files)>100]


```


<!-- Load, parse and filter data -->
```{r, include=FALSE}
# plan(multiprocess)


# data <- future_map(files, ~{
data <- map(files, ~{
  dt <- fread_gz(.) %>%
    setkey(sample) %>%
    .[sample %in% cells]
  # filter by weight
  dt <- dt[N>=opts$min.weight]
  # filter variance
  var <- dt[, .(var=var(rate)), id] %>%
      .[!is.na(var)] %>%
      .[order(-rank(var))] %>%
      .[1:(.N*opts$var_cutoff), id]
  dt <- dt[id %in% var]
  if (dt[, .N]==0) return(NULL)
  
  total_cells <- dt[, length(unique(sample))]
  
  # filter by number of cells
  dt <- dt[, coverage := (.N)/total_cells, id] %>%
    .[coverage >= opts$min.coverage]
  
   if (dt[, .N]==0) return(NULL)
  
  #Convert beta value to M value 
  dt <- dt[,m:=log2(((rate)+0.01)/(100-(rate)+0.01))]
  
  # mean impute 
  dt <- dcast(dt, sample~id, value.var="m") %>%
    melt(id.vars="sample", variable.name="id", value.name="m") %>%
    .[, mean_m := mean(m, na.rm=TRUE), id] %>%
    .[is.na(m), m:=mean_m]
  
  # dcast to matrix
  
  dcast(dt, sample ~ id, value.var = "m") %>%
    as.data.frame() %>%
    tibble::column_to_rownames("sample") %>%
    as.matrix()
})

names(data) <- basename(files) %>% gsub(".tsv.gz", "", .)
  
  
  
 
  
 
  
 
```

<!-- t-SNE -->
```{r tsne}
meta <- fread(io$sample.metadata)

# tsne <- future_map2(data, names(data), ~{
tsne <- map2(data, names(data), ~{
  dt <- Rtsne::Rtsne(.x, check_duplicates=FALSE, pca=TRUE, perplexity=15, theta=0.5, dims=3) %>%
    .$Y %>%
    as.data.table() %>%
    .[, sample := rownames(.x)] %>%
    merge(meta[, .(sample, stage_lineage = paste0(stage, "_", lineage))])
  
  p1 <- ggplot(dt, aes(V1, V2, colour = stage_lineage)) +
    geom_point(size = 2) +
    xlab("t-SNE component 1") + 
    ylab("t-SNE component 2") +
    scale_colour_discrete(name = "RNA cluster") +
    ggtitle(.y)
  
   p2 <- ggplot(dt, aes(V1, V3, colour = stage_lineage)) +
    geom_point(size = 2) +
    xlab("t-SNE component 1") + 
    ylab("t-SNE component 3") +
    scale_colour_discrete(name = "RNA cluster") +
    ggtitle(.y)
  
  list(p1, p2)
    
  
})

tsne


```




