```{r}
library(MOFA2)
library(ggplot2)
library(data.table)
library(purrr)
library(RColorBrewer)
```

<!-- Define settings -->
```{r}
source("/Users/ricard/mofa2_gastrulation/mofa/load_settings.R")
```

<!-- Load model -->
```{r}
source("/Users/ricard/mofa2_gastrulation/mofa/analysis/load_model.R")
```

<!-- Update some settings -->
```{r}
# io$mofa.model <- "/Users/ricard/data/gastrulation_norsync_stuff/mofa/imputation/hdf5/model_imputed_mofa.rds"
io$outdir <- "/Users/ricard/data/gastrulation_norsync_stuff/mofa/pdf/characterisation_factors/ExE_endoderm_factor"

opts$height <- 6.5
opts$width <- 4.5

# opts$colors <- c(
#   # "Epiblast"="grey70",
#   "Mesoderm"="#CD3278",
#   # "Primitive Streak"="sandybrown",
#   "Endoderm"="#43CD80",
#   "Ectoderm"="steelblue"
#   # "ExE Endoderm"="#E066FF"
# )
# 
# opts$assay.colors <- c(
#   "10x" = "#beaed4",
#   "scNMT" = "#fdc086"
# )
```

<!-- Convert M-values to B-values for DNA methylation and chromatin accessibility data -->
```{r}
views <- views_names(model)[grep("RNA",views_names(model),invert=T)]

for (m in views) {
  for (g in groups_names(model)) {
    model@data[[m]][[g]] <- 100*2**model@data[[m]][[g]]/(1+2**model@data[[m]][[g]])
    model@imputed_data[[m]][[g]]$mean <- 100*2**model@imputed_data[[m]][[g]]$mean/(1+2**model@imputed_data[[m]][[g]]$mean)
    # model@imputed_data[[m]][[g]]$variance <- 100*2**model@imputed_data[[m]][[g]]$variance/(1+2**model@imputed_data[[m]][[g]]$variance)
  }
}
```

<!-- Cap chromatin accessibility measurements (for better visualisation) -->
```{r}
opts$min.acc <- 25
opts$max.acc <- 75

views <- views_names(model)[grep("acc",views_names(model))]

for (m in views) {
  for (g in groups_names(model)) {
    model@data[[m]][[g]][model@data[[m]][[g]]<opts$min.acc] <- opts$min.acc
    model@data[[m]][[g]][model@data[[m]][[g]]>opts$max.acc] <- opts$max.acc
    model@imputed_data[[m]][[g]]$mean[model@imputed_data[[m]][[g]]$mean<opts$min.acc] <- opts$min.acc
    model@imputed_data[[m]][[g]]$mean[model@imputed_data[[m]][[g]]$mean>opts$max.acc] <- opts$max.acc
  }
}
```

<!-- Subset models -->
```{r}
# Subset scNMT-seq cells
# model.scnmt <- subset_groups(model, c("E5.5_scNMT","E6.5_scNMT","E7.5_scNMT"))
# table(model.scnmt@samples_metadata$group_name)
```


```{r}
anno_df <- model@samples_metadata[,c("sample_name","lineage10x_2")] %>%
  tibble::remove_rownames() %>% tibble::column_to_rownames("sample_name")
anno_df.scnmt <- model.scnmt@samples_metadata[,c("sample_name","lineage10x_2")] %>%
  tibble::remove_rownames() %>% tibble::column_to_rownames("sample_name")
anno_df.10x <- model.10x@samples_metadata[,c("sample_name","lineage10x_2")] %>%
  tibble::remove_rownames() %>% tibble::column_to_rownames("sample_name")
```

<!-- Plot heatmap for DNA methylation -->

Define settings
```{r}
factor <- 1
view <- "Enhancer methylation"
features <- names(tail(sort(abs(get_weights(model, views=view, factor=factor)[[1]][,1])), n=100))
```

Before imputation (scNMT cells only)
```{r}
filename <- sprintf("%s/met_heatmap.png",io$outdir)

# pdf(filename, width=opts$width, height=opts$height)
png(filename, width=opts$width, height=opts$height, units="in", res=300)
plot_data_heatmap(model,
  features = features,
  factor = factor,
  group = c("E5.5_scNMT","E6.5_scNMT","E7.5_scNMT"),
  view=view,
  # annotation_col = anno_df, annotation_colors=list("lineage10x_2"=opts$colors, "assay"=opts$assay.colors), annotation_legend = F,
  color = colorRampPalette(brewer.pal(n=9, name="YlOrRd"))(50),
  show_rownames=F, show_colnames=F,
  legend = F,
  cluster_rows=T, cluster_cols=F,
  treeheight_row = 0, treeheight_col = 0
)
dev.off()
```


After imputation (all cells)
```{r}
# filename <- sprintf("%s/met/factor%d/all_imputed.pdf",io$outdir,factor)
# 
# pdf(filename, width=opts$width, height=opts$height, useDingbats = F)
# plot_data_heatmap(model,
#   features = features,
#   factor = factor,
#   group = c("E7.5_scNMT","E7.5_10x"),
#   view=view,
#   annotation_col = anno_df, annotation_colors=list("lineage10x_2"=opts$colors, "assay"=opts$assay.colors), annotation_legend = F,
#   color = colorRampPalette(brewer.pal(n=9, name="YlOrRd"))(50),
#   show_rownames=F, show_colnames=F,
#   cluster_rows=T, cluster_cols=F,
#   treeheight_row = 0, treeheight_col = 0,
#   imputed = T
# )
# dev.off()
```

After imputation (scNMT cells)
```{r}
# filename <- sprintf("%s/met/factor%d/scNMT_imputed.pdf",io$outdir,factor)
# 
# pdf(filename, width=opts$width, height=opts$height, useDingbats = F)
# plot_data_heatmap(model,
#   features = features,
#   factor = factor,
#   group = "E7.5_scNMT",
#   view=view,
#   annotation_col = anno_df, annotation_colors=list("lineage10x_2"=opts$colors, "assay"=opts$assay.colors), annotation_legend = F,
#   color = colorRampPalette(brewer.pal(n=9, name="YlOrRd"))(50),
#   show_rownames=F, show_colnames=F,
#   cluster_rows=T, cluster_cols=F,
#   treeheight_row = 0, treeheight_col = 0,
#   imputed = T
# )
# dev.off()
```





<!-- Chromatin accessibility -->

Define settings
```{r}
view <- "Enhancer accessibility"
factor <- 1
features <- names(tail(sort(abs(get_weights(model, views=view, factor=factor)[[1]][,1])), n=100))
```

Before imputation (scNMT cells only)
```{r}
filename <- sprintf("%s/acc_heatmap.png",io$outdir)

# pdf(filename, width=opts$width, height=opts$height)
png(filename, width=opts$width, height=opts$height, units="in", res=300)
plot_data_heatmap(model,
  features = features,
  factor = factor,
  group = c("E5.5_scNMT","E6.5_scNMT"),
  view=view,
  # annotation_col = anno_df, 
  # annotation_colors = list("lineage10x_2"=opts$colors, "assay"=opts$assay.colors), 
  # annotation_legend = F,
  legend = FALSE,
  color = colorRampPalette(brewer.pal(n=9, name="PuBu"))(50),
  show_rownames=F, show_colnames=F,
  cluster_rows=T, cluster_cols=F,
  treeheight_row = 0, treeheight_col = 0,
  # imputed = F
)
dev.off()
```


After imputation (all cells)
```{r}
# filename <- sprintf("%s/acc/factor%d/all_imputed.pdf",io$outdir,factor)
# 
# pdf(filename, width=opts$width, height=opts$height, useDingbats = F)
# plot_data_heatmap(model,
#   features = features,
#   factor = factor,
#   group = c("E7.5_scNMT","E7.5_10x"),
#   view=view,
#   annotation_col = anno_df, annotation_colors=list("lineage10x_2"=opts$colors, "assay"=opts$assay.colors), annotation_legend = F,
#   color = colorRampPalette(brewer.pal(n=9, name="PuBu"))(50),
#   show_rownames=F, show_colnames=F,
#   cluster_rows=T, cluster_cols=F,
#   treeheight_row = 0, treeheight_col = 0,
#   imputed = T
# )
# dev.off()
```

After imputation (scNMT cells)
```{r}
filename <- sprintf("%s/acc/factor%d/scNMT_imputed.pdf",io$outdir,factor)

# pdf(filename, width=opts$width, height=opts$height, useDingbats = F)
plot_data_heatmap(model,
  features = features,
  factor = factor,
  # group = "E7.5_scNMT",
  view=view,
  annotation_col = anno_df, 
  annotation_colors=list("lineage10x_2"=opts$colors, "assay"=opts$assay.colors), 
  annotation_legend = F,
  color = colorRampPalette(brewer.pal(n=9, name="PuBu"))(50),
  show_rownames=F, show_colnames=F,
  cluster_rows=T, cluster_cols=F,
  treeheight_row = 0, treeheight_col = 0,
  imputed = T
)
# dev.off()
```


TEST
```{r}
# p <- plot_factor(model,
#   factor = 1,
#   color_by = "lineage10x_2",
#   dodge=F, dot_size=1, legend = F, rasterize = F
# )
# p <- p + scale_color_manual(values=opts$colors) + scale_fill_manual(values=opts$colors)
# 
# print(p)
```

